
CREATE PROCEDURE [trn].[sp_RESMODELANALYSISDATA_insert]
AS 
begin
/**************************************************************************************************
Created By: Marc Beacom
Description: view source prior to loading into the datastore
Usage: exec [trn].[sp_RESMODELANALYSISDATA_insert]
--------------------------------------------------------------------------------------------------
Date:		Name:			Comments:
20210325	Marc Beacom		Initial Creation
**************************************************************************************************/
SET NOCOUNT ON;

	MERGE	assessor_datastore.Reporting.RESMODELANALYSISDATA AS myTarget
	USING	trn.v_etl_RESMODELANALYSISDATA AS mySource
	ON		myTarget.rowhash = mySource.rowhash
	WHEN MATCHED 
		 THEN
			UPDATE SET	 
						 MyTarget.[NBHD]					=	mySource.[NBHD]				
						,MyTarget.[SUBNAME]					=	mySource.[SUBNAME]				
						,MyTarget.[ACCOUNTNO]				=	mySource.[ACCOUNTNO]			
						,MyTarget.[PARCELNO]				=	mySource.[PARCELNO]			
						,MyTarget.[STREETADDRESS]			=	mySource.[STREETADDRESS]		
						,MyTarget.[ANALYSISMODEL]			=	mySource.[ANALYSISMODEL]		
						,MyTarget.[PLANMODEL]				=	mySource.[PLANMODEL]			
						,MyTarget.[ADJYEARBUILT]			=	mySource.[ADJYEARBUILT]		
						,MyTarget.[IMPQUALITY]				=	mySource.[IMPQUALITY]			
						,MyTarget.[PROPERTYTYPE]			=	mySource.[PROPERTYTYPE] 			
						,MyTarget.[IMPUNITTYPE]				=	mySource.[IMPUNITTYPE]			
						,MyTarget.[CURRIMPCOUNT]			=	mySource.[CURRIMPCOUNT]		
						,MyTarget.[BLTASDESCRIPTION]		=	mySource.[BLTASDESCRIPTION]	
						,MyTarget.[HVACTYPE]				=	mySource.[HVACTYPE]		
						,MyTarget.[BATHCOUNT]				=	mySource.[BATHCOUNT] 			
						,MyTarget.[FPCOUNT]					=	mySource.[FPCOUNT]				
						,MyTarget.[BLTASSF]					=	mySource.[BLTASSF]				
						,MyTarget.[BASEMENTSF]				=	mySource.[BASEMENTSF]			
						,MyTarget.[FINISHEDBASEMENTSF]		=	mySource.[FINISHEDBASEMENTSF]	
						,MyTarget.[GARAGESF]				=	mySource.[GARAGESF]			
						,MyTarget.[CARPORTSF]				=	mySource.[CARPORTSF]			
						,MyTarget.[PORCHSF]					=	mySource.[PORCHSF]				
						,MyTarget.[BASEMENT]				=	mySource.[BASEMENT]			
						,MyTarget.[LANDSF]					=	mySource.[LANDSF]				
						,MyTarget.[GOLF]					=	mySource.[GOLF]				
						,MyTarget.[GREENBELT]				=	mySource.[GREENBELT]			
						,MyTarget.[POWERLINE]				=	mySource.[POWERLINE]			
						,MyTarget.[SUPVIEW]					=	mySource.[SUPVIEW]				
						,MyTarget.[TRAFFIC]					=	mySource.[TRAFFIC]				
						,MyTarget.[CULDESAC]				=	mySource.[CULDESAC]			
						,MyTarget.[TREED]					=	mySource.[TREED]				
						,MyTarget.[CORNERLOT]				=	mySource.[CORNERLOT]			
						,MyTarget.[RAILROAD]				=	mySource.[RAILROAD]			
						,MyTarget.[UNPAVEDROAD]				=	mySource.[UNPAVEDROAD]			
						,MyTarget.[RECEPTIONNO]				=	mySource.[RECEPTIONNO]			
						,MyTarget.[SALEDATE]				=	mySource.[SALEDATE]			
						,MyTarget.[ADJSALEPRICE]			=	mySource.[ADJSALEPRICE]		
						,MyTarget.[TASP]					=	mySource.[TASP]				
						,MyTarget.[VALID1FLAG]				=	mySource.[VALID1FLAG]			
						,MyTarget.[EXCLUDECODE1]			=	mySource.[EXCLUDECODE1]		
						,MyTarget.[NEWCONSTRUCTION]			=	mySource.[NEWCONSTRUCTION]		
						,MyTarget.[SALESRATIO]				=	mySource.[SALESRATIO]			
						,MyTarget.[PREVIOUSVALUE]			=	mySource.[PREVIOUSVALUE]		
						,MyTarget.[PREVIOUSYEAR]			=	mySource.[PREVIOUSYEAR]		
						,MyTarget.[CURRENTVALUE]			=	mySource.[CURRENTVALUE]		
						,MyTarget.[CURRENTYEAR]				=	mySource.[CURRENTYEAR]			
						,MyTarget.[VALUECHANGE]				=	mySource.[VALUECHANGE]			
						,MyTarget.[PRICEPERSF]				=	mySource.[PRICEPERSF]			
						,MyTarget.[COUNTAPPEAL]				=	mySource.[COUNTAPPEAL]			
						,MyTarget.[UNIQUEFEATURE]			=	mySource.[UNIQUEFEATURE]		
						,MyTarget.[AG]						=	mySource.[AG]			
						,MyTarget.[SALEPRICEPERSF]			=	mySource.[SALEPRICEPERSF]					
						,MyTarget.[Create_Datetime]			=	mySource.[Create_Datetime]		
						,MyTarget.[Create_User_ID]			=	mySource.[Create_User_ID]	

						,myTarget.update_datetime			=	GETDATE()
						,myTarget.update_user_id			=	SUSER_NAME()
						,myTarget.rowhash					=	mySource.rowhash


	WHEN NOT MATCHED BY TARGET 
		 THEN
		 INSERT (	[NBHD]
					,[SUBNAME]
					,[ACCOUNTNO]
					,[PARCELNO]
					,[STREETADDRESS]
					,[ANALYSISMODEL]
					,[PLANMODEL]
					,[ADJYEARBUILT]
					,[IMPQUALITY]
					,[PROPERTYTYPE] 
					,[IMPUNITTYPE]
					,[CURRIMPCOUNT]
					,[BLTASDESCRIPTION]
					,[HVACTYPE]
					,[BATHCOUNT] 
					,[FPCOUNT]
					,[BLTASSF]
					,[BASEMENTSF]
					,[FINISHEDBASEMENTSF]
					,[GARAGESF]
					,[CARPORTSF]
					,[PORCHSF]
					,[BASEMENT]
					,[LANDSF]
					,[GOLF]
					,[GREENBELT]
					,[POWERLINE]
					,[SUPVIEW]
					,[TRAFFIC]
					,[CULDESAC]
					,[TREED]
					,[CORNERLOT]
					,[RAILROAD]
					,[UNPAVEDROAD]
					,[RECEPTIONNO]
					,[SALEDATE]
					,[ADJSALEPRICE]
					,[TASP]
					,[VALID1FLAG]
					,[EXCLUDECODE1]
					,[NEWCONSTRUCTION]
					,[SALESRATIO]
					,[PREVIOUSVALUE]
					,[PREVIOUSYEAR]
					,[CURRENTVALUE]
					,[CURRENTYEAR]
					,[VALUECHANGE]
					,[PRICEPERSF]
					,[COUNTAPPEAL]
					,[UNIQUEFEATURE]
					,[AG]
					,[SALEPRICEPERSF]
					,[Create_Datetime]
					,[Create_User_ID]
					,[Rowhash]
				)
		 VALUES (	[NBHD]
					,[SUBNAME]
					,[ACCOUNTNO]
					,[PARCELNO]
					,[STREETADDRESS]
					,[ANALYSISMODEL]
					,[PLANMODEL]
					,[ADJYEARBUILT]
					,[IMPQUALITY]
					,[PROPERTYTYPE] 
					,[IMPUNITTYPE]
					,[CURRIMPCOUNT]
					,[BLTASDESCRIPTION]
					,[HVACTYPE]
					,[BATHCOUNT] 
					,[FPCOUNT]
					,[BLTASSF]
					,[BASEMENTSF]
					,[FINISHEDBASEMENTSF]
					,[GARAGESF]
					,[CARPORTSF]
					,[PORCHSF]
					,[BASEMENT]
					,[LANDSF]
					,[GOLF]
					,[GREENBELT]
					,[POWERLINE]
					,[SUPVIEW]
					,[TRAFFIC]
					,[CULDESAC]
					,[TREED]
					,[CORNERLOT]
					,[RAILROAD]
					,[UNPAVEDROAD]
					,[RECEPTIONNO]
					,[SALEDATE]
					,[ADJSALEPRICE]
					,[TASP]
					,[VALID1FLAG]
					,[EXCLUDECODE1]
					,[NEWCONSTRUCTION]
					,[SALESRATIO]
					,[PREVIOUSVALUE]
					,[PREVIOUSYEAR]
					,[CURRENTVALUE]
					,[CURRENTYEAR]
					,[VALUECHANGE]
					,[PRICEPERSF]
					,[COUNTAPPEAL]
					,[UNIQUEFEATURE]
					,[AG]
					,[SALEPRICEPERSF]
					,[Create_Datetime]
					,[Create_User_ID]
					,[Rowhash]
				)

	WHEN NOT MATCHED BY SOURCE
		 THEN
		 DELETE;

end	--	[trn].[sp_RESMODELANALYSISDATA_insert]