CREATE TABLE [dqm].[s_tblacctreal_err] (
    [COLUMN_NAME]              VARCHAR (100)   NOT NULL,
    [DQM_RULE]                 VARCHAR (100)   NOT NULL,
    [ERROR_DESCRIPTION]        VARCHAR (100)   NOT NULL,
    [DQM_RUN_DATE]             DATE            NOT NULL,
    [VERSTART]                 NUMERIC (11)    NULL,
    [VEREND]                   NUMERIC (11)    NULL,
    [ACCOUNTNO]                VARCHAR (30)    NULL,
    [IMPONLYFLAG]              NUMERIC (1)     NULL,
    [TIFFLAG]                  NUMERIC (1)     NULL,
    [VACANTFLAG]               NUMERIC (1)     NULL,
    [LANDWIDTH]                NUMERIC (11)    NULL,
    [LANDDEPTH]                NUMERIC (11)    NULL,
    [LANDEASEMENTSF]           NUMERIC (20, 6) NULL,
    [LANDEXCESSSF]             NUMERIC (20, 6) NULL,
    [TRAFFICCOUNT]             NUMERIC (15)    NULL,
    [PARKINGSPACES]            NUMERIC (15)    NULL,
    [ZONINGCODE]               VARCHAR (50)    NULL,
    [FLOODFRINGE]              NUMERIC (11)    NULL,
    [FLOODWAY]                 NUMERIC (11)    NULL,
    [TAPFEE]                   NUMERIC (15, 2) NULL,
    [PLATTEDFLAG]              NUMERIC (1)     NULL,
    [LANDCERTIFICATIONCODE]    VARCHAR (10)    NULL,
    [LANDAPPRAISER]            VARCHAR (20)    NULL,
    [LANDAPPRAISALDATE]        VARCHAR (22)    NULL,
    [LANDOVERRIDESIZEADJ]      NUMERIC (20, 6) NULL,
    [LANDSIZEADJ]              NUMERIC (20, 6) NULL,
    [LANDGROSSSF]              NUMERIC (20, 6) NULL,
    [LANDGROSSACRES]           NUMERIC (20, 6) NULL,
    [LANDGROSSFF]              NUMERIC (20, 6) NULL,
    [LANDGROSSUNITCOUNT]       NUMERIC (20, 6) NULL,
    [ACCTREALON0]              NUMERIC (20, 6) NULL,
    [ACCTREALON1]              NUMERIC (20, 6) NULL,
    [ACCTREALON2]              NUMERIC (20, 6) NULL,
    [ACCTREALOD0]              VARCHAR (22)    NULL,
    [ACCTREALOD1]              VARCHAR (22)    NULL,
    [ACCTREALOM0]              VARCHAR (50)    NULL,
    [ACCTREALOM1]              VARCHAR (50)    NULL,
    [ACCTREALOT0]              VARCHAR (50)    NULL,
    [ACCTREALOT1]              VARCHAR (50)    NULL,
    [JURISDICTIONID]           NUMERIC (15)    NULL,
    [DEFAULTLEA]               VARCHAR (30)    NULL,
    [TOTALACCTIMPINTERESTPCT]  NUMERIC (9, 6)  NULL,
    [TOTALACCTLANDINTERESTPCT] NUMERIC (9, 6)  NULL,
    [WRITEDATE]                VARCHAR (22)    NULL,
    [SEQID]                    NUMERIC (15)    NULL,
    [ETL_RUN_TIME]             DATETIME2 (7)   DEFAULT (getdate()) NULL
);

