CREATE TABLE [dqm].[s_tbladdresssecure_err] (
    [COLUMN_NAME]       VARCHAR (100)   NOT NULL,
    [DQM_RULE]          VARCHAR (100)   NOT NULL,
    [ERROR_DESCRIPTION] VARCHAR (100)   NOT NULL,
    [DQM_RUN_DATE]      DATE            NOT NULL,
    [VERSTART]          NUMERIC (11)    NULL,
    [VEREND]            NUMERIC (11)    NULL,
    [ADDRESSCODE]       NUMERIC (15)    NULL,
    [ADDRESS1]          VARCHAR (50)    NULL,
    [ADDRESS2]          VARCHAR (50)    NULL,
    [CITY]              VARCHAR (50)    NULL,
    [STATECODE]         VARCHAR (2)     NULL,
    [ZIPCODE]           VARCHAR (10)    NULL,
    [PERSONCODE]        NUMERIC (15)    NULL,
    [PROVINCE]          VARCHAR (50)    NULL,
    [ADDRESSON0]        NUMERIC (20, 6) NULL,
    [ADDRESSON1]        NUMERIC (20, 6) NULL,
    [ADDRESSON2]        NUMERIC (20, 6) NULL,
    [JURISDICTIONID]    NUMERIC (15)    NULL,
    [COUNTRY]           VARCHAR (100)   NULL,
    [POSTALCODE]        VARCHAR (20)    NULL,
    [ADDRESSOD0]        VARCHAR (22)    NULL,
    [ADDRESSOD1]        VARCHAR (22)    NULL,
    [ADDRESSOM0]        VARCHAR (50)    NULL,
    [ADDRESSOM1]        VARCHAR (50)    NULL,
    [ADDRESSOT0]        VARCHAR (50)    NULL,
    [ADDRESSOT1]        VARCHAR (50)    NULL,
    [ADDRESSVALIDFLAG]  NUMERIC (1)     NULL,
    [WRITEDATE]         VARCHAR (22)    NULL,
    [SEQID]             NUMERIC (15)    NULL,
    [ETL_RUN_TIME]      DATETIME2 (7)   DEFAULT (getdate()) NULL
);

