CREATE TABLE [dqm].[s_tblimpsbltas_err] (
    [COLUMN_NAME]         VARCHAR (100)   NOT NULL,
    [DQM_RULE]            VARCHAR (100)   NOT NULL,
    [ERROR_DESCRIPTION]   VARCHAR (100)   NOT NULL,
    [DQM_RUN_DATE]        DATE            NOT NULL,
    [DETAILID]            NUMERIC (15)    NULL,
    [VERSTART]            NUMERIC (11)    NULL,
    [VEREND]              NUMERIC (11)    NULL,
    [ACCOUNTNO]           VARCHAR (30)    NULL,
    [IMPNO]               NUMERIC (7, 2)  NULL,
    [BLTASCODE]           NUMERIC (15)    NULL,
    [IMPEXTERIOR]         VARCHAR (50)    NULL,
    [IMPINTERIOR]         VARCHAR (30)    NULL,
    [BLTASSTORIES]        NUMERIC (15, 2) NULL,
    [BLTASSTORYHEIGHT]    NUMERIC (15)    NULL,
    [ROOFTYPE]            VARCHAR (30)    NULL,
    [ROOFCOVER]           VARCHAR (30)    NULL,
    [FLOORCOVER]          VARCHAR (30)    NULL,
    [ROOMCOUNT]           NUMERIC (7)     NULL,
    [BEDROOMCOUNT]        NUMERIC (7, 2)  NULL,
    [BLTASTOTALUNITCOUNT] NUMERIC (15)    NULL,
    [IMPBLTASOTHER]       NUMERIC (15)    NULL,
    [CLASSCODE]           VARCHAR (10)    NULL,
    [BLTASHEIGHT]         NUMERIC (15)    NULL,
    [BLTASYEARBUILT]      NUMERIC (4)     NULL,
    [YEARREMODELED]       NUMERIC (4)     NULL,
    [REMODELEDPERCENT]    NUMERIC (15, 4) NULL,
    [EFFECTIVEAGE]        NUMERIC (5)     NULL,
    [BLTASLENGTH]         NUMERIC (15)    NULL,
    [BLTASWIDTH]          NUMERIC (15)    NULL,
    [MHTAGLENGTH]         NUMERIC (15)    NULL,
    [MHTAGWIDTH]          NUMERIC (15)    NULL,
    [BLTASSF]             NUMERIC (15)    NULL,
    [SPRINKLERSF]         NUMERIC (15)    NULL,
    [BATHCOUNT]           NUMERIC (7, 2)  NULL,
    [PRIMARYBLTASORDERNO] NUMERIC (5)     NULL,
    [JURISDICTIONID]      NUMERIC (15)    NULL,
    [HVACTYPE]            VARCHAR (30)    NULL,
    [WRITEDATE]           VARCHAR (22)    NULL,
    [SEQID]               NUMERIC (15)    NULL,
    [APEXID]              NUMERIC (15)    NULL,
    [ETL_RUN_TIME]        DATETIME2 (7)   DEFAULT (getdate()) NULL
);

