CREATE TABLE [dqm].[s_tblimps_err] (
    [COLUMN_NAME]            VARCHAR (100)   NOT NULL,
    [DQM_RULE]               VARCHAR (100)   NOT NULL,
    [ERROR_DESCRIPTION]      VARCHAR (100)   NOT NULL,
    [DQM_RUN_DATE]           DATE            NOT NULL,
    [VERSTART]               NUMERIC (11)    NULL,
    [VEREND]                 NUMERIC (11)    NULL,
    [ACCOUNTNO]              VARCHAR (30)    NULL,
    [IMPNO]                  NUMERIC (7, 2)  NULL,
    [IMPDESCRIPTION]         VARCHAR (100)   NULL,
    [COSTVALUEBY]            VARCHAR (10)    NULL,
    [MARKETVALUEBY]          VARCHAR (10)    NULL,
    [INCOMEVALUEBY]          VARCHAR (10)    NULL,
    [LANDATTRIBUTEDPCT]      NUMERIC (15, 4) NULL,
    [IMPCOMPLETEDPCT]        NUMERIC (15, 4) NULL,
    [IMPQUALITY]             VARCHAR (15)    NULL,
    [IMPUNITTYPE]            VARCHAR (30)    NULL,
    [IMPDESIGNADJPCT]        NUMERIC (15, 4) NULL,
    [IMPEXTERIORADJPCT]      NUMERIC (15, 4) NULL,
    [IMPPHYSICALDEPRPCT]     NUMERIC (15, 4) NULL,
    [FUNCTIONALOBSOLESCEPCT] NUMERIC (15, 4) NULL,
    [ECONOMICOBSOLESCEPCT]   NUMERIC (15, 4) NULL,
    [IMPOTHERADJPCT]         NUMERIC (15, 4) NULL,
    [MHTITLENO]              VARCHAR (30)    NULL,
    [MHSERIALNO]             VARCHAR (30)    NULL,
    [MHTOTALLENGTH]          NUMERIC (15)    NULL,
    [MHDECALNO]              VARCHAR (30)    NULL,
    [MHTAGNO]                VARCHAR (30)    NULL,
    [APPRAISER]              VARCHAR (20)    NULL,
    [APPRAISALDATE]          VARCHAR (22)    NULL,
    [OWNEROCCUPIEDFLAG]      NUMERIC (1)     NULL,
    [COSTMETHOD]             VARCHAR (30)    NULL,
    [MARKETMETHOD]           VARCHAR (30)    NULL,
    [INCOMEMETHOD]           VARCHAR (30)    NULL,
    [IMPCONDITIONTYPE]       VARCHAR (40)    NULL,
    [CONDOLANDPERCENT]       NUMERIC (15, 6) NULL,
    [IMPSF]                  NUMERIC (15)    NULL,
    [CONDOIMPPERCENT]        NUMERIC (15, 6) NULL,
    [IMPPERIMETER]           NUMERIC (15)    NULL,
    [IMPINTERIORADJPCT]      NUMERIC (15, 4) NULL,
    [CONDOIMPSF]             NUMERIC (15)    NULL,
    [IMPAMATEURADJPCT]       NUMERIC (15, 4) NULL,
    [IMPNETSF]               NUMERIC (15)    NULL,
    [PROPERTYTYPE]           VARCHAR (15)    NULL,
    [APPROACHTYPE]           VARCHAR (15)    NULL,
    [JURISDICTIONID]         NUMERIC (15)    NULL,
    [IMPSOT0]                VARCHAR (50)    NULL,
    [IMPSOT1]                VARCHAR (50)    NULL,
    [IMPSOM0]                VARCHAR (50)    NULL,
    [IMPSOM1]                VARCHAR (50)    NULL,
    [IMPSOD0]                VARCHAR (22)    NULL,
    [IMPSOD1]                VARCHAR (22)    NULL,
    [IMPSON0]                NUMERIC (20, 6) NULL,
    [IMPSON1]                NUMERIC (20, 6) NULL,
    [IMPSON2]                NUMERIC (20, 6) NULL,
    [WRITEDATE]              VARCHAR (22)    NULL,
    [SEQID]                  NUMERIC (15)    NULL,
    [ETL_RUN_TIME]           DATETIME2 (7)   DEFAULT (getdate()) NULL
);

