CREATE TABLE [dqm].[s_tlkpleatype_err] (
    [COLUMN_NAME]       VARCHAR (100) NOT NULL,
    [DQM_RULE]          VARCHAR (100) NOT NULL,
    [ERROR_DESCRIPTION] VARCHAR (100) NOT NULL,
    [DQM_RUN_DATE]      DATE          NOT NULL,
    [LEA]               VARCHAR (30)  NULL,
    [LEADESCRIPTION]    VARCHAR (50)  NULL,
    [SORTORDER]         NUMERIC (9)   NULL,
    [ACTIVEFLAG]        NUMERIC (1)   NULL,
    [JURISDICTIONID]    NUMERIC (15)  NULL,
    [LASTUPDATED]       VARCHAR (22)  NULL
);

