-- =============================================
-- Author:		ktotten
-- Create date: 2023-09-26
-- Description:	Encapsulate logic for TBLLANDABSTRACT with parameters for ETL
-- =============================================
CREATE PROCEDURE [dbo].[usp_landabstract]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.

    -- Change this to reflect the correct environment PRRW_[env]
    -- Env Databbase Name
    -- DV  PRRW_Test
    -- UA  PRRW_Upgrade
    -- PR  PRRW

	SET NOCOUNT ON;

DECLARE @FREEZE_FLAG VARCHAR(1);
SELECT @FREEZE_FLAG = (SELECT PARAMETER_VALUE FROM [rw_extract].[etl_parameter] WHERE PARAMETER_NAME = 'ASR_VALUE_FREEZE_FLAG');


SELECT			T1.ACCOUNTNO, T1.VERSTART, T1.VEREND, T1.LANDTYPE, T1.ABSTRACTCODE, T1.LANDACRES, T1.LANDSF, T1.LANDFF, T1.LANDUNITCOUNT, T1.LANDVALUEPER, T1.LANDVALUE, T1.LANDOVERRIDEFLAG, 
                         T1.LANDOVERRIDETOTAL, T1.LANDACTUALTOTAL, T1.LANDCLASS, T1.LANDSUBCLASS, T1.LANDVALUEBY, T1.LANDVALUEMEASURE, CAST(T1.ABSTRACTINDATE AS VARCHAR(22)) AS ABSTRACTINDATE, 
                         CAST(T1.ABSTRACTOUTDATE AS VARCHAR(22)) AS ABSTRACTOUTDATE, T1.PRORATETYPE, T1.LANDACTIVEFLAG, T1.DETAILID, T1.ABSTRACTADJCODE, T1.LANDVALUEPERADJFACTOR, T1.ATTRIBUTEADJFLAG, 
                         T1.LANDADJSIZE, T1.LANDOVERRIDEADJSIZE, T1.LANDABSTRACTON0, T1.LANDABSTRACTON1, T1.LANDABSTRACTON2, T1.LANDOVERRIDEVALUEPER, T1.TAXDISTRICT, 
                         CAST(T1.LANDABSTRACTOD0 AS VARCHAR(22)) AS LANDABSTRACTOD0, CAST(T1.LANDABSTRACTOD1 AS VARCHAR(22)) AS LANDABSTRACTOD1, T1.LANDABSTRACTOM0, T1.LANDABSTRACTOM1, 
                         T1.LANDABSTRACTOT0, T1.LANDABSTRACTOT1, T1.JURISDICTIONID, CAST(T1.WRITEDATE AS VARCHAR(22)) AS WRITEDATE, T1.MSALANDVALUE, T1.MSALANDVALUEPER, T1.LEA, T1.SEQID
FROM            PRRW_[env].ENCOMPASS.TBLLANDABSTRACT AS T1 
INNER JOIN
                             (SELECT        CAST(PARAMETER_VALUE AS numeric) AS verstart
                               FROM            rw_extract.etl_parameter
                               WHERE        (@FREEZE_FLAG = 'Y' AND PARAMETER_NAME = 'ASR_VALUE_FREEZE_VERSION_START_DATE')
							             OR (@FREEZE_FLAG = 'N' AND PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE')
							  ) AS p1 ON T1.VERSTART <= p1.verstart INNER JOIN
                             (SELECT        CAST(PARAMETER_VALUE AS numeric) AS verend
                               FROM            rw_extract.etl_parameter
                               WHERE        (@FREEZE_FLAG = 'Y' AND PARAMETER_NAME = 'ASR_VALUE_FREEZE_VERSION_END_DATE')
							             OR (@FREEZE_FLAG = 'N' AND PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE')
							  ) AS p2 ON T1.VEREND > p2.verend
END -- proc
GO