

create view [asr_opendata].[v_imp_segment]
as

SELECT
  Q_TBLIMPSBLTAS.HVACTYPE HVAC,
  Q_TBLIMPSBLTAS.BLTASSF BLTASSF,
  FLOOR(Q_TBLIMPSBLTAS.BLTASSTORIES) STORIES,
  Q_TBLIMPSBLTAS.BLTASSTORYHEIGHT STORYHT,
  cast(Q_TBLIMPSBLTAS.SPRINKLERSF as numeric (8,0)) SPRINKLERSF,
  FLOOR(Q_TBLIMPSBLTAS.BATHCOUNT) BATHS,
  Q_TBLIMPSBLTAS.BLTASTOTALUNITCOUNT UNITS,
  Q_TBLIMPSBLTAS.BLTASYEARBUILT YRBLT,
  Q_TBLIMPSBLTAS.YEARREMODELED YRREM,
  FLOOR(Q_TBLIMPSBLTASVALUE.PHYSICALAGE) PHYSICALAGE,
  FLOOR(Q_TBLIMPSBLTAS.EFFECTIVEAGE) EFFAGE,
  Q_TBLIMPSBLTAS.BLTASLENGTH BLTASLENGTH,
  Q_TBLIMPSBLTAS.BLTASWIDTH BLTASWIDTH,
  Q_TBLIMPSBLTAS.ROOMCOUNT ROOMS,
  FLOOR(Q_TBLIMPSBLTAS.BEDROOMCOUNT) BEDROOMS,
  Q_TBLIMPSBLTAS.BLTASCODE BLTASID,
  Q_TBLIMPSBLTAS.ROOFTYPE ROOFTYPE,
  Q_TBLIMPSBLTAS.IMPEXTERIOR EXTERIOR,
  Q_TBLIMPSBLTAS.IMPINTERIOR INTERIOR,
  Q_TBLIMPSBLTAS.ROOFCOVER ROOFCOVER,
  Q_TBLIMPSBLTAS.FLOORCOVER FLOORCOVER
FROM [assessor_datastore].[asr_datastore].[improvement] IMPROVEMENT   
 JOIN   dqm.Q_TBLIMPSBLTAS  Q_TBLIMPSBLTAS ON ( (( IMPROVEMENT.ACCOUNT_NO = Q_TBLIMPSBLTAS.ACCOUNTNO )) AND (( IMPROVEMENT.improvement_no = floor ( Q_TBLIMPSBLTAS.IMPNO  ) )) )
JOIN   dqm.Q_TBLIMPSBLTASVALUE  Q_TBLIMPSBLTASVALUE ON ( (( IMPROVEMENT.ACCOUNT_NO = Q_TBLIMPSBLTASVALUE.ACCOUNTNO )) AND (( IMPROVEMENT.improvement_no = floor( Q_TBLIMPSBLTASVALUE.IMPNO  ) )) AND (( Q_TBLIMPSBLTAS.BLTASCODE = Q_TBLIMPSBLTASVALUE.BLTASCODE )) AND (( Q_TBLIMPSBLTAS.IMPNO = Q_TBLIMPSBLTASVALUE.IMPNO )) AND (( Q_TBLIMPSBLTAS.ACCOUNTNO = Q_TBLIMPSBLTASVALUE.ACCOUNTNO )) );


