

create view [asr_opendata].[v_property_sale]
as

select 
ACCOUNT_NO, RECORDING_NO, ACCOUNT_TYPE_CODE, SUBDIVISION_NO, SUB_FILING_RECORDING_NO, LOT_NO, BLOCK_NO, PROPERTY_TYPE_CODE, QUALITY_CODE, BUILT_YEAR, BASEMENT_UNFINISHED_SF, BASEMENT_FINISHED_SF, WALKOUT_BASEMENT_FLAG, GARAGE_SF, NET_ACRES, OCCUPANCY_CODE, HEAT_TYPE, BUILT_AS_CODE, NO_OF_BEDROOM, NO_OF_BATHROOM, UNIT_TYPE, TOTAL_IMP_SF, DISTRESSED_SALE_FLAG, LAND_VALUATION_CLASS_CODE, LAND_ECONOMIC_AREA_CODE, NEIGHBORHOOD_CODE, NEIGHBORHOOD_EXTENSION, NO_OF_BUILDING, VALID_ARMS_LENGTH_TRANS_FLAG
from [assessor_datastore].[asr_datastore].[property_sale]
;


