
create view asr_opendata.v_sub_filing
as

SELECT
  S_TBNSUBFILING.SUBNO SUBNO_1_1,
  S_TBNSUBFILING.SUBFILINGRECORDINGNO RECORDINGNO,
  S_TBNSUBFILING.FILINGNO FILINGNO,
  S_TBNSUBFILING.SUBFILINGDESCRIPTION FILINGDESC,
  S_TBNSUBDIVISION.SUBNAME SUBNAME
FROM
    asr_staging.S_TBNSUBDIVISION   
 JOIN   asr_staging.S_TBNSUBFILING ON ( ( S_TBNSUBDIVISION.SUBNO = S_TBNSUBFILING.SUBNO ) );

