CREATE TABLE [asr_api_test].[AccountImprovementData] (
    [id]                               INT             IDENTITY (1, 1) NOT NULL,
    [accountNo]                        VARCHAR (30)    NOT NULL,
    [buildingNumber]                   NUMERIC (5)     NULL,
    [propertyType]                     VARCHAR (50)    NULL,
    [completedPercent]                 NUMERIC (7, 4)  NULL,
    [quality]                          VARCHAR (50)    NULL,
    [perimeter]                        NUMERIC (15)    NULL,
    [netSquareFeet]                    NUMERIC (15)    NULL,
    [improvementIsPrimary]             BIT             NULL,
    [unitType]                         VARCHAR (30)    NULL,
    [approachType]                     VARCHAR (50)    NULL,
    [condition_type]                   VARCHAR (50)    NULL,
    [type]                             VARCHAR (50)    NULL,
    [subtype]                          VARCHAR (100)   NULL,
    [unitCount]                        NUMERIC (15, 4) NULL,
    [detailBuiltYear]                  VARCHAR (4)     NULL,
    [addonCode]                        VARCHAR (50)    NULL,
    [addonCodeDescription]             VARCHAR (100)   NULL,
    [useCode]                          VARCHAR (50)    NULL,
    [useCodeDescription]               VARCHAR (100)   NULL,
    [usePercentage]                    NUMERIC (7, 4)  NULL,
    [occupancyAbstractCode]            VARCHAR (50)    NULL,
    [occupancyAbstractCodeDescription] VARCHAR (100)   NULL,
    [abstractValue]                    NUMERIC (15)    NULL,
    [occupancyIsPrimary]               BIT             NULL,
    [styleCode]                        VARCHAR (50)    NULL,
    [styleCodeDescription]             VARCHAR (100)   NULL,
    [builtAsBuiltYear]                 VARCHAR (4)     NULL,
    [squareFeet]                       NUMERIC (15)    NULL,
    [builtASAbstractCode]              VARCHAR (50)    NULL,
    [builtAsAbstractCodeDescription]   VARCHAR (100)   NULL,
    [bedroomCount]                     NUMERIC (7, 2)  NULL,
    [bathroomCount]                    NUMERIC (7, 2)  NULL,
    [effectiveAge]                     NUMERIC (5)     NULL,
    [exterior_construction_type]       VARCHAR (50)    NULL,
    [floorMaterialType]                VARCHAR (50)    NULL,
    [heatType]                         VARCHAR (50)    NULL,
    [hvacPercent]                      NUMERIC (7, 4)  NULL,
    [interiorFinishType]               VARCHAR (50)    NULL,
    [numberOfStories]                  NUMERIC (5, 2)  NULL,
    [remodeledPercent]                 NUMERIC (7, 4)  NULL,
    [remodeledYear]                    VARCHAR (4)     NULL,
    [roofConstructionType]             VARCHAR (50)    NULL,
    [roofMaterialType]                 VARCHAR (50)    NULL,
    [numberOfRooms]                    NUMERIC (7)     NULL,
    [sprinklerCoverageSquareFeet]      NUMERIC (15)    NULL,
    [totalUnitCount]                   NUMERIC (7)     NULL,
    [typicalStoryHeight]               NUMERIC (5)     NULL,
    [builtAsIsPrimary]                 BIT             NULL,
    [length]                           NUMERIC (15)    NULL,
    [width]                            NUMERIC (15)    NULL,
    [height]                           NUMERIC (15)    NULL,
    [mobileHomeMake]                   VARCHAR (50)    NULL,
    [mobileHomeModelType]              VARCHAR (30)    NULL,
    [mobileHomeSkirt]                  VARCHAR (30)    NULL,
    [mobileHomeSkirtLinearFeet]        NUMERIC (15)    NULL,
    [mobileHomeWallType]               VARCHAR (32)    NULL,
    [BasementUnfinishedSQFT]           NUMERIC (15, 4) NULL,
    [BasementUnfinishedPct]            NUMERIC (10, 4) NULL,
    [BasementFinishedSQFT]             NUMERIC (15, 4) NULL,
    [BasementFinishedPct]              NUMERIC (10, 4) NULL,
    [BasementFinishedFlag]             VARCHAR (1)     NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_AccountImprovementData_AccountLevelData] FOREIGN KEY ([accountNo]) REFERENCES [asr_api_test].[AccountLevelData_Old] ([accountNumber]) NOT FOR REPLICATION
);


GO
ALTER TABLE [asr_api_test].[AccountImprovementData] NOCHECK CONSTRAINT [FK_AccountImprovementData_AccountLevelData];

