CREATE TABLE [asr_staging].[etl_parameter] (
    [PARAMETER_NAME]  VARCHAR (50)   NOT NULL,
    [PARAMETER_VALUE] VARCHAR (100)  NULL,
    [PARAMETER_DESCR] VARCHAR (1000) NULL,
    [CREATE_DTM]      DATETIME2 (7)  CONSTRAINT [DF_etl_parameter_CREATE_DTM] DEFAULT (getdate()) NULL,
    [CREATE_USER_ID]  VARCHAR (30)   CONSTRAINT [DF_etl_parameter_CREATE_USER_ID] DEFAULT (suser_name()) NULL,
    [UPDATE_DTM]      DATETIME2 (7)  NULL,
    [UPDATE_USER_ID]  VARCHAR (30)   NULL,
    CONSTRAINT [pk_etl_parameter] PRIMARY KEY CLUSTERED ([PARAMETER_NAME] ASC)
);

