CREATE TABLE [asr_staging].[s_nodtable2] (
    [HEADER]                     VARCHAR (2)    NOT NULL,
    [AGENT_FLAG]                 VARCHAR (1)    NOT NULL,
    [REVIEWNUMBER]               NUMERIC (15)   NOT NULL,
    [TAXYEAR]                    NUMERIC (4)    NULL,
    [ACCOUNTNO]                  VARCHAR (30)   NOT NULL,
    [SUBLOT]                     VARCHAR (6)    NULL,
    [SUBBLOCK]                   VARCHAR (6)    NULL,
    [DESC1]                      VARCHAR (50)   NULL,
    [DESC2]                      VARCHAR (50)   NULL,
    [DESC3]                      VARCHAR (50)   NULL,
    [DESC4]                      VARCHAR (50)   NULL,
    [A/D]                        VARCHAR (30)   NULL,
    [PRIORVALUE1]                VARCHAR (8000) NULL,
    [PRIORVALUE2]                VARCHAR (8000) NULL,
    [PRIORVALUE3]                VARCHAR (8000) NULL,
    [PRIORVALUE4]                VARCHAR (50)   NULL,
    [CURRENTVALUE1]              VARCHAR (8000) NULL,
    [CURRENTVALUE2]              VARCHAR (8000) NULL,
    [CURRENTVALUE3]              VARCHAR (8000) NULL,
    [CURRENTVALUE4]              VARCHAR (50)   NULL,
    [PETVALUETOTAL]              VARCHAR (8000) NULL,
    [PRIORVALUETOTAL]            VARCHAR (8000) NULL,
    [CURRENTVALUETOTAL]          VARCHAR (8000) NULL,
    [APPEALACCTADJUSTDENYREASON] VARCHAR (255)  NULL,
    [APPEALACCTREASONDESC]       VARCHAR (1000) NULL,
    [SUBNAME]                    VARCHAR (255)  NULL,
    [FILINGNO]                   VARCHAR (30)   NULL
);

