CREATE TABLE [asr_staging].[s_ppogtype] (
    [PPOGTYPE]        VARCHAR (4)   NULL,
    [PPOGDESCRIPTION] VARCHAR (200) NULL,
    [APPRAISALTYPE]   VARCHAR (30)  NULL,
    [ACTIVEFLAG]      NUMERIC (1)   NULL,
    [SORTORDER]       NUMERIC (9)   NULL,
    [JURISDICTIONID]  NUMERIC (15)  NULL,
    [LASTUPDATED]     VARCHAR (22)  NULL
);

