CREATE TABLE [asr_staging].[s_tblsale] (
    [VERSTART]                NUMERIC (11)    NULL,
    [VEREND]                  NUMERIC (11)    NULL,
    [RECEPTIONNO]             VARCHAR (30)    NULL,
    [BOOK]                    VARCHAR (6)     NULL,
    [PAGE]                    VARCHAR (10)    NULL,
    [GRANTOR]                 VARCHAR (80)    NULL,
    [GRANTEE]                 VARCHAR (80)    NULL,
    [DOCUMENTDATE]            VARCHAR (22)    NULL,
    [SALEDATE]                VARCHAR (22)    NULL,
    [DOCUMENTFEE]             NUMERIC (15, 2) NULL,
    [DEEDCODE]                VARCHAR (10)    NULL,
    [PENALTYFLAG]             NUMERIC (1)     NULL,
    [PENALTYDATE]             VARCHAR (22)    NULL,
    [SALEPRICE]               NUMERIC (15, 2) NULL,
    [PPADJAMOUNT]             NUMERIC (15, 2) NULL,
    [GOODWILLADJAMOUNT]       NUMERIC (15, 2) NULL,
    [OTHERADJAMOUNT]          NUMERIC (15, 2) NULL,
    [TIMEADJ]                 NUMERIC (15, 4) NULL,
    [DOWNPAYMENTAMOUNT]       NUMERIC (15, 2) NULL,
    [DOWNPAYMENTPCT]          NUMERIC (15, 4) NULL,
    [NOTEAMOUNT]              NUMERIC (15, 2) NULL,
    [INTERESTRATEPCT]         NUMERIC (15, 4) NULL,
    [LOANTERM]                NUMERIC (15, 4) NULL,
    [POINTSPAID]              NUMERIC (15, 4) NULL,
    [POINTSPAIDBY]            VARCHAR (30)    NULL,
    [LOANINSTITUTION]         VARCHAR (50)    NULL,
    [MKTRATEPCT]              NUMERIC (15, 4) NULL,
    [PAYMENTAMOUNT]           NUMERIC (15, 2) NULL,
    [RECOURSEFLAG]            NUMERIC (1)     NULL,
    [TENANT]                  VARCHAR (30)    NULL,
    [VALID1FLAG]              NUMERIC (1)     NULL,
    [VALID2FLAG]              NUMERIC (1)     NULL,
    [CONFIRMEDFLAG]           NUMERIC (1)     NULL,
    [EXCLUDECODE1]            VARCHAR (10)    NULL,
    [EXCLUDECODE2]            VARCHAR (10)    NULL,
    [IMPROVEDFLAG]            NUMERIC (1)     NULL,
    [CONFIRMBY]               VARCHAR (30)    NULL,
    [CONFIRMMETHOD]           VARCHAR (30)    NULL,
    [CONFIRMDATE]             VARCHAR (22)    NULL,
    [COMMENTS]                VARCHAR (500)   NULL,
    [NONSALEFLAG]             NUMERIC (1)     NULL,
    [SALEON0]                 NUMERIC (20, 6) NULL,
    [SALEON1]                 NUMERIC (20, 6) NULL,
    [SALEON2]                 NUMERIC (20, 6) NULL,
    [SALEOD0]                 VARCHAR (22)    NULL,
    [SALEOD1]                 VARCHAR (22)    NULL,
    [SALEOM0]                 VARCHAR (50)    NULL,
    [SALEOM1]                 VARCHAR (50)    NULL,
    [SALEOT0]                 VARCHAR (50)    NULL,
    [SALEOT1]                 VARCHAR (50)    NULL,
    [JURISDICTIONID]          NUMERIC (15)    NULL,
    [WRITEDATE]               VARCHAR (22)    NULL,
    [BALLOONPAYMENTYEAR]      NUMERIC (4)     NULL,
    [TRANSFERDECLARATIONFLAG] NUMERIC (1)     NULL,
    [TRANSFERDECLARATIONDATE] VARCHAR (22)    NULL,
    [QUESTIONNAIREMAILDATE]   VARCHAR (22)    NULL,
    [QUESTIONNAIRERETURNDATE] VARCHAR (22)    NULL,
    [SEQID]                   NUMERIC (15)    NULL
);


GO
CREATE CLUSTERED INDEX [s_tblsale_ClusteredIndex-receptionno]
    ON [asr_staging].[s_tblsale]([RECEPTIONNO] ASC);

