CREATE TABLE [asr_staging].[s_tblacctowneraddress] (
    [VERSTART]            NUMERIC (11)    NULL,
    [VEREND]              NUMERIC (11)    NULL,
    [ACCOUNTNO]           VARCHAR (30)    NULL,
    [PERSONCODE]          NUMERIC (15)    NULL,
    [ADDRESSCODE]         NUMERIC (15)    NULL,
    [PRIMARYOWNERFLAG]    NUMERIC (1)     NULL,
    [ACCTOWNERADDRESSON0] NUMERIC (20, 6) NULL,
    [ACCTOWNERADDRESSON1] NUMERIC (20, 6) NULL,
    [ACCTOWNERADDRESSON2] NUMERIC (20, 6) NULL,
    [ACCTOWNERADDRESSOD0] VARCHAR (22)    NULL,
    [ACCTOWNERADDRESSOD1] VARCHAR (22)    NULL,
    [ACCTOWNERADDRESSOM0] VARCHAR (50)    NULL,
    [ACCTOWNERADDRESSOM1] VARCHAR (50)    NULL,
    [ACCTOWNERADDRESSOT0] VARCHAR (50)    NULL,
    [ACCTOWNERADDRESSOT1] VARCHAR (50)    NULL,
    [JURISDICTIONID]      NUMERIC (15)    NULL,
    [OWNERPERCENT]        NUMERIC (9, 8)  NULL,
    [WRITEDATE]           VARCHAR (22)    NULL,
    [SEQID]               NUMERIC (15)    NULL,
    [OWNERSHIPTYPE]       VARCHAR (50)    NULL,
    [ETL_RUN_TIME]        DATETIME2 (7)   DEFAULT (getdate()) NULL
);

