CREATE TABLE [asr_staging].[s_tblacct] (
    [VERSTART]                NUMERIC (11)    NULL,
    [VEREND]                  NUMERIC (11)    NULL,
    [ACCOUNTNO]               VARCHAR (30)    NULL,
    [PARCELNO]                VARCHAR (30)    NULL,
    [LOCALNO]                 VARCHAR (30)    NULL,
    [MAPNO]                   VARCHAR (40)    NULL,
    [ACCTSTATUSCODE]          VARCHAR (1)     NULL,
    [ACCTTYPE]                VARCHAR (15)    NULL,
    [ASSIGNEDTO]              VARCHAR (20)    NULL,
    [VALUEAREACODE]           VARCHAR (10)    NULL,
    [ASSOCIATEDACCT]          VARCHAR (30)    NULL,
    [APPRAISALTYPE]           VARCHAR (30)    NULL,
    [ECONOMICAREACODE]        VARCHAR (10)    NULL,
    [ACCTDATECREATED]         VARCHAR (22)    NULL,
    [DEFAULTAPPROACHTYPE]     VARCHAR (15)    NULL,
    [DEFAULTTAXDISTRICT]      VARCHAR (10)    NULL,
    [BUSINESSLICENSE]         VARCHAR (10)    NULL,
    [MAPGROUP]                VARCHAR (2)     NULL,
    [CONTROLMAP]              VARCHAR (5)     NULL,
    [PROPERTYIDENTIFIER]      VARCHAR (1)     NULL,
    [SPECIALINTERESTNUMBER]   VARCHAR (3)     NULL,
    [ACCTON0]                 NUMERIC (20, 6) NULL,
    [ACCTON1]                 NUMERIC (20, 6) NULL,
    [ACCTON2]                 NUMERIC (20, 6) NULL,
    [PRIMARYUSECODE]          VARCHAR (10)    NULL,
    [WARD]                    VARCHAR (2)     NULL,
    [ACCTOD0]                 VARCHAR (22)    NULL,
    [ACCTOD1]                 VARCHAR (22)    NULL,
    [ACCTOM0]                 VARCHAR (50)    NULL,
    [ACCTOM1]                 VARCHAR (50)    NULL,
    [STRIPPEDACCOUNTNO]       VARCHAR (30)    NULL,
    [JURISDICTIONID]          NUMERIC (15)    NULL,
    [ACCTOT0]                 VARCHAR (50)    NULL,
    [ACCTOT1]                 VARCHAR (50)    NULL,
    [WRITEDATE]               VARCHAR (22)    NULL,
    [CENSUSTRACT]             NUMERIC (6, 2)  NULL,
    [CENSUSBLOCK]             NUMERIC (6, 2)  NULL,
    [MOBILEHOMESPACE]         VARCHAR (10)    NULL,
    [EFILEFLAG]               NUMERIC (1)     NULL,
    [BUSINESSNAME]            VARCHAR (255)   NULL,
    [COSTHYBRIDPERCENT]       NUMERIC (15, 4) NULL,
    [MARKETHYBRIDPERCENT]     NUMERIC (15, 4) NULL,
    [INCOMEHYBRIDPERCENT]     NUMERIC (15, 4) NULL,
    [RECONCILEDHYBRIDPERCENT] NUMERIC (15, 4) NULL,
    [PARCELSEQUENCE]          NUMERIC (4)     NULL,
    [PROPERTYCLASSID]         NUMERIC (15)    NULL,
    [SEQID]                   NUMERIC (15)    NULL,
    [DETAILEDREVIEWDATE]      VARCHAR (22)    NULL,
    [ETL_RUN_TIME]            DATETIME2 (7)   DEFAULT (getdate()) NULL
);


GO
CREATE CLUSTERED INDEX [IX_s_tblacct_ClusteredIndex-accountno]
    ON [asr_staging].[s_tblacct]([ACCOUNTNO] ASC);

