CREATE TABLE [asr_staging].[s_tblacctparentparcel] (
    [VERSTART]            NUMERIC (11)    NULL,
    [VEREND]              NUMERIC (11)    NULL,
    [ACCOUNTNO]           VARCHAR (30)    NULL,
    [PARENTACCOUNT]       VARCHAR (30)    NULL,
    [PARENTACCOUNTON0]    NUMERIC (20, 6) NULL,
    [PARENTACCOUNTON1]    NUMERIC (20, 6) NULL,
    [PARENTACCOUNTON2]    NUMERIC (20, 6) NULL,
    [ACCTPARENTPARCELOD0] DATETIME2 (0)   NULL,
    [ACCTPARENTPARCELOD1] DATETIME2 (0)   NULL,
    [ACCTPARENTPARCELOM0] VARCHAR (50)    NULL,
    [ACCTPARENTPARCELOM1] VARCHAR (50)    NULL,
    [ACCTPARENTPARCELOT0] VARCHAR (50)    NULL,
    [ACCTPARENTPARCELOT1] VARCHAR (50)    NULL,
    [JURISDICTIONID]      NUMERIC (15)    NULL,
    [WRITEDATE]           DATETIME2 (0)   NULL,
    [SEQID]               NUMERIC (15)    NULL
);

