CREATE TABLE [asr_staging].[s_tblacctlegal] (
    [VERSTART]         NUMERIC (11)    NULL,
    [VEREND]           NUMERIC (11)    NULL,
    [ACCOUNTNO]        VARCHAR (30)    NULL,
    [LEGAL]            VARCHAR (4000)  NULL,
    [ACCTLEGALON0]     NUMERIC (20, 6) NULL,
    [ACCTLEGALON1]     NUMERIC (20, 6) NULL,
    [ACCTLEGALON2]     NUMERIC (20, 6) NULL,
    [ACCTLEGALOD0]     VARCHAR (22)    NULL,
    [ACCTLEGALOD1]     VARCHAR (22)    NULL,
    [ACCTLEGALOM0]     VARCHAR (50)    NULL,
    [ACCTLEGALOM1]     VARCHAR (50)    NULL,
    [ACCTLEGALOT0]     VARCHAR (50)    NULL,
    [ACCTLEGALOT1]     VARCHAR (50)    NULL,
    [JURISDICTIONID]   NUMERIC (15)    NULL,
    [WRITEDATE]        VARCHAR (22)    NULL,
    [SEQID]            NUMERIC (15)    NULL,
    [SHORTDESCRIPTION] VARCHAR (255)   NULL,
    [ETL_RUN_TIME]     DATETIME2 (7)   DEFAULT (getdate()) NULL
);

