CREATE TABLE [asr_staging].[s_tbnsaleinventory] (
    [RECEPTIONNO]               VARCHAR (30)    NULL,
    [ACCOUNTNO]                 VARCHAR (30)    NULL,
    [PARCELNO]                  VARCHAR (30)    NULL,
    [INVENTORYEFFECTIVEDATE]    VARCHAR (22)    NULL,
    [SALEDATE]                  VARCHAR (22)    NULL,
    [SALEPRICE]                 NUMERIC (15, 2) NULL,
    [ADJSALEPRICE]              NUMERIC (15, 2) NULL,
    [SALEVALUEPER]              NUMERIC (15, 2) NULL,
    [ACCTTYPE]                  VARCHAR (15)    NULL,
    [ECONOMICAREACODE]          VARCHAR (10)    NULL,
    [LEA]                       VARCHAR (30)    NULL,
    [SUBDIVISION]               VARCHAR (30)    NULL,
    [VALUEAREACODE]             VARCHAR (10)    NULL,
    [PROPERTYTYPE]              VARCHAR (15)    NULL,
    [IMPCONDITIONTYPE]          VARCHAR (40)    NULL,
    [IMPQUALITY]                VARCHAR (15)    NULL,
    [IMPABSTRACTCODE]           VARCHAR (10)    NULL,
    [BLTASDESCRIPTION]          VARCHAR (50)    NULL,
    [BLTASYEARBUILT]            NUMERIC (4)     NULL,
    [PHYSICALAGE]               NUMERIC (4)     NULL,
    [ADJUSTEDYEARBUILT]         NUMERIC (4)     NULL,
    [EFFECTIVEAGE]              NUMERIC (5)     NULL,
    [IMPEXTERIOR]               VARCHAR (50)    NULL,
    [CLASSCODE]                 VARCHAR (10)    NULL,
    [IMPCOUNT]                  NUMERIC (15)    NULL,
    [BLTASTOTALUNITCOUNT]       NUMERIC (15)    NULL,
    [ROOMCOUNT]                 NUMERIC (7)     NULL,
    [BEDROOMCOUNT]              NUMERIC (7, 2)  NULL,
    [BATHCOUNT]                 NUMERIC (7, 2)  NULL,
    [FIXTURECOUNT]              NUMERIC (15)    NULL,
    [TOTALIMPSF]                NUMERIC (15, 2) NULL,
    [RESIDENTIALSF]             NUMERIC (15, 2) NULL,
    [COMMERCIALSF]              NUMERIC (15, 2) NULL,
    [CONDOIMPSF]                NUMERIC (15)    NULL,
    [OUTBUILDINGSF]             NUMERIC (15, 2) NULL,
    [IMPBLTASOTHER]             NUMERIC (15)    NULL,
    [LANDNETSF]                 NUMERIC (20, 6) NULL,
    [MULTIPLEUSEFLAG]           NUMERIC (1)     NULL,
    [LANDTYPE]                  VARCHAR (15)    NULL,
    [LANDABSTRACTCODE]          VARCHAR (10)    NULL,
    [LANDCERTIFICATIONCODE]     VARCHAR (10)    NULL,
    [LANDGROSSACRECOUNT]        NUMERIC (20, 6) NULL,
    [LANDGROSSSF]               NUMERIC (20, 6) NULL,
    [LANDGROSSFF]               NUMERIC (20, 6) NULL,
    [LANDGROSSUNITCOUNT]        NUMERIC (20, 6) NULL,
    [ZONINGCODE]                VARCHAR (50)    NULL,
    [PLATTEDFLAG]               NUMERIC (1)     NULL,
    [UNITNAME]                  VARCHAR (6)     NULL,
    [ACCTADJSALEVALUEPER]       NUMERIC (15, 2) NULL,
    [TOTALLANDVALUETIMEOFSALE]  NUMERIC (15, 2) NULL,
    [TOTALACCTVALUETIMEOFSALE]  NUMERIC (15, 2) NULL,
    [PRIORYEARTAXROLLACTUALAMT] NUMERIC (15, 2) NULL,
    [PRIORYEARTAXROLLASSESSED]  NUMERIC (15, 2) NULL,
    [LANDNETACRECOUNT]          NUMERIC (20, 6) NULL,
    [HVACTYPE]                  VARCHAR (30)    NULL,
    [IMPUNITTYPE]               VARCHAR (30)    NULL,
    [IMPINTERIOR]               VARCHAR (30)    NULL,
    [ROOFCOVER]                 VARCHAR (30)    NULL,
    [ROOFTYPE]                  VARCHAR (30)    NULL,
    [INVENTORYOVERRIDEFLAG]     NUMERIC (1)     NULL,
    [ZONEDAREA]                 NUMERIC (20, 6) NULL,
    [NBHDCODE1]                 VARCHAR (10)    NULL,
    [NBHDCODE2]                 VARCHAR (10)    NULL,
    [NBHDCODE3]                 VARCHAR (10)    NULL,
    [NBHDCODE4]                 VARCHAR (10)    NULL,
    [NBHDEXTENSION1]            VARCHAR (10)    NULL,
    [NBHDEXTENSION2]            VARCHAR (10)    NULL,
    [NBHDEXTENSION3]            VARCHAR (10)    NULL,
    [NBHDEXTENSION4]            VARCHAR (10)    NULL,
    [OCCCODE1]                  NUMERIC (15)    NULL,
    [OCCCODE2]                  NUMERIC (15)    NULL,
    [OCCCODE3]                  NUMERIC (15)    NULL,
    [ACCTADJSALEPRICE]          NUMERIC (15, 2) NULL,
    [TIMEADJSALEPRICE]          NUMERIC (15, 2) NULL,
    [DEEDCODE]                  VARCHAR (10)    NULL,
    [VALID1FLAG]                NUMERIC (1)     NULL,
    [VALID2FLAG]                NUMERIC (1)     NULL,
    [EXCLUDECODE1]              VARCHAR (10)    NULL,
    [EXCLUDECODE2]              VARCHAR (10)    NULL,
    [IMPROVEDFLAG]              NUMERIC (1)     NULL,
    [CONFIRMEDFLAG]             NUMERIC (1)     NULL,
    [BUSINESSNAME]              VARCHAR (255)   NULL,
    [STREETNO]                  VARCHAR (15)    NULL,
    [PREDIRECTION]              VARCHAR (2)     NULL,
    [STREETNAME]                VARCHAR (50)    NULL,
    [STREETTYPE]                VARCHAR (4)     NULL,
    [POSTDIRECTION]             VARCHAR (2)     NULL,
    [PROPERTYCITY]              VARCHAR (50)    NULL,
    [PROPERTYZIPCODE]           VARCHAR (10)    NULL,
    [OUTBUILDINGCOUNT]          NUMERIC (15, 2) NULL,
    [LANDEXCESSSF]              NUMERIC (20, 6) NULL,
    [APPROACHTYPE]              VARCHAR (15)    NULL,
    [FLOORCOVER]                VARCHAR (30)    NULL,
    [CONDOIMPPERCENT]           NUMERIC (15, 6) NULL,
    [FINALSF]                   NUMERIC (20, 6) NULL,
    [FINALSFVALUEPER]           NUMERIC (15, 2) NULL,
    [ZONEDAREAVALUEPER]         NUMERIC (15, 2) NULL,
    [GROUPINVENTORYFLAG]        NUMERIC (1)     NULL,
    [GRANTORNAME1]              VARCHAR (80)    NULL,
    [GRANTORNAME2]              VARCHAR (60)    NULL,
    [GRANTORADDRESS1]           VARCHAR (50)    NULL,
    [GRANTORADDRESS2]           VARCHAR (50)    NULL,
    [GRANTORCITY]               VARCHAR (50)    NULL,
    [GRANTORSTATECODE]          VARCHAR (2)     NULL,
    [GRANTORZIPCODE]            VARCHAR (10)    NULL,
    [SUBDIVISIONNAME]           VARCHAR (255)   NULL,
    [LOT]                       VARCHAR (20)    NULL,
    [BLOCK]                     VARCHAR (20)    NULL,
    [FILINGNO]                  VARCHAR (30)    NULL,
    [TRACT]                     VARCHAR (20)    NULL,
    [LEGALDESCRIPTION]          VARCHAR (4000)  NULL,
    [GRANTEENAME1]              VARCHAR (80)    NULL,
    [GRANTEENAME2]              VARCHAR (60)    NULL,
    [GRANTEEADDRESS1]           VARCHAR (50)    NULL,
    [GRANTEEADDRESS2]           VARCHAR (50)    NULL,
    [GRANTEECITY]               VARCHAR (50)    NULL,
    [GRANTEESTATECODE]          VARCHAR (2)     NULL,
    [GRANTEEZIPCODE]            VARCHAR (10)    NULL,
    [SALEINVENTORYON0]          NUMERIC (20, 6) NULL,
    [SALEINVENTORYON1]          NUMERIC (20, 6) NULL,
    [SALEINVENTORYON2]          NUMERIC (20, 6) NULL,
    [OCCCODEDESCRIPTION1]       VARCHAR (50)    NULL,
    [OCCCODEDESCRIPTION2]       VARCHAR (50)    NULL,
    [OCCCODEDESCRIPTION3]       VARCHAR (50)    NULL,
    [SALEINVENTORYOD0]          VARCHAR (22)    NULL,
    [SALEINVENTORYOD1]          VARCHAR (22)    NULL,
    [SALEINVENTORYOM0]          VARCHAR (50)    NULL,
    [SALEINVENTORYOM1]          VARCHAR (50)    NULL,
    [SALEINVENTORYOT0]          VARCHAR (50)    NULL,
    [SALEINVENTORYOT1]          VARCHAR (50)    NULL,
    [LANDNETFF]                 NUMERIC (20, 6) NULL,
    [JURISDICTIONID]            NUMERIC (15)    NULL,
    [OUTOFAREASALEJURISDICTION] VARCHAR (30)    NULL,
    [LASTUPDATED]               VARCHAR (22)    NULL,
    [GRANTEEPROVINCE]           VARCHAR (50)    NULL,
    [GRANTEECOUNTRY]            VARCHAR (100)   NULL,
    [GRANTEEPOSTALCODE]         VARCHAR (20)    NULL,
    [OCCCOMPLETEDPCT]           NUMERIC (15, 4) NULL,
    [PRIMARYUSECODE]            VARCHAR (10)    NULL,
    [GRANTORPROVINCE]           VARCHAR (50)    NULL,
    [GRANTORCOUNTRY]            VARCHAR (100)   NULL,
    [GRANTORPOSTALCODE]         VARCHAR (20)    NULL,
    [LANDNETUNITCOUNT]          NUMERIC (20, 6) NULL,
    [TOTALFINISHEDSF]           NUMERIC (15, 2) NULL,
    [TOTALUNFINISHEDSF]         NUMERIC (15, 2) NULL,
    [BLTASCODE]                 NUMERIC (15)    NULL,
    [SALERATIO]                 NUMERIC (7, 4)  NULL
);


GO
CREATE CLUSTERED INDEX [IX_s_tbnsaleinventory_ClusteredIndex-receptionno]
    ON [asr_staging].[s_tbnsaleinventory]([RECEPTIONNO] ASC);

