CREATE TABLE [asr_staging].[s_tblappeal] (
    [VERSTART]                   NUMERIC (11)    NULL,
    [VEREND]                     NUMERIC (11)    NULL,
    [TAXYEAR]                    NUMERIC (4)     NULL,
    [APPEALNO]                   NUMERIC (15)    NULL,
    [APPEALTYPE]                 VARCHAR (30)    NULL,
    [APPEALMETHOD]               VARCHAR (30)    NULL,
    [ASSIGNEDTO]                 VARCHAR (20)    NULL,
    [INITIATEDBY]                VARCHAR (30)    NULL,
    [AGENTCODE]                  NUMERIC (15)    NULL,
    [AGENT_NAME]                 VARCHAR (150)   NULL,
    [AGENT_EMAILADDRESS]         VARCHAR (100)   NULL,
    [AGENT_PHONE]                VARCHAR (25)    NULL,
    [AGENT_ADDRESS]              VARCHAR (250)   NULL,
    [FILER_EMAIL]                VARCHAR (100)   NULL,
    [FILER_PHONE]                VARCHAR (18)    NULL,
    [FILER]                      VARCHAR (250)   NULL,
    [FILER_ADDRESS]              VARCHAR (50)    NULL,
    [FILER_CITY]                 VARCHAR (50)    NULL,
    [FILER_STATECODE]            VARCHAR (2)     NULL,
    [FILER_ZIPCODE]              VARCHAR (10)    NULL,
    [MAILTO]                     VARCHAR (30)    NULL,
    [DECISIONBY]                 VARCHAR (30)    NULL,
    [CASENO]                     VARCHAR (30)    NULL,
    [REREVIEWSTATUS]             VARCHAR (30)    NULL,
    [REREVIEWINITIALS]           VARCHAR (30)    NULL,
    [REREVIEWDECISION]           VARCHAR (30)    NULL,
    [APPEALREASON]               VARCHAR (30)    NULL,
    [APPEALBASIS]                VARCHAR (30)    NULL,
    [APPEALRECOMMENDATION]       VARCHAR (30)    NULL,
    [APPEALADJUSTDENYREASONID]   NUMERIC (15)    NULL,
    [APPEALENDVALUE]             NUMERIC (15, 2) NULL,
    [DATEOFAPPEAL]               VARCHAR (22)    NULL,
    [DATERECEIVED]               VARCHAR (22)    NULL,
    [TAXPAYERMEETINGREQUESTFLAG] NUMERIC (1)     NULL,
    [TAXPAYERMEETINGDATE]        VARCHAR (22)    NULL,
    [TAXPAYERMEETINGTIME]        VARCHAR (100)   NULL,
    [BEGINNINGAPPEALVALUE]       NUMERIC (15, 2) NULL,
    [APPEALON1]                  NUMERIC (20, 6) NULL,
    [APPEALON2]                  NUMERIC (20, 6) NULL,
    [APPEALOD0]                  VARCHAR (22)    NULL,
    [APPEALOD1]                  VARCHAR (22)    NULL,
    [APPEALOM0]                  VARCHAR (50)    NULL,
    [APPEALOM1]                  VARCHAR (50)    NULL,
    [APPEALON0]                  NUMERIC (20, 6) NULL,
    [APPEALOT0]                  VARCHAR (50)    NULL,
    [APPEALOT1]                  VARCHAR (50)    NULL,
    [APPRAISALTYPE]              VARCHAR (30)    NULL,
    [PRIMARYACCOUNT]             VARCHAR (30)    NULL,
    [JURISDICTIONID]             NUMERIC (15)    NULL,
    [SCHEDULEDATEAS]             VARCHAR (22)    NULL,
    [SCHEDULESTARTTIME]          VARCHAR (50)    NULL,
    [SCHEDULEENDTIME]            VARCHAR (50)    NULL,
    [SCHEDULECOMMENT]            VARCHAR (500)   NULL,
    [SCHEDULEBOARDFILENO]        VARCHAR (30)    NULL,
    [SCHEDULEAPPRAISERINITIALS]  VARCHAR (30)    NULL,
    [APPOINTMENTCOLOR]           VARCHAR (50)    NULL,
    [WRITEDATE]                  VARCHAR (22)    NULL,
    [APPEALSTATUSID]             NUMERIC (15)    NULL,
    [APPEALREASONDESCRIPTION]    VARCHAR (1000)  NULL,
    [BOARDNO]                    VARCHAR (10)    NULL,
    [APPEALDECISION]             VARCHAR (30)    NULL,
    [SEQID]                      NUMERIC (15)    NULL
);

