CREATE TABLE [asr_staging].[s_TBLMLSHISTORY] (
    [TBLMLSHISTORYID]    INT          IDENTITY (1, 1) NOT NULL,
    [MLSMONTH]           INT          NOT NULL,
    [MLSYEAR]            INT          NOT NULL,
    [MLSTYPE]            VARCHAR (25) NOT NULL,
    [MONTHSOFINVENTORY]  INT          NULL,
    [ACTIVELISTINGCOUNT] INT          NULL,
    [AVGDOM]             INT          NULL,
    [MEDIANDOM]          INT          NULL,
    [SALESCOUNT]         INT          NULL,
    [AVGLISTPRICE]       NUMERIC (15) NULL,
    [MEDIANLISTPRICE]    NUMERIC (15) NULL,
    [AVGCLOSEPRICE]      NUMERIC (15) NULL,
    [MEDIANCLOSEPRICE]   NUMERIC (15) NULL,
    CONSTRAINT [PK_Reporting_TBLMLSHISTORY] PRIMARY KEY CLUSTERED ([TBLMLSHISTORYID] ASC)
);



