CREATE TABLE [asr_staging].[s_tlkpimpsocctype] (
    [OCCCODE]            NUMERIC (15) NULL,
    [OCCCODEDESCRIPTION] VARCHAR (50) NULL,
    [ABSTRACTCODE]       VARCHAR (10) NULL,
    [SORTORDER]          NUMERIC (9)  NULL,
    [ACTIVEFLAG]         NUMERIC (1)  NULL,
    [JURISDICTIONID]     NUMERIC (15) NULL,
    [LASTUPDATED]        VARCHAR (22) NULL
);

