CREATE TABLE [asr_staging].[s_tlkpabstractcodetype] (
    [ABSTRACTCODE]   VARCHAR (10) NULL,
    [ABSTRACTTYPE]   VARCHAR (1)  NULL,
    [ACTIVEFLAG]     NUMERIC (1)  NULL,
    [JURISDICTIONID] NUMERIC (15) NULL,
    [LASTUPDATED]    VARCHAR (22) NULL,
    [SORTORDER]      NUMERIC (9)  NULL
);

