CREATE TABLE [asr_staging].[s_tlkpimpshvactype] (
    [HVACTYPE]       VARCHAR (30) NULL,
    [PROPERTYTYPE]   VARCHAR (15) NULL,
    [SORTORDER]      NUMERIC (9)  NULL,
    [ACTIVEFLAG]     NUMERIC (1)  NULL,
    [JURISDICTIONID] NUMERIC (15) NULL,
    [LASTUPDATED]    VARCHAR (22) NULL
);

