CREATE TABLE [asr_staging].[s_tlkpvaluegroup] (
    [VALUEGROUPCODE]         NUMERIC (15)  NOT NULL,
    [VALUEGROUPDESCRIPTION]  VARCHAR (50)  NULL,
    [VALUECODE]              VARCHAR (30)  NULL,
    [SORTORDER]              NUMERIC (9)   NOT NULL,
    [ACTIVEFLAG]             NUMERIC (1)   NOT NULL,
    [JURISDICTIONID]         NUMERIC (15)  NOT NULL,
    [LASTUPDATED]            VARCHAR (22)  NULL,
    [SUPPLEMENTALBILLTYPEID] NUMERIC (15)  NULL,
    [ETL_RUN_TIME]           DATETIME2 (7) DEFAULT (getdate()) NULL
);

