CREATE TABLE [asr_staging].[s_tlkpsaleexclude] (
    [EXCLUDECODE]        VARCHAR (10) NULL,
    [EXCLUDEDESCRIPTION] VARCHAR (40) NULL,
    [SORTORDER]          NUMERIC (9)  NULL,
    [ACTIVEFLAG]         NUMERIC (1)  NULL,
    [JURISDICTIONID]     NUMERIC (15) NULL,
    [LASTUPDATED]        VARCHAR (22) NULL
);

