








CREATE VIEW [asr_open_data_query].[v_account_fact]

/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Mod Date:      5/10/2017
Developer:     David Guillen
Comments:      Initial creation
               Provide a view to access account_fact records for consumption by 
			   assessor open data in socrata

*************************************************************************************/
AS
SELECT
  INGRP1.ACCOUNT_NO ACCOUNT_NO,
  INGRP1.STATE_PARCEL_NO STATE_PARCEL_NO,
  CAST(INGRP1.ACCOUNT_SUBTYPE_CODE AS VARCHAR) ACCOUNT_SUBTYPE_CODE,
  INGRP1.TAX_DISTRICT_NO TAX_DISTRICT_NO,
  CAST(INGRP1.LAND_ECONOMIC_AREA_CODE AS VARCHAR) LAND_ECONOMIC_AREA_CODE,
  INGRP1.ACCOUNT_TYPE ACCOUNT_TYPE,
  CAST(INGRP1.SUB_FILING_RECORDING_NO AS VARCHAR) SUB_FILING_RECORDING_NO,
  INGRP1.OWNER_NAME OWNER_NAME,
  INGRP1.ADDRESS_LINE_1 ADDRESS_LINE_1,
  INGRP1.ADDRESS_LINE_2 ADDRESS_LINE_2,
  CAST(INGRP1.ADDRESS_LINE_3 AS VARCHAR) ADDRESS_LINE_3,
  INGRP1.CITY_NAME_1 CITY_NAME_1,
  INGRP1.STATE STATE,
  INGRP1.ZIP_CODE ZIP_CODE,
  INGRP1.COUNTRY COUNTRY,
  INGRP1.UNIT_NO UNIT_NO,
  INGRP1.UNIT_DESIGNATOR UNIT_DESIGNATOR,
  SUBSTRING(INGRP1.ADDRESS_NUMBER,1,10) ADDRESS_NUMBER,
  INGRP1.ADDRESS_NUMBER_SUFFIX ADDRESS_NUMBER_SUFFIX,
  INGRP1.PRE_DIRECTION_CODE PRE_DIRECTION_CODE,
  INGRP1.STREET_NAME STREET_NAME,
  INGRP1.STREET_TYPE_CODE STREET_TYPE_CODE,
  INGRP1.POST_DIRECTION_CODE POST_DIRECTION_CODE,
  INGRP1.CITY_NAME CITY_NAME,
  INGRP1.LOCATION_ZIP_CODE LOCATION_ZIP_CODE,
  INGRP2.TOTAL_ACTUAL_VALUE TOTAL_ACTUAL_VALUE,
  INGRP2.TOTAL_ASSESSED_VALUE TOTAL_ASSESSED_VALUE,
  INGRP2.TOTAL_NET_ACRES TOTAL_NET_ACRES,
  INGRP1.LEGAL_DESCR LEGAL_DESCR,
  INGRP1.ACCOUNT_STATUS ACCOUNT_STATUS,
  INGRP1.FEDERAL_ID_NO FEDERAL_ID_NO,
  'CO' as LOCATION_STATE_CODE

FROM
   ( SELECT
  INGRP1.ACCOUNT_NO ACCOUNT_NO,
  INGRP1.ACCOUNT_STATUS ACCOUNT_STATUS,
  INGRP1.ACCOUNT_TYPE ACCOUNT_TYPE,
  INGRP1.ACCOUNT_SUBTYPE_CODE ACCOUNT_SUBTYPE_CODE,
  INGRP1.STATE_PARCEL_NO STATE_PARCEL_NO,
  INGRP1.TAX_DISTRICT_NO TAX_DISTRICT_NO,
  INGRP1.SUB_FILING_RECORDING_NO SUB_FILING_RECORDING_NO,
  INGRP1.LAND_ECONOMIC_AREA_CODE LAND_ECONOMIC_AREA_CODE,
  INGRP1.LEGAL_DESCRIPTION LEGAL_DESCR,
  INGRP1.UNIT_NO UNIT_NO,
  INGRP1.UNIT_DESIGNATOR UNIT_DESIGNATOR,
  INGRP1.ADDRESS_NUMBER ADDRESS_NUMBER,
  INGRP1.ADDRESS_NUMBER_SUFFIX ADDRESS_NUMBER_SUFFIX,
  INGRP1.PRE_DIRECTION_CODE PRE_DIRECTION_CODE,
  INGRP1.STREET_NAME STREET_NAME,
  INGRP1.STREET_TYPE_CODE STREET_TYPE_CODE,
  INGRP1.POST_DIRECTION_CODE POST_DIRECTION_CODE,
  INGRP1.CITY_NAME CITY_NAME,
  INGRP1.LOCATION_ZIP_CODE LOCATION_ZIP_CODE,
  INGRP2.OWNER_NAME OWNER_NAME,
  INGRP2.FEDERAL_ID_NO FEDERAL_ID_NO,
  INGRP2.ADDRESS_LINE_1 ADDRESS_LINE_1,
  INGRP2.ADDRESS_LINE_2 ADDRESS_LINE_2,
  INGRP2.ADDRESS_LINE_3 ADDRESS_LINE_3,
  INGRP2.CITY_NAME CITY_NAME_1,
  INGRP2.STATE STATE,
  INGRP2.ZIP_CODE ZIP_CODE,
  INGRP2.COUNTRY COUNTRY,
  INGRP1.REDUCED_MILL_LEVY REDUCED_MILL_LEVY,
  INGRP1.REDUCED_TAX_RATE REDUCED_TAX_RATE
FROM
   ( SELECT
  INGRP1.ACCOUNT_NO ACCOUNT_NO,
  INGRP1.ACCOUNT_STATUS ACCOUNT_STATUS,
  INGRP1.ACCOUNT_TYPE ACCOUNT_TYPE,
  INGRP1.ACCOUNT_SUBTYPE_CODE ACCOUNT_SUBTYPE_CODE,
  INGRP1.STATE_PARCEL_NO STATE_PARCEL_NO,
  INGRP1.TAX_DISTRICT_NO TAX_DISTRICT_NO,
  INGRP1.SUB_FILING_RECORDING_NO SUB_FILING_RECORDING_NO,
  INGRP1.LAND_ECONOMIC_AREA_CODE LAND_ECONOMIC_AREA_CODE,
  INGRP1.LEGAL_DESCRIPTION LEGAL_DESCRIPTION,
  INGRP2.UNIT_NO UNIT_NO,
  INGRP2.UNIT_DESIGNATOR UNIT_DESIGNATOR,
  INGRP2.ADDRESS_NUMBER ADDRESS_NUMBER,
  INGRP2.ADDRESS_NUMBER_SUFFIX ADDRESS_NUMBER_SUFFIX,
  INGRP2.PRE_DIRECTION_CODE PRE_DIRECTION_CODE,
  INGRP2.STREET_NAME STREET_NAME,
  INGRP2.STREET_TYPE_CODE STREET_TYPE_CODE,
  INGRP2.POST_DIRECTION_CODE POST_DIRECTION_CODE,
  INGRP2.CITY_NAME CITY_NAME,
  INGRP2.LOCATION_ZIP_CODE LOCATION_ZIP_CODE,
  INGRP1.REDUCED_MILL_LEVY REDUCED_MILL_LEVY,
  INGRP1.REDUCED_TAX_RATE REDUCED_TAX_RATE
FROM
   ( SELECT
  INGRP1.ACCOUNT_NO ACCOUNT_NO,
  INGRP1.ACCOUNT_STATUS ACCOUNT_STATUS,
  INGRP1.ACCOUNT_TYPE ACCOUNT_TYPE,
  INGRP1.ACCOUNT_SUBTYPE_CODE ACCOUNT_SUBTYPE_CODE,
  INGRP1.STATE_PARCEL_NO STATE_PARCEL_NO,
  INGRP1.TAX_DISTRICT_NO TAX_DISTRICT_NO,
  INGRP1.SUB_FILING_RECORDING_NO SUB_FILING_RECORDING_NO,
  NULL LAND_ECONOMIC_AREA_CODE,
  --asr_datastore.REAL_ACCOUNT.LAND_ECONOMIC_AREA_CODE LAND_ECONOMIC_AREA_CODE,
  --NULL LEGAL_DESCRIPTION,
  INGRP1.LEGAL_DESCRIPTION LEGAL_DESCRIPTION,
  INGRP1.REDUCED_MILL_LEVY REDUCED_MILL_LEVY,
  INGRP1.REDUCED_TAX_RATE REDUCED_TAX_RATE
FROM
   ( SELECT
ACCOUNT.ACCOUNT_NO ACCOUNT_NO,
ACCOUNT.ACCOUNT_STATUS ACCOUNT_STATUS,
ACCOUNT.ACCOUNT_TYPE ACCOUNT_TYPE,
ACCOUNT.APPRAISAL_TYPE ACCOUNT_SUBTYPE_CODE,
  --asr_datastore.ACCOUNT.ACCOUNT_SUBTYPE_CODE ACCOUNT_SUBTYPE_CODE,
  ACCOUNT.STATE_PARCEL_NO STATE_PARCEL_NO,
  ACCOUNT.TAX_DISTRICT_NO TAX_DISTRICT_NO,
  ACCOUNT.SUB_FILING_RECORDING_NO,
  --ACCOUNT_PLATTED_LOT.SUB_FILING_RECORDING_NO SUB_FILING_RECORDING_NO,
  NULL REDUCED_MILL_LEVY,
  --ACCOUNT.REDUCED_MILL_LEVY REDUCED_MILL_LEVY,
  NULL REDUCED_TAX_RATE,
  --ACCOUNT.REDUCED_TAX_RATE REDUCED_TAX_RATE
  ACCOUNT.LEGAL_DESCRIPTION
FROM
    asr_datastore.ACCOUNT  ACCOUNT   
 LEFT OUTER JOIN   asr_datastore.ACCOUNT_PLATTED_LOT  ACCOUNT_PLATTED_LOT ON ( ( ACCOUNT.STATE_PARCEL_NO = ACCOUNT_PLATTED_LOT.ACCOUNT_NO ) ) ) INGRP1   
 LEFT OUTER JOIN   asr_datastore.REAL_ACCOUNT  REAL_ACCOUNT ON ( ( INGRP1.ACCOUNT_NO = REAL_ACCOUNT.ACCOUNT_NO ) ) ) INGRP1   
 LEFT OUTER JOIN  
 ( SELECT
  ACCOUNT_PROPERTY_ADDRESS.UNIT_NO UNIT_NO,
  ACCOUNT_PROPERTY_ADDRESS.UNIT_DESIGNATOR UNIT_DESIGNATOR,
  ACCOUNT_PROPERTY_ADDRESS.ADDRESS_NUMBER ADDRESS_NUMBER,
  ACCOUNT_PROPERTY_ADDRESS.ADDRESS_NUMBER_SUFFIX ADDRESS_NUMBER_SUFFIX,
  ACCOUNT_PROPERTY_ADDRESS.PRE_DIRECTION_CODE PRE_DIRECTION_CODE,
  ACCOUNT_PROPERTY_ADDRESS.STREET_NAME STREET_NAME,
  ACCOUNT_PROPERTY_ADDRESS.STREET_TYPE_CODE STREET_TYPE_CODE,
  ACCOUNT_PROPERTY_ADDRESS.POST_DIRECTION_CODE POST_DIRECTION_CODE,
  ACCOUNT_PROPERTY_ADDRESS.CITY_NAME CITY_NAME,
  ACCOUNT_PROPERTY_ADDRESS.LOCATION_ZIP_CODE LOCATION_ZIP_CODE,
  ACCOUNT_PROPERTY_ADDRESS.ACCOUNT_NO ACCOUNT_NO
FROM
    asr_datastore.ACCOUNT_PROPERTY_ADDRESS  ACCOUNT_PROPERTY_ADDRESS   
 --JOIN   ACCOUNT_PROPERTY_ADDRESS  ACCOUNT_PROPERTY_ADDRESS ON ( ( ACCOUNT_PROPERTY_ADDRESS.SITUS_ADDRESS_EID = ACCOUNT_SITUS_ADDRESS.SITUS_ADDRESS_EID ) )
  WHERE 
  ( ACCOUNT_PROPERTY_ADDRESS.PRIMARY_ADDRESS_FLAG = 1  )  ) INGRP2 ON ( ( INGRP1.ACCOUNT_NO = INGRP2.ACCOUNT_NO ) ) ) INGRP1   
 LEFT OUTER JOIN  
 ( SELECT
  ACCOUNT_OWNER_ADDRESS.ACCOUNT_NO ACCOUNT_NO,
  ACCOUNT_OWNER_ADDRESS.OWNER_NAME OWNER_NAME,
  ACCOUNT_OWNER_ADDRESS.FEDERAL_ID_NO FEDERAL_ID_NO,
  ACCOUNT_OWNER_ADDRESS.ADDRESS_LINE_1 ADDRESS_LINE_1,
  ACCOUNT_OWNER_ADDRESS.ADDRESS_LINE_2 ADDRESS_LINE_2,
  NULL ADDRESS_LINE_3,
  ACCOUNT_OWNER_ADDRESS.CITY_NAME CITY_NAME,
  ACCOUNT_OWNER_ADDRESS.STATE STATE,
  ACCOUNT_OWNER_ADDRESS.ZIP_CODE ZIP_CODE,
  ACCOUNT_OWNER_ADDRESS.COUNTRY COUNTRY
FROM
    asr_datastore.ACCOUNT_OWNER_ADDRESS  ACCOUNT_OWNER_ADDRESS
  WHERE 
  ( ACCOUNT_OWNER_ADDRESS.PRIMARY_OWNER_FLAG = 1 )  ) INGRP2 ON ( ( INGRP1.ACCOUNT_NO = INGRP2.ACCOUNT_NO ) ) ) INGRP1   
 LEFT OUTER JOIN  ( SELECT
  AGGREGATOR.TOTAL_ACTUAL_VALUE TOTAL_ACTUAL_VALUE,
  AGGREGATOR.TOTAL_ASSESSED_VALUE TOTAL_ASSESSED_VALUE,
  AGGREGATOR.TOTAL_NET_ACRES TOTAL_NET_ACRES,
  AGGREGATOR.ACCOUNT_NO ACCOUNT_NO
FROM
  (SELECT
  SUM(ACCOUNT_VALUATION.ACTUAL_VALUE) TOTAL_ACTUAL_VALUE,
  SUM(ACCOUNT_VALUATION.ASSESSED_VALUE) TOTAL_ASSESSED_VALUE,
  SUM(ACCOUNT_VALUATION.NET_ACRES) TOTAL_NET_ACRES,
  ACCOUNT_VALUATION.ACCOUNT_NO ACCOUNT_NO
FROM
  asr_datastore.ACCOUNT_VALUATION  ACCOUNT_VALUATION
GROUP BY
ACCOUNT_VALUATION.ACCOUNT_NO) AGGREGATOR  ) INGRP2 ON ( ( INGRP1.ACCOUNT_NO = INGRP2.ACCOUNT_NO ) );






















