//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.account_neighborhood = new HashSet<account_neighborhood>();
            this.account_owner_address = new HashSet<account_owner_address>();
            this.account_property_address = new HashSet<account_property_address>();
            this.improvement_built_as = new HashSet<improvement_built_as>();
            this.improvement_detail = new HashSet<improvement_detail>();
            this.improvements = new HashSet<improvement>();
            this.improvement_occupancy = new HashSet<improvement_occupancy>();
            this.land_abstract = new HashSet<land_abstract>();
            this.land_attribute = new HashSet<land_attribute>();
            this.sale_account = new HashSet<sale_account>();
            this.sale_inventory = new HashSet<sale_inventory>();
            this.sale_inventory_detail = new HashSet<sale_inventory_detail>();
            this.values = new HashSet<value>();
            this.account_valuation = new HashSet<account_valuation>();
            this.value_from_tsgvacctabstvalue = new HashSet<value_from_tsgvacctabstvalue>();
            this.realnov = new HashSet<realnov>();
            this.appeal_account = new HashSet<appeal_account>();
            this.account_notification = new HashSet<account_notification>();
        }
    
        public string account_no { get; set; }
        public string state_parcel_no { get; set; }
        public string tax_district_no { get; set; }
        public string sub_filing_recording_no { get; set; }
        public string account_type { get; set; }
        public string appraisal_type { get; set; }
        public string account_status { get; set; }
        public string account_status_description { get; set; }
        public string legal_description { get; set; }
        public Nullable<decimal> longitude_x { get; set; }
        public Nullable<decimal> latitude_y { get; set; }
        public string location { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<decimal> elevation_z { get; set; }
        public Nullable<int> bldg_permit_auth_id { get; set; }
        public string qtr { get; set; }
        public string section { get; set; }
        public string township { get; set; }
        public string range { get; set; }
    
        public virtual sub_filing sub_filing { get; set; }
        public virtual tax_district tax_district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_neighborhood> account_neighborhood { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_owner_address> account_owner_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_property_address> account_property_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_built_as> improvement_built_as { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_detail> improvement_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement> improvements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_occupancy> improvement_occupancy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<land_abstract> land_abstract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<land_attribute> land_attribute { get; set; }
        public virtual real_account real_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_account> sale_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_inventory> sale_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_inventory_detail> sale_inventory_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<value> values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_valuation> account_valuation { get; set; }
        public virtual azure_building_permit_authority azure_building_permit_authority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<value_from_tsgvacctabstvalue> value_from_tsgvacctabstvalue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<realnov> realnov { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appeal_account> appeal_account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_notification> account_notification { get; set; }
    }
}
