//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_property_address
    {
        public string account_no { get; set; }
        public int order_no { get; set; }
        public Nullable<bool> primary_address_flag { get; set; }
        public string building_no { get; set; }
        public string unit_no { get; set; }
        public string unit_designator { get; set; }
        public string address_number { get; set; }
        public string address_number_suffix { get; set; }
        public string pre_direction_code { get; set; }
        public string street_name { get; set; }
        public string street_type_code { get; set; }
        public string post_direction_code { get; set; }
        public string city_name { get; set; }
        public string location_zip_code { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public string concatenated_property_address { get; set; }
    
        public virtual account account { get; set; }
    }
}
