//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_valuation
    {
        public string account_no { get; set; }
        public string valuation_class_code { get; set; }
        public Nullable<decimal> actual_value { get; set; }
        public Nullable<decimal> assessed_value { get; set; }
        public Nullable<decimal> net_acres { get; set; }
        public Nullable<bool> new_growth_flag { get; set; }
        public string valuation_class_code_description { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public string account_type { get; set; }
    
        public virtual account account { get; set; }
    }
}
