//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_fact
    {
        public string ACCOUNT_NO { get; set; }
        public string STATE_PARCEL_NO { get; set; }
        public string ACCOUNT_SUBTYPE_CODE { get; set; }
        public string TAX_DISTRICT_NO { get; set; }
        public string LAND_ECONOMIC_AREA_CODE { get; set; }
        public string ACCOUNT_TYPE_CODE { get; set; }
        public string SUB_FILING_RECORDING_NO { get; set; }
        public string OWNER_NAME { get; set; }
        public string MAILING_ADDRESS_LINE_1 { get; set; }
        public string MAILING_ADDRESS_LINE_2 { get; set; }
        public string MAILING_ADDRESS_LINE_3 { get; set; }
        public string MAILING_CITY_NAME { get; set; }
        public string MAILING_STATE { get; set; }
        public string MAILING_ZIP_CODE { get; set; }
        public string MAILING_COUNTRY { get; set; }
        public string UNIT_NO { get; set; }
        public string UNIT_DESIGNATOR { get; set; }
        public string ADDRESS_NUMBER { get; set; }
        public string ADDRESS_NUMBER_SUFFIX { get; set; }
        public string PRE_DIRECTION_CODE { get; set; }
        public string STREET_NAME { get; set; }
        public string STREET_TYPE_CODE { get; set; }
        public string POST_DIRECTION_CODE { get; set; }
        public string CITY_NAME { get; set; }
        public string LOCATION_STATE_CODE { get; set; }
        public string LOCATION_ZIP_CODE { get; set; }
        public Nullable<decimal> TOTAL_ACTUAL_VALUE { get; set; }
        public Nullable<decimal> TOTAL_ASSESSED_VALUE { get; set; }
        public Nullable<decimal> TOTAL_NET_ACRES { get; set; }
        public string ACCOUNT_STATUS_CODE { get; set; }
        public string FEDERAL_ID_NO { get; set; }
        public Nullable<System.DateTime> ROW_START_DTM { get; set; }
        public Nullable<System.DateTime> ROW_END_DTM { get; set; }
        public string ROW_CURRENT_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DTM { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DTM { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public string LEGAL_DESCR { get; set; }
        public Nullable<decimal> REDUCED_MILL_LEVY { get; set; }
        public Nullable<decimal> REDUCED_TAX_RATE { get; set; }
    }
}
