//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_owner_address
    {
        public string account_no { get; set; }
        public string person_code { get; set; }
        public bool primary_owner_flag { get; set; }
        public string owner_name { get; set; }
        public Nullable<decimal> ownership_percent { get; set; }
        public string federal_id_no { get; set; }
        public string address_line_1 { get; set; }
        public string address_line_2 { get; set; }
        public string city_name { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<bool> private_flag { get; set; }
        public string owner_name_1 { get; set; }
        public string owner_name_2 { get; set; }
    
        public virtual account account { get; set; }
    }
}
