//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class appeal_account
    {
        public Nullable<decimal> TAX_YEAR { get; set; }
        public Nullable<decimal> APPEAL_NO { get; set; }
        public string ACCOUNT_NO { get; set; }
        public Nullable<decimal> APPEAL_ADJUST_DENY_REASON_ID { get; set; }
        public string APPEAL_COMMENT { get; set; }
        public Nullable<decimal> APPEAL_ACCOUNT_END_VALUE { get; set; }
        public Nullable<decimal> APPEALACCTON0 { get; set; }
        public Nullable<decimal> APPEALACCTON1 { get; set; }
        public Nullable<decimal> APPEALACCTON2 { get; set; }
        public string APPEALACCTOD0 { get; set; }
        public string APPEALACCTOD1 { get; set; }
        public string APPEALACCTOM0 { get; set; }
        public string APPEALACCTOM1 { get; set; }
        public string APPEALACCTOT0 { get; set; }
        public string APPEALACCTOT1 { get; set; }
        public Nullable<decimal> JURISDICTION_ID { get; set; }
        public string WRITE_DATE { get; set; }
        public Nullable<decimal> BEGINNING_ACCOUNT_VALUE { get; set; }
        public string APPEAL_DECISION { get; set; }
        public string APPEAL_ACCT_REASON_DESC { get; set; }
        public Nullable<decimal> ADD_BOARD_APPEAL_END_VALUE { get; set; }
        public Nullable<decimal> SEQ_ID { get; set; }
        public System.DateTime CREATE_DATEIME { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public byte[] ROWHASH { get; set; }
        public string VALUE_GROUP_DESCRIPTION { get; set; }
    
        public virtual account account { get; set; }
    }
}
