//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class azure_important_dates
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Reappraisal { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Intervening { get; set; }
        public string Category { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public string Title { get; set; }
    }
}
