//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_processing_log
    {
        public int data_processing_log_id { get; set; }
        public string process_name { get; set; }
        public System.DateTime process_start_time { get; set; }
        public Nullable<System.DateTime> process_end_time { get; set; }
        public string process_status { get; set; }
    }
}
