//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class improvement_occupancy
    {
        public string account_no { get; set; }
        public decimal improvement_no { get; set; }
        public decimal occupancy_detail_id { get; set; }
        public string occupancy_code { get; set; }
        public string occupancy_code_description { get; set; }
        public decimal occupancy_percent { get; set; }
        public string abstract_code { get; set; }
        public string abstract_code_description { get; set; }
        public Nullable<decimal> abstract_value { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<bool> primary_flag { get; set; }
    
        public virtual account account { get; set; }
        public virtual improvement improvement { get; set; }
    }
}
