//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class improvement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public improvement()
        {
            this.improvement_built_as = new HashSet<improvement_built_as>();
            this.improvement_detail = new HashSet<improvement_detail>();
            this.improvement_occupancy = new HashSet<improvement_occupancy>();
        }
    
        public string account_no { get; set; }
        public decimal improvement_no { get; set; }
        public Nullable<decimal> completed_percent { get; set; }
        public string improvement_quality { get; set; }
        public Nullable<decimal> improvement_perimeter { get; set; }
        public Nullable<decimal> improvement_sf { get; set; }
        public Nullable<decimal> improvement_net_sf { get; set; }
        public string property_type { get; set; }
        public string condition_type { get; set; }
        public string approach_type { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<bool> primary_flag { get; set; }
        public string improvement_unit_type { get; set; }
    
        public virtual account account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_built_as> improvement_built_as { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_detail> improvement_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<improvement_occupancy> improvement_occupancy { get; set; }
    }
}
