//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class improvement_built_as
    {
        public string account_no { get; set; }
        public decimal improvement_no { get; set; }
        public decimal built_as_detail_id { get; set; }
        public string built_as_code { get; set; }
        public string built_as_code_description { get; set; }
        public Nullable<decimal> hvac_percent { get; set; }
        public string exterior_construction_type { get; set; }
        public string interior_finish_type { get; set; }
        public Nullable<decimal> no_of_story { get; set; }
        public Nullable<decimal> typical_story_height { get; set; }
        public string roof_construction_type { get; set; }
        public string roof_material_type { get; set; }
        public string floor_material_type { get; set; }
        public Nullable<decimal> room_count { get; set; }
        public Nullable<decimal> bedroom_count { get; set; }
        public Nullable<decimal> total_unit_count { get; set; }
        public string class_code { get; set; }
        public string class_code_description { get; set; }
        public string built_year { get; set; }
        public string remodeled_year { get; set; }
        public Nullable<decimal> remodeled_percent { get; set; }
        public Nullable<decimal> effective_age { get; set; }
        public Nullable<decimal> built_as_sf { get; set; }
        public Nullable<decimal> sprinkler_coverage_sf { get; set; }
        public Nullable<decimal> bathroom_count { get; set; }
        public string heat_type { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<bool> primary_flag { get; set; }
        public Nullable<decimal> built_as_length { get; set; }
        public Nullable<decimal> built_as_width { get; set; }
        public Nullable<decimal> built_as_height { get; set; }
        public string mobile_home_make { get; set; }
        public string mobile_home_model_type { get; set; }
        public string mobile_home_skirt { get; set; }
        public Nullable<decimal> mobile_home_skirt_linear_feet { get; set; }
        public string mobile_home_wall_type { get; set; }
    
        public virtual account account { get; set; }
        public virtual improvement improvement { get; set; }
    }
}
