//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class land_attribute
    {
        public string account_no { get; set; }
        public decimal detail_id { get; set; }
        public string attribute_type { get; set; }
        public string attribute_subtype { get; set; }
        public Nullable<decimal> attribute_adjustment { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
    
        public virtual account account { get; set; }
    }
}
