//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class land_abstract
    {
        public string account_no { get; set; }
        public string abstract_code { get; set; }
        public decimal land_abstract_detail_id { get; set; }
        public string land_type { get; set; }
        public Nullable<decimal> land_acres { get; set; }
        public Nullable<decimal> land_sf { get; set; }
        public Nullable<decimal> land_unit_count { get; set; }
        public decimal land_value_per { get; set; }
        public Nullable<decimal> land_value { get; set; }
        public bool land_override_flag { get; set; }
        public Nullable<decimal> land_override_total { get; set; }
        public Nullable<decimal> land_actual_value { get; set; }
        public string land_class { get; set; }
        public string land_subclass { get; set; }
        public string land_valued_by { get; set; }
        public string land_value_measure { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public string abstract_code_description { get; set; }
    
        public virtual account account { get; set; }
    }
}
