//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class pers_prop_acct
    {
        public string ACCOUNT_NO { get; set; }
        public string BUSINESS_NAME { get; set; }
        public Nullable<System.DateTime> ROW_START_DTM { get; set; }
        public Nullable<System.DateTime> ROW_END_DTM { get; set; }
        public string ROW_CURRENT_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DTM { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DTM { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public string LATE_FILING_FLAG { get; set; }
        public string NEW_CONSTRUCTION_FLAG { get; set; }
        public string NEW_CONSTRUCTION_CLASS_CODE { get; set; }
        public Nullable<decimal> NEW_CONSTRUCTION_VALUE { get; set; }
        public Nullable<System.DateTime> DECLARATION_SENT_DATE { get; set; }
        public Nullable<System.DateTime> DECLARATION_RETURNED_DATE { get; set; }
        public string VALUED_BY { get; set; }
        public string NO_DECLARATION_FLAG { get; set; }
        public string BEST_INFO_AVAILABLE_FLAG { get; set; }
        public string NO_CHANGE_FLAG { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string BUSINESS_TYPE_DESCRIPTION { get; set; }
        public string ASSOCIATED_ACCOUNT { get; set; }
    }
}
