//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class pers_prop_type
    {
        public string PERS_PROP_TYPE1 { get; set; }
        public string CODE_DESCR { get; set; }
        public Nullable<System.DateTime> ROW_START_DTM { get; set; }
        public Nullable<System.DateTime> ROW_END_DTM { get; set; }
        public string ROW_CURRENT_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DTM { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DTM { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
