//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class realnov
    {
        public string account_no { get; set; }
        public Nullable<decimal> TAXYEAR { get; set; }
        public string PARCELNO { get; set; }
        public string PROPADDRESS { get; set; }
        public string LEGALDESCRIPTION1 { get; set; }
        public string LEGALDESCRIPTION2 { get; set; }
        public string LEGALDESCRIPTION3 { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string PNAME1 { get; set; }
        public string PNAME2 { get; set; }
        public string OWNERADDRESS1 { get; set; }
        public string OWNERADDRESS2 { get; set; }
        public string OWNERCITY { get; set; }
        public string OWNERSTATE { get; set; }
        public string OWNERZIP { get; set; }
        public string PROPCLASS1 { get; set; }
        public string PRIORVALUE1 { get; set; }
        public string CURRENTVALUE1 { get; set; }
        public string INCREASEDECREASE1 { get; set; }
        public string PROPCLASS2 { get; set; }
        public string PRIORVALUE2 { get; set; }
        public string CURRENTVALUE2 { get; set; }
        public string INCREASEDECREASE2 { get; set; }
        public string PROPCLASS3 { get; set; }
        public string PRIORVALUE3 { get; set; }
        public string CURRENTVALUE3 { get; set; }
        public string INCREASEDECREASE3 { get; set; }
        public string PROPCLASS4 { get; set; }
        public string PRIORVALUE4 { get; set; }
        public string CURRENTVALUE4 { get; set; }
        public string INCREASEDECREASE4 { get; set; }
        public string PROPCLASS5 { get; set; }
        public string PRIORVALUE5 { get; set; }
        public string CURRENTVALUE5 { get; set; }
        public string INCREASEDECREASE5 { get; set; }
        public string PROPCLASS6 { get; set; }
        public string PRIORVALUE6 { get; set; }
        public string CURRENTVALUE6 { get; set; }
        public string INCREASEDECREASE6 { get; set; }
        public string TOTALPRIOR { get; set; }
        public string TOTALCURRENT { get; set; }
        public string TOTALINCREASEDECREASE { get; set; }
        public Nullable<int> VALUEYEAR { get; set; }
        public string PROPERTYTYPE { get; set; }
        public string PRIMARYBUILDING { get; set; }
        public string BUILDINGCOUNT { get; set; }
        public string SUBDIVISION { get; set; }
        public string NEIGHBORHOOD { get; set; }
        public Nullable<decimal> RESIDENTIALSF { get; set; }
        public string STYLE { get; set; }
        public string QUALITY { get; set; }
        public string YEARBUILT { get; set; }
        public string HEATTYPE { get; set; }
        public Nullable<decimal> BASEMENTSF { get; set; }
        public Nullable<decimal> FINISHEDBSMNTSF { get; set; }
        public string BASEMENTTYPE { get; set; }
        public Nullable<decimal> GARAGESF { get; set; }
        public Nullable<decimal> IMPSF { get; set; }
        public Nullable<decimal> COMMERCIALSF { get; set; }
        public Nullable<decimal> OUTBUILDINGSF { get; set; }
        public string LANDTYPE { get; set; }
        public string ACREAGE { get; set; }
        public string LEA { get; set; }
        public string LANDATTRIBUTES { get; set; }
        public string APPRDATEYEAR { get; set; }
        public string REAPPRYEAR { get; set; }
        public string BEGPERYEAR { get; set; }
        public string ENDPERYEAR { get; set; }
        public string CBOEDEADLINE { get; set; }
        public string PRINTFLAG { get; set; }
        public string BULKNOVFLAG { get; set; }
        public string PRIVATEFLAG { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public string ASSESSOR { get; set; }
        public string SREXEMPTIONDEADLINE { get; set; }
        public string VETEXEMPTIONDEADLINE { get; set; }
        public string NODMONTH { get; set; }
    
        public virtual account account { get; set; }
    }
}
