//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class real_account
    {
        public string account_no { get; set; }
        public bool vacant_flag { get; set; }
        public bool improvement_only_flag { get; set; }
        public bool tif_flag { get; set; }
        public string zoning_code { get; set; }
        public string zoning_code_description { get; set; }
        public bool platted_flag { get; set; }
        public string default_lea { get; set; }
        public string default_lea_description { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<decimal> total_improvement_interest_percent { get; set; }
        public Nullable<decimal> total_land_interest_percent { get; set; }
        public string no_of_buildings { get; set; }
    
        public virtual account account { get; set; }
    }
}
