//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sale()
        {
            this.sale_account = new HashSet<sale_account>();
        }
    
        public string recording_no { get; set; }
        public string grantor { get; set; }
        public string grantee { get; set; }
        public System.DateTime sale_date { get; set; }
        public string deed_code { get; set; }
        public string deed_code_description { get; set; }
        public decimal sale_price { get; set; }
        public bool valid1_flag { get; set; }
        public int confirmed_flag { get; set; }
        public string exclude_code_1 { get; set; }
        public bool improved_flag { get; set; }
        public bool non_sale_flag { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public string exclude_code_1_description { get; set; }
        public byte[] rowhash { get; set; }
        public Nullable<bool> valid2_flag { get; set; }
        public string book { get; set; }
        public string page { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_account> sale_account { get; set; }
    }
}
