//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_inventory
    {
        public string recording_no { get; set; }
        public string account_no { get; set; }
        public Nullable<System.DateTime> inventory_effective_date { get; set; }
        public Nullable<decimal> adjusted_sale_price { get; set; }
        public Nullable<decimal> time_adjusted_sale_price { get; set; }
        public string account_type { get; set; }
        public string land_economic_area { get; set; }
        public string land_economic_area_description { get; set; }
        public string property_type { get; set; }
        public string improvement_condition_type { get; set; }
        public string improvement_quality { get; set; }
        public string improvement_abstract_code { get; set; }
        public string improvement_abstract_code_description { get; set; }
        public string built_as_description { get; set; }
        public Nullable<decimal> built_as_year_built { get; set; }
        public Nullable<decimal> physical_age { get; set; }
        public Nullable<decimal> adjusted_year_built { get; set; }
        public Nullable<decimal> effective_age { get; set; }
        public string improvement_exterior { get; set; }
        public string class_code { get; set; }
        public string class_code_description { get; set; }
        public Nullable<decimal> improvement_count { get; set; }
        public Nullable<decimal> built_as_total_unit_count { get; set; }
        public Nullable<decimal> room_count { get; set; }
        public Nullable<decimal> bedroom_count { get; set; }
        public Nullable<decimal> bath_count { get; set; }
        public Nullable<decimal> total_improvement_square_footage { get; set; }
        public Nullable<decimal> residential_square_footage { get; set; }
        public Nullable<decimal> commercial_square_footage { get; set; }
        public Nullable<decimal> outbuilding_square_footage { get; set; }
        public Nullable<decimal> improvement_built_as_other { get; set; }
        public Nullable<decimal> land_net_square_footage { get; set; }
        public Nullable<decimal> multiple_use_flag { get; set; }
        public string land_type { get; set; }
        public string land_abstract_code { get; set; }
        public string land_abstract_code_description { get; set; }
        public string zoning_code { get; set; }
        public string zoning_code_description { get; set; }
        public Nullable<bool> platted_flag { get; set; }
        public Nullable<decimal> land_net_acre_count { get; set; }
        public string hvac_type { get; set; }
        public string improvement_unit_type { get; set; }
        public string improvement_interior { get; set; }
        public string roof_cover { get; set; }
        public string roof_type { get; set; }
        public string neighborhood_code_1 { get; set; }
        public string neighborhood_code_2 { get; set; }
        public string neighborhood_extension_1 { get; set; }
        public string neighborhood_extension_2 { get; set; }
        public Nullable<decimal> outbuilding_count { get; set; }
        public string floor_cover { get; set; }
        public string occupancy_code_description_1 { get; set; }
        public string occupancy_code_description_2 { get; set; }
        public Nullable<decimal> total_finished_square_footage { get; set; }
        public Nullable<decimal> total_unfinished_square_footage { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public byte[] rowhash { get; set; }
    
        public virtual account account { get; set; }
    }
}
