//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_authority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tax_authority()
        {
            this.tax_authority_fund = new HashSet<tax_authority_fund>();
            this.tax_district_authority = new HashSet<tax_district_authority>();
        }
    
        public string tax_authority_no { get; set; }
        public string tax_authority_name { get; set; }
        public string authority_type { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
        public string contact_person { get; set; }
        public string contact_address_line_1 { get; set; }
        public string contact_address_line_2 { get; set; }
        public string contact_city_name { get; set; }
        public string contact_state { get; set; }
        public string contact_zip_code { get; set; }
        public Nullable<int> active_flag { get; set; }
        public byte[] rowhash { get; set; }
        public string contact_phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tax_authority_fund> tax_authority_fund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tax_district_authority> tax_district_authority { get; set; }
    }
}
