//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_district
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tax_district()
        {
            this.accounts = new HashSet<account>();
            this.tax_district_authority = new HashSet<tax_district_authority>();
            this.values = new HashSet<value>();
            this.value_from_tsgvacctabstvalue = new HashSet<value_from_tsgvacctabstvalue>();
        }
    
        public string tax_district_no { get; set; }
        public string tax_district_name { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tax_district_authority> tax_district_authority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<value> values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<value_from_tsgvacctabstvalue> value_from_tsgvacctabstvalue { get; set; }
    }
}
