//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorJson
{
    using System;
    using System.Collections.Generic;
    
    public partial class value_from_tsgvacctabstvalue
    {
        public string account_no { get; set; }
        public decimal tax_year { get; set; }
        public string valuation_class_code { get; set; }
        public string tax_district_no { get; set; }
        public Nullable<decimal> raw_assessed_value { get; set; }
        public Nullable<decimal> raw_tax_dollars { get; set; }
        public Nullable<decimal> actual_value { get; set; }
        public Nullable<decimal> mill_levy { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string create_user_id { get; set; }
        public string account_type { get; set; }
        public Nullable<decimal> net_acres { get; set; }
        public string valuation_class_code_description { get; set; }
        public Nullable<decimal> assessment_rate { get; set; }
    
        public virtual account account { get; set; }
        public virtual tax_district tax_district { get; set; }
    }
}
