CREATE TABLE [asr_app].[nod_table_2] (
    [header]                         VARCHAR (2)    NOT NULL,
    [agent_flag]                     VARCHAR (1)    NOT NULL,
    [review_number]                  NUMERIC (15)   NOT NULL,
    [tax_year]                       NUMERIC (4)    NULL,
    [account_no]                     VARCHAR (30)   NOT NULL,
    [sub_lot]                        VARCHAR (6)    NULL,
    [sub_block]                      VARCHAR (6)    NULL,
    [desc_1]                         VARCHAR (50)   NULL,
    [desc_2]                         VARCHAR (50)   NULL,
    [desc_3]                         VARCHAR (50)   NULL,
    [desc_4]                         VARCHAR (50)   NULL,
    [a/d]                            VARCHAR (30)   NULL,
    [prior_value_1]                  VARCHAR (8000) NULL,
    [prior_value_2]                  VARCHAR (8000) NULL,
    [prior_value_3]                  VARCHAR (8000) NULL,
    [prior_value_4]                  VARCHAR (50)   NULL,
    [current_value_1]                VARCHAR (8000) NULL,
    [current_value_2]                VARCHAR (8000) NULL,
    [current_value_3]                VARCHAR (8000) NULL,
    [current_value_4]                VARCHAR (50)   NULL,
    [pet_value_total]                VARCHAR (8000) NULL,
    [prior_value_total]              VARCHAR (8000) NULL,
    [current_value_total]            VARCHAR (8000) NULL,
    [appeal_acct_adjust_deny_reason] VARCHAR (255)  NULL,
    [appeal_acct_reason_desc]        VARCHAR (1000) NULL,
    [sub_name]                       VARCHAR (255)  NULL,
    [filing_no]                      VARCHAR (30)   NULL,
    [create_datetime]                DATETIME2 (7)  NOT NULL,
    [create_user_id]                 VARCHAR (60)   NOT NULL
);

