CREATE TABLE [asr_app].[pers_prop_acct] (
    [ACCOUNT_NO]                  VARCHAR (30)    NOT NULL,
    [BUSINESS_NAME]               VARCHAR (100)   NULL,
    [BUSINESS_TYPE]               VARCHAR (10)    NOT NULL,
    [BUSINESS_TYPE_DESCRIPTION]   VARCHAR (50)    NOT NULL,
    [ROW_START_DTM]               DATETIME        CONSTRAINT [DF_pers_prop_acct_ROW_START_DATE] DEFAULT (getdate()) NULL,
    [ROW_END_DTM]                 DATETIME        NULL,
    [ROW_CURRENT_FLAG]            VARCHAR (1)     CONSTRAINT [DF_pers_prop_acct_ROW_CURRENT_FLAG] DEFAULT ('Y') NULL,
    [CREATE_DTM]                  DATETIME        CONSTRAINT [DF_pers_prop_acct_ROW_CREATE_DTM] DEFAULT (getdate()) NULL,
    [CREATE_USER_ID]              VARCHAR (30)    CONSTRAINT [DF_pers_prop_acct_CREATE_USER_ID] DEFAULT ('SSIS_ETL') NULL,
    [UPDATE_DTM]                  DATETIME        NULL,
    [UPDATE_USER_ID]              VARCHAR (30)    NULL,
    [LATE_FILING_FLAG]            VARCHAR (1)     NULL,
    [NEW_CONSTRUCTION_FLAG]       VARCHAR (1)     NULL,
    [NEW_CONSTRUCTION_CLASS_CODE] VARCHAR (50)    NULL,
    [NEW_CONSTRUCTION_VALUE]      NUMERIC (15, 2) NULL,
    [DECLARATION_SENT_DATE]       DATE            NULL,
    [DECLARATION_RETURNED_DATE]   DATE            NULL,
    [VALUED_BY]                   VARCHAR (30)    NULL,
    [NO_DECLARATION_FLAG]         VARCHAR (1)     NULL,
    [BEST_INFO_AVAILABLE_FLAG]    VARCHAR (1)     NULL,
    [NO_CHANGE_FLAG]              VARCHAR (1)     NULL,
    [ASSOCIATED_ACCOUNT]          VARCHAR (30)    NULL
);

