
CREATE view [trn].[v_etl_appeal]
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Mod Date:      5/2/2017
Developer:     T Golden
Comments:      Initial creation
               Appeal data from RW database
*************************************************************************************/

AS
SELECT
       a.TAXYEAR as TAX_YEAR
      ,a.APPEALNO as APPEAL_NO
      ,a.APPEALTYPE as APPEAL_TYPE
      ,a.APPEALMETHOD as APPEAL_METHOD
      ,a.ASSIGNEDTO as ASSIGNED_TO
      ,a.INITIATEDBY as INITIATED_BY
      ,a.AGENTCODE	as AGENT_CODE
	  ,a.AGENT_NAME as AGENT_NAME
	  ,a.AGENT_EMAILADDRESS as AGENT_EMAILADDRESS
	  ,a.AGENT_PHONE as AGENT_PHONE
	  ,a.AGENT_ADDRESS as AGENT_ADDRESS
	  ,a.FILER_EMAIL as FILER_EMAIL
      ,a.FILER_PHONE as FILER_PHONE
      ,a.FILER as FILER
      ,a.FILER_ADDRESS as FILER_ADDRESS
      ,a.FILER_CITY as FILER_CITY
      ,a.FILER_STATECODE as FILER_STATECODE
      ,a.FILER_ZIPCODE as FILER_ZIPCODE
      ,a.MAILTO as MAIL_TO
      ,a.DECISIONBY as DECISION_BY
      ,a.CASENO as CASE_NO
      ,a.REREVIEWSTATUS as REREVIEW_STATUS
      ,a.REREVIEWINITIALS as REREVIEW_INITIALS
      ,a.REREVIEWDECISION as REREVIEW_DECISION
      ,a.APPEALREASON as APPEAL_REASON
      ,a.APPEALBASIS as APPEAL_BASIS
      ,a.APPEALRECOMMENDATION as APPEAL_RECOMMENDATION
      ,a.APPEALADJUSTDENYREASONID as APPEAL_ADJUST_DENY_REASON_ID
      ,a.APPEALENDVALUE as APPEAL_END_VALUE
      ,a.DATEOFAPPEAL as DATE_OF_APPEAL
      ,a.DATERECEIVED as DATE_RECEIVED
      ,a.TAXPAYERMEETINGREQUESTFLAG as TAX_PAYER_MEETING_REQUEST_FLAG
      ,a.TAXPAYERMEETINGDATE as TAX_PAYER_MEETING_DATE
      ,a.TAXPAYERMEETINGTIME as TAX_PAYER_MEETING_TIME
      ,a.BEGINNINGAPPEALVALUE as BEGINNING_APPEAL_VALUE
      ,a.APPEALON1 as APPEAL_ON1
      ,a.APPEALON2 as APPEAL_ON2
      ,a.APPEALOD0 as APPEAL_OD0
      ,a.APPEALOD1 as APPEAL_OD1
      ,a.APPEALOM0 as APPEAL_OM0
      ,a.APPEALOM1 as APPEAL_OM1
      ,a.APPEALON0 as APPEAL_ON0
      ,a.APPEALOT0 as APPEAL_OT0
      ,a.APPEALOT1 as APPEAL_OT1
      ,a.APPRAISALTYPE as APPRAISAL_TYPE
      ,a.PRIMARYACCOUNT as PRIMARY_ACCOUNT
      ,a.JURISDICTIONID as JURISDICTION_ID
      ,a.SCHEDULEDATEAS as SCHEDULE_DATE_AS
      ,a.SCHEDULESTARTTIME as SCHEDULE_START_TIME
      ,a.SCHEDULEENDTIME as SCHEDULE_END_TIME
      ,a.SCHEDULECOMMENT as SCHEDULE_COMMENT
      ,a.SCHEDULEBOARDFILENO as SCHEDULE_BOARD_FILE_NO
      ,a.SCHEDULEAPPRAISERINITIALS as SCHEDULE_APPRAISER_INITIALS
      ,a.APPOINTMENTCOLOR as APPOINTMENT_COLOR
      ,a.WRITEDATE as WRITE_DATE
      ,a.APPEALSTATUSID as APPEAL_STATUS_ID
      ,a.APPEALREASONDESCRIPTION as APPEAL_REASON_DESCRIPTION
      ,a.BOARDNO as BOARD_NO
      ,a.APPEALDECISION as APPEAL_DECISION
      ,a.SEQID as SEQ_ID
      ,GETDATE() AS create_datetime
      ,SUSER_NAME() AS create_user_id
      ,HASHBYTES('SHA2_256', 
			  ISNULL(RTRIM(a.TAXYEAR), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.APPEALNO), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.APPEALTYPE), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.APPEALMETHOD), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.ASSIGNEDTO), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.INITIATEDBY), 'DBNULL_TEXT') 
			+ ISNULL(RTRIM(a.AGENTCODE), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.AGENT_NAME), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.AGENT_EMAILADDRESS), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.AGENT_PHONE), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.AGENT_ADDRESS), 'DBNULL_TEXT')
	        + ISNULL(RTRIM(a.FILER_EMAIL), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER_PHONE), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER_ADDRESS), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER_CITY), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER_STATECODE), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.FILER_ZIPCODE), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.MAILTO), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.DECISIONBY), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.CASENO), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.REREVIEWSTATUS), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.REREVIEWINITIALS), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.REREVIEWDECISION), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.APPEALREASON), 'DBNULL_TEXT')
			+ ISNULL(RTRIM(a.APPEALBASIS), 'DBNULL_TEXT')
			) AS rowhash
FROM asr_staging.s_tblappeal a;
















