


/****** Script for SelectTopNRows command from SSMS  ******/
CREATE VIEW [trn].[v_etl_pers_prop_detail]
AS
SELECT 
  Q_TBLACCTPPDETAIL.ACCOUNTNO ACCOUNT_NO,
  Q_TBLACCTPPDETAIL.PPRECORDNO DETAIL_ID,
  Q_TBLACCTPPDETAIL.PPOGTYPE PERS_PROP_TYPE,
  (ISNULL((SELECT
  S_TLKPPPOGDESCRIPTIONTYPE.PPOGDESCRIPTIONTYPE PPOGDESCRIPTIONTYPE
              FROM
                asr_staging.S_TLKPPPOGDESCRIPTIONTYPE
              WHERE 
              ( S_TLKPPPOGDESCRIPTIONTYPE.PPOGDESCRIPTIONTYPEID = Q_TBLACCTPPDETAIL.PPOGDESCRIPTIONTYPEID ) ), NULL)) ASSET_TYPE_CODE,
  Q_TBLACCTPPDETAIL.PPCONDITIONCODE ASSET_CONDITION_CODE,
  CAST( Q_TBLACCTPPDETAIL.ACQUISITIONYEAR as varchar(4) ) ACQUIRED_YEAR,
  Q_TBLACCTPPDETAIL.PPQUANTITY  QUANTITY,
  Q_TBLACCTPPDETAIL.ORIGINALCOST  ORIGINAL_COST,
  Q_TBLACCTPPDETAIL.PPDETAILDESCRIPTION  ASSET_DETAIL_DESCR
FROM
    dqm.Q_TBLACCTPPDETAIL  Q_TBLACCTPPDETAIL   
 --JOIN   assessor_app.asr_app.PERS_PROP_ACCT  PERS_PROP_ACCT ON ( ( Q_TBLACCTPPDETAIL.ACCOUNTNO = PERS_PROP_ACCT.ACCOUNT_NO ) )
 JOIN   [assessor_datastore].[asr_datastore].[pers_prop_acct]  PERS_PROP_ACCT ON ( ( Q_TBLACCTPPDETAIL.ACCOUNTNO = PERS_PROP_ACCT.ACCOUNT_NO ) )

  --HASHBYTES('SHA2_256', ISNULL(RTRIM(Q_TBLACCTPP.ACCOUNTNO), 'DBNULL_TEXT') + ISNULL(RTRIM(substring(Q_TBLACCT.BUSINESSNAME,1,100)), 'DBNULL_TEXT')) AS rowhash




