


CREATE VIEW [trn].[v_etl_ppnov]
AS
SELECT        ACCOUNTNO, TAXYEAR, PARCELNO, PROPADDRESS, LEGALDESCRIPTION1, LEGALDESCRIPTION2, LEGALDESCRIPTION3, NAME1, NAME2, PNAME1, PNAME2, OWNERADDRESS1, OWNERADDRESS2, 
                         OWNERCITY, OWNERSTATE, OWNERZIP, PROPCLASS1, PRIORVALUE1, CURRENTVALUE1, INCREASEDECREASE1, PROPCLASS2, PRIORVALUE2, CURRENTVALUE2, INCREASEDECREASE2, PROPCLASS3, 
                         PRIORVALUE3, CURRENTVALUE3, INCREASEDECREASE3, PROPCLASS4, PRIORVALUE4, CURRENTVALUE4, INCREASEDECREASE4, PROPCLASS5, PRIORVALUE5, CURRENTVALUE5, INCREASEDECREASE5, 
                         PROPCLASS6, PRIORVALUE6, CURRENTVALUE6, INCREASEDECREASE6, TOTALPRIOR, TOTALCURRENT, TOTALINCREASEDECREASE, VALUEYEAR, PROPERTYTYPE, PRIMARYBUILDING, BUILDINGCOUNT, 
                         SUBDIVISION, NEIGHBORHOOD, RESIDENTIALSF, STYLE, QUALITY, YEARBUILT, HEATTYPE, BASEMENTSF, FINISHEDBSMNTSF, BASEMENTTYPE, GARAGESF, IMPSF, COMMERCIALSF, OUTBUILDINGSF, 
                         LANDTYPE, ACREAGE, LEA, LANDATTRIBUTES, APPRDATEYEAR, REAPPRYEAR, BEGPERYEAR, ENDPERYEAR, CBOEDEADLINE, PRINTFLAG, BULKNOVFLAG, PRIVATEFLAG, ASSESSOR,
						 SREXEMPTIONDEADLINE, VETEXEMPTIONDEADLINE, NODMONTH

FROM            asr_staging.s_ppnov



