

-- ========================================================================
-- Author:	David Guillen
-- Create date: 2/26/2016
-- Description:	DQM stored procedure for S_TMAPTAXAUTHORITYDETAILFUND table 
-- ========================================================================


/*
DQM RULES FOR:
TABLE:  S_TMAPTAXAUTHORITYDETAILFUND

1.	    The combination of TAXYEAR, FUNDCODE, LEVYTYPEID, and TAXAUTHORITY – must be unique

*/

CREATE PROCEDURE [dqm].[dqm_s_tmaptaxauthoritydetailfund]
	

AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	  BEGIN
	

     --Begin DQM checks for the table for each row.

----------------------------------------------------------------------------------
	

	-- The combination of TAXYEAR, FUNDCODE, LEVYTYPEID, and TAXAUTHORITY – must be unique DQM check

	WITH DUPE_VALUES AS (SELECT distinct TAXYEAR,FUNDCODE,LEVYTYPEID,TAXAUTHORITY FROM [asr_staging].[s_tmaptaxauthoritydetailfund] GROUP BY TAXYEAR,FUNDCODE,LEVYTYPEID,TAXAUTHORITY HAVING COUNT(*) > 1)
	
	INSERT INTO [dqm].[s_tmaptaxauthoritydetailfund_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, TAXAUTHORITY, TAXYEAR, FUNDCODE, PARENTFUNDCODE, ASSESSEDMILLLEVY, ALTERNATEMILLLEVY, REALFLAG, PPFLAG, MAXLEVYINCLUDEFLAG, SORTORDER, JURISDICTIONID, LASTUPDATED, LEVYTYPEID, TAXDISTRICTID, EXCLUDEREDUCEDRATEFLAG, INCLUDEONTAXBILLFLAG, PERMANENTRATE, BILLINGRATE, URDOTADJUSTMENTRATE, BUDGETEDTAXVALUE, BUDGETEDTAXRATE, TRUNCATIONLOSSVALUE, FUNDCATEGORYTYPEID)
	    SELECT 
				'TAXYEAR and FUNDCODE LEVYTYPEID, and TAXAUTHORITY',
				'COMBINATION OF THREE FIELDS MUST BE UNIQUE',
				'TAXYEAR and FUNDCODE LEVYTYPEID, and TAXAUTHORITY MUST BE UNIQUE',
				@lv_RUNTIME, 
				tadf.TAXAUTHORITY, 
				tadf.TAXYEAR, 
				tadf.FUNDCODE, 
				PARENTFUNDCODE, 
				ASSESSEDMILLLEVY, 
				ALTERNATEMILLLEVY, 
				REALFLAG, 
				PPFLAG, 
				MAXLEVYINCLUDEFLAG, 
				SORTORDER, 
				JURISDICTIONID, 
				LASTUPDATED, 
				tadf.LEVYTYPEID, 
				TAXDISTRICTID, 
				EXCLUDEREDUCEDRATEFLAG, 
				INCLUDEONTAXBILLFLAG, 
				PERMANENTRATE, 
				BILLINGRATE, 
				URDOTADJUSTMENTRATE, 
				BUDGETEDTAXVALUE, 
				BUDGETEDTAXRATE, 
				TRUNCATIONLOSSVALUE, 
				FUNDCATEGORYTYPEID
			FROM [asr_staging].[s_tmaptaxauthoritydetailfund] tadf
			INNER JOIN DUPE_VALUES DV 
			ON tadf.TAXYEAR = DV.TAXYEAR
			and tadf.TAXAUTHORITY = DV.TAXAUTHORITY
			and tadf.LEVYTYPEID = DV.LEVYTYPEID
			and tadf.FUNDCODE = DV.FUNDCODE;


--------------------------------------------------------------------------------


            END


	END


