
CREATE PROCEDURE [dqm].[dqm_s_tblacctpp]
	
AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	BEGIN

     --Begin DQM checks for the table for each row.


-- The ACCOUNTNO must be unique

	WITH DUPE_VALUES AS (SELECT distinct ACCOUNTNO FROM [asr_staging].[s_tblacctpp] GROUP BY ACCOUNTNO HAVING COUNT(*) > 1)
	
	INSERT INTO [dqm].[s_tblacctpp_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG)
	    SELECT 
				'ACCOUNTNO, PROPERTYTYPE, NBHDCODE, NBHDEXTENSION',
				'COMBINATION OF FOUR FIELDS MUST BE UNIQUE',
				'ACCOUNTNO, PROPERTYTYPE, NBHDCODE, NBHDEXTENSION MUST BE UNIQUE', 
				@lv_RUNTIME, 
				--GETDATE(),
				VERSTART, VEREND, pp.ACCOUNTNO, pp.PPCERTIFICATIONCODE, pp.PPCERTIFICATIONDATE, pp.JURISDICTIONAUDITDATE, pp.NOVSENTDATE, pp.ASSOCIATEDREALSF, pp.PPAUDITEDBY, pp.PPDECLARATIONSENTDATE, pp.PPDECLARATIONRETURNDATE, pp.ASSOCIATEDREALUNITCOUNT, pp.LATEDECLARATIONFLAG, pp.PRECOLLECTDATE, pp.LETTERSENTFLAG, pp.PPAPPRAISER, pp.PPAPPRASALDATE, pp.CROPTYPE, pp.ACRESUSED, pp.FARMSERVICEAGENCYFLAG, pp.FARMSERVICEAGENCYNO, pp.NOCHANGEFLAG, pp.AUDITDATE, pp.NODECLARATIONFLAG, pp.BESTINFOAVAILABLEFLAG, pp.PPCITYCODE, pp.ATTACHMENTCOUNT, pp.SPECIALDISTRICT1, pp.SPECIALDISTRICT2, pp.AREACODEID, pp.DESKAUDITBY, pp.PPUNITTYPE, pp.APPRAISEDVALUEPERUNIT, pp.UNITNUMBER, pp.SMALLACCTCERTIFICATIONFLAG, pp.STATESALESTAXID, pp.FEDERALID, pp.ACCTPPON0, pp.ACCTPPON1, pp.ACCTPPON2, pp.ELECTRONICFILEFLAG, pp.ACCTPPOD0, pp.ACCTPPOD1, pp.ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG
			FROM [asr_staging].[s_tblacctpp] pp
			INNER JOIN DUPE_VALUES DV 
			ON pp.ACCOUNTNO = DV.ACCOUNTNO;
			
----------------------------------------------------------------------------------

	
	INSERT INTO [dqm].[s_tblacctpp_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG)
	    SELECT 
				'ACCOUNTNO',
				'FIELD CANNOT BE NULL',
				'ACCOUNTNO CANNOT BE NULL',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG
			FROM asr_staging.s_tblacctpp
			WHERE accountno is NULL or accountno = '';


----------------------------------------------------------------------------------
  /*
    INSERT INTO [asr_staging].[s_tblacctpp_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG)
	    SELECT 
				'ACCOUNTNO',
				'FIELD MUST EXIST IN ACCOUNT TABLE',
				'ACCOUNTNO MUST EXIST IN S_TBLACCT',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG
			FROM s_tblacctpp pp
			WHERE accountno not in (select distinct accountno from s_tblacct)

*/

----------------------------------------------------------------------------------

	INSERT INTO [dqm].[s_tblacctpp_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG)
	    SELECT 
				'BUSINESSCODE',
				'FIELD CANNOT BE NULL',
				'BUSINESSCODE CANNOT BE NULL',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG
			FROM asr_staging.s_tblacctpp
			WHERE businesscode is NULL or businesscode = '';

----------------------------------------------------------------------------------
	INSERT INTO [dqm].[s_tblacctpp_err]
		(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG)
			SELECT 
					'PPVAL',
					'VALUE MUST EQUAL SUM OF PPVAL',
					'APPRAISEDVALUE PER UNIT MUST EQUAL SUM OF PPVAL FOR THE ACCOUNT',
					--getdate(),
					@lv_RUNTIME,
					VERSTART, VEREND, ACCOUNTNO, PPCERTIFICATIONCODE, PPCERTIFICATIONDATE, JURISDICTIONAUDITDATE, NOVSENTDATE, ASSOCIATEDREALSF, PPAUDITEDBY, PPDECLARATIONSENTDATE, PPDECLARATIONRETURNDATE, ASSOCIATEDREALUNITCOUNT, LATEDECLARATIONFLAG, PRECOLLECTDATE, LETTERSENTFLAG, PPAPPRAISER, PPAPPRASALDATE, CROPTYPE, ACRESUSED, FARMSERVICEAGENCYFLAG, FARMSERVICEAGENCYNO, NOCHANGEFLAG, AUDITDATE, NODECLARATIONFLAG, BESTINFOAVAILABLEFLAG, PPCITYCODE, ATTACHMENTCOUNT, SPECIALDISTRICT1, SPECIALDISTRICT2, AREACODEID, DESKAUDITBY, PPUNITTYPE, APPRAISEDVALUEPERUNIT, UNITNUMBER, SMALLACCTCERTIFICATIONFLAG, STATESALESTAXID, FEDERALID, ACCTPPON0, ACCTPPON1, ACCTPPON2, ELECTRONICFILEFLAG, ACCTPPOD0, ACCTPPOD1, ACCTPPOM0, ACCTPPOM1, ACCTPPOT0, ACCTPPOT1, BUSINESSCODE, JURISDICTIONID, WRITEDATE, SEQID, ONLINEFILINGOPTOUTFLAG
				FROM asr_staging.s_tblacctpp
				WHERE APPRAISEDVALUEPERUNIT <> [dbo].[get_total_ppval](ACCOUNTNO);

----------------------------------------------------------------------------------

	END	

END







