
-- =====================================================================================
-- Author:		Tony Golden
-- Create date: 6/2/2014
-- Description:	DQM stored procedure for s_tblacctppdetail
-- =====================================================================================


/*
DQM RULES FOR:
TABLE:  tblacctppdetail

DATA_RULE_USAGE_NAME		DATA_RULE_USAGE_DESCR

IS_FK_1C_ACCT_NO			Foreign key check on accountno to tblacctpp
IS_FK_1C_TYPE				Foreign key check on description type to tlkpppogtype
IS_FK_1C_DESC				Foreign key check on description type to tlkpppogdescriptiontype
IS_FK_1C_CONDITION			Foreign key check on conditioncode  to tlkpppcondition
IS_0_OR_POSITIVE_NUMBER_1	Quantity has to be >= 0
IS_0_OR_POSITIVE_NUMBER		Original cost has to be >= 0

*/

CREATE PROCEDURE [dqm].[dqm_s_tblacctppdetail]
	
AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	BEGIN

     --Begin DQM checks for the table for each row.




	
	INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
	    SELECT 
				'ACCOUNTNO',
				'FIELD MUST EXIST IN PARENT TABLE',
				'ACCOUNTNO MUST EXIST IN S_TBLACCTPP',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
			FROM asr_staging.s_tblacctppdetail
			WHERE accountno not in (select distinct accountno from asr_staging.s_tblacctpp)

----------------------------------------------------------------------------------


INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
	    SELECT 
				'PPOGTYPE',
				'FIELD MUST EXIST IN LOOKUP TABLE',
				'PPOGTYPE MUST EXIST IN S_TLKPPPOGTYPE',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
			FROM asr_staging.s_tblacctppdetail
			WHERE ppogtype not in (select distinct ppogtype from asr_staging.s_tlkpppogtype)

----------------------------------------------------------------------------------

INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
	    SELECT 
				'PPOGDESCRIPTIONTYPE',
				'FIELD MUST EXIST IN LOOKUP TABLE',
				'PPOGTYPE MUST EXIST IN S_TLKPPPOGDESCRIPTIONTYPE',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
			FROM asr_staging.s_tblacctppdetail
			WHERE ppogdescriptiontypeid not in (select distinct ppogdescriptiontypeid from asr_staging.s_tlkpppogdescriptiontype)

----------------------------------------------------------------------------------

INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
	    SELECT 
				'PPCONDITIONCODE',
				'FIELD MUST EXIST IN LOOKUP TABLE',
				'PPCONDITIONCODE MUST EXIST IN S_TLKPPPOGDESCRIPTIONTYPE',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
			FROM asr_staging.s_tblacctppdetail
			WHERE ppconditioncode not in (select distinct ppconditioncode from asr_staging.s_tlkpppcondition)

----------------------------------------------------------------------------------

	INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
	    SELECT 
				'PPQUANTITY',
				'VALUE MUST BE >= 0',
				'PPQUANTITY MUST BE >=0',
				--getdate(),
				@lv_RUNTIME,
				VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
			FROM asr_staging.s_tblacctppdetail
			WHERE ppquantity < 0

----------------------------------------------------------------------------------
	INSERT INTO [dqm].[s_tblacctppdetail_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID)
			SELECT 
					'ORIGINALCOST',
					'VALUE MUST BE >= 0',
					'ORIGINALCOST MUST BE >=0',
					--getdate(),
					@lv_RUNTIME,
					VERSTART, VEREND, ACCOUNTNO, DETAILID, PPRECORDNO, ABSTRACTCODE, ABSTRACTADJCODE, TAXDISTRICT, PPOGTYPE, PPOGDESCRIPTIONTYPEID, ACQUISITIONYEAR, PPAGE, PPQUANTITY, TYPEFACTOR, ORIGINALCOST, PPMETHODCODE, PPLIFEEXPECTANCY, PPCONDITIONCODE, PPGOODPERCENT, PERCENTADDEDDEPRECIATION, ROLLBACKFACTOR, PPABSTRACTVALUE, BESTINFOAVAILABLEFLAG, OMITTEDFLAG, DEPRECIATIONVALUE, REPORTEDACQUIREDYEAR, REPORTEDACQUIREDCOST, PPREPORTEDRECORDNO, PPMAKE, PPMODEL, PPLEASETERM, PPMONTHLYRENT, PPLESSORCODE, PPDETAILDESCRIPTION, JURISDICTIONID, WRITEDATE, APPRAISALTYPE, SEQID
				FROM asr_staging.s_tblacctppdetail
				WHERE ORIGINALCOST < 0

----------------------------------------------------------------------------------

	END	

END






