

-- =====================================================================================
-- Author:		Richard Edwards
-- Create date: 4/19/2016
-- Description:	DQM stored procedure for TSGNVALUE table in Realware_ODS
-- =====================================================================================


/*
DQM RULES FOR:
TABLE:  S_TSGNVALUE

1. ACCOUNTNO - Must exist in table s_tblacct - FK check

 2. TAXYEAR - Must be a valid year

 3. VALUEGROUPCODE - Must exist in s_tblkvaluegroup

 4. TAXDISTRICT - Must exist in s_tklptaxdistrict - FK check

*/

CREATE PROCEDURE [dqm].[dqm_s_tsgnvalue_backup_05022016]
	

AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	  BEGIN
	

     --Begin DQM checks for the table for each row.

----------------------------------------------------------------------------------

   -- ACCOUNTNO - Must exist in table s_tblacct - FK check

INSERT INTO [dqm].[s_tsgnvalue_err]
	(
    [COLUMN_NAME],
	[DQM_RULE],
	[ERROR_DESCRIPTION],
	[DQM_RUN_DATE],
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
    )
	    SELECT 
				'ACCOUNTNO',
				'ACCOUNTNO MUST EXIST IN ACCOUNT TABLE - FK CHECK',
				'ACCOUNT NUMBER MUST EXIST IN TABLE S_TBLACCT',
				@lv_RUNTIME,
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
			FROM [asr_staging].[s_tsgnvalue]
			WHERE ACCOUNTNO NOT IN (SELECT DISTINCT ACCOUNTNO FROM asr_staging.s_tblacct)
------------------------------------------------------------------------------

     --TAXYEAR - Must be a valid year between 1850 and 2050

	 INSERT INTO [dqm].[s_tsgnvalue_err]
	(
    [COLUMN_NAME],
	[DQM_RULE],
	[ERROR_DESCRIPTION],
	[DQM_RUN_DATE],
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
    )
	    SELECT 
				'TAXYEAR',
				'TAXYEAR MUST BE VALID YEAR',
				'TAXYEAR MUST BE BETWEEN 1850 AND 2050',
				@lv_RUNTIME,
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
			FROM [asr_staging].[s_tsgnvalue]
            WHERE TAXYEAR NOT BETWEEN 1850 AND 2050

------------------------------------------------------------------------------
     --VALUEGROUPCODE - Must exist in s_tblkvaluegroup

	 INSERT INTO [dqm].[s_tsgnvalue_err]
	(
    [COLUMN_NAME],
	[DQM_RULE],
	[ERROR_DESCRIPTION],
	[DQM_RUN_DATE],
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
    )
	    SELECT 
				'VALUEGROUPCODE',
				'VALUEGROUPCODE MUST BE VALID CODE',
				'VALUEGROUPCODE MUST EXIST IN LOOKUP TABLE FOR VALUEGROUP',
				@lv_RUNTIME,
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
			FROM [asr_staging].[s_tsgnvalue]
			WHERE VALUEGROUPCODE NOT IN (SELECT VALUEGROUPCODE FROM asr_staging.s_tlkpvaluegroup)

------------------------------------------------------------------------------

     -- TAXDISTRICT - Must exist in s_tklptaxdistrict FK check

	  INSERT INTO [dqm].[s_tsgnvalue_err]
	(
    [COLUMN_NAME],
	[DQM_RULE],
	[ERROR_DESCRIPTION],
	[DQM_RUN_DATE],
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
    )
	    SELECT 
				'TAXDISTRICT',
				'FK CHECK',
				'TAXDISTRICT MUST EXIST IN LOOKUP TABLE FOR TAXDISTRICT',
				@lv_RUNTIME,
	[ACCOUNTNO],
	[TAXYEAR],
	[VALUEGROUPCODE],
	[TAXDISTRICT],
	[PARCELNO],
	[TAXDOLLARS],
	[ALTERNATETAXDOLLARS],
	[ADJUSTEDTAXDOLLARS],
	[ADJALTERNATETAXDOLLARS],
	[TOTALTAXDOLLARS],
	[ADJTOTALTAXDOLLARS],
	[ACTUALVALUE],
	[ADJACTUALVALUE],
	[ALTERNATEADJACTUALVALUE],
	[ADJALTERNATEADJACTUALVALUE],
	[ASSESSEDVALUE],
	[ALTERNATEASSESSEDVALUE],
	[ADJASSESSEDVALUE],
	[ADJALTERNATEASSESSEDVALUE],
	[MILLLEVY],
	[ALTERNATEMILLLEVY],
	[AVERAGEASSESSMENTRATIO],
	[AVERAGEALTASSESSMENTRATIO],
	[ACTUALPENALTYVALUE],
	[ALTERNATEACTUALPENALTYVALUE],
	[ASSESSEDPENALTYVALUE],
	[ALTERNATEASSDPENALTYVALUE],
	[PENALTYTAXDOLLARS],
	[ALTERNATEPENALTYTAXDOLLARS],
	[RAWASSESSEDVALUE],
	[RAWTAXDOLLARS],
	[TOTALPENALTYTAXDOLLARS],
	[IMPCURRENTUSE],
	[LANDMKTUSE],
	[JURISDICTIONID],
	[LASTUPDATED],
	[FINALADJASSESSEDVALUE],
	[FINALADJALTASSESSEDVALUE],
	[FINALADJASSDPENALTYVALUE],
	[FINALADJALTASSDPENALTYVALUE],
	[CCIAPPLICATIONID],
	[CAPOVERMARKETVALUE]
			FROM [asr_staging].[s_tsgnvalue]
			WHERE TAXDISTRICT NOT IN (SELECT DISTINCT TAXDISTRICT FROM asr_staging.s_tlkptaxdistrict)

            END




		END