

-- ==============================================================
-- Author:	David Guillen
-- Create date: 2/25/2016
-- Description:	DQM stored procedure for S_TLKPABSTRACTCODE table
-- ==============================================================


/*
DQM RULES FOR:
TABLE:  S_TLKPABSTRACTCODE

1.	    ABSTRACTDESCRIPTION – must be 256 characters or less

*/

CREATE PROCEDURE [dqm].[dqm_s_tlkpabstractcode]
	

AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	  BEGIN
	

     --Begin DQM checks for the table.

----------------------------------------------------------------------------------
	-- ABSTRACTDESCRIPTION – must be 256 characters or less DQM check
	
	INSERT INTO [dqm].[s_tlkpabstractcode_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, ABSTRACTCODE, ABSTRACTDESCRIPTION, EQUIVALENCEABSTRACTCODE, ROLLABSTRACTVALUEFLAG, VALUEGROUPCODE, ACTUALPRECISION, ACTUALMINIMUMVALUE, ASSESSEDPRECISION, ASSESSEDMINIMUMVALUE, ACTUALROUNDTYPE, ASSESSEDROUNDTYPE, USEVALUEFLAG, ADJACTUALPRECISION, ADJACTUALMINIMUMVALUE, ADJACTUALROUNDTYPE, ADJASSESSEDPRECISION, ADJASSESSEDMINIMUMVALUE, ADJASSESSEDROUNDTYPE, ADJALTACTUALPRECISION, ADJALTACTUALMINVALUE, ADJALTACTUALROUNDTYPE, ADJALTASSESSEDPRECISION, ADJALTASSESSEDMINVALUE, ADJALTASSESSEDDROUNDTYPE, ALTASSESSEDPRECISION, ALTASSESSEDMINIMUMVALUE, ALTASSESSEDROUNDTYPE, SHOWADMINFLAG, CLASSIFICATIONID, LOCALGROWTHEXEMPTFLAG, EXPORTCNTGROUPEXCLUSIONFLAG, SORTORDER, ACTIVEFLAG, LIMITTOABSTTYPE, JURISDICTIONID, LASTUPDATED, ABSTRACTCATEGORYCODE)
	    SELECT 
				'ABSTRACTDESCRIPTION',
				'FIELD LENGTH CONSTRAINT',
				'ABSTRACTDESCRIPTION MUST BE 256 CHARACTERS OR LESS',
				@lv_RUNTIME,
				ABSTRACTCODE, 
				ABSTRACTDESCRIPTION, 
				EQUIVALENCEABSTRACTCODE, 
				ROLLABSTRACTVALUEFLAG, 
				VALUEGROUPCODE, 
				ACTUALPRECISION, 
				ACTUALMINIMUMVALUE, 
				ASSESSEDPRECISION, 
				ASSESSEDMINIMUMVALUE, 
				ACTUALROUNDTYPE, 
				ASSESSEDROUNDTYPE, 
				USEVALUEFLAG, 
				ADJACTUALPRECISION, 
				ADJACTUALMINIMUMVALUE, 
				ADJACTUALROUNDTYPE, 
				ADJASSESSEDPRECISION, 
				ADJASSESSEDMINIMUMVALUE, 
				ADJASSESSEDROUNDTYPE, 
				ADJALTACTUALPRECISION,
				ADJALTACTUALMINVALUE, 
				ADJALTACTUALROUNDTYPE, 
				ADJALTASSESSEDPRECISION, 
				ADJALTASSESSEDMINVALUE, 
				ADJALTASSESSEDDROUNDTYPE, 
				ALTASSESSEDPRECISION, 
				ALTASSESSEDMINIMUMVALUE, 
				ALTASSESSEDROUNDTYPE, 
				SHOWADMINFLAG, 
				CLASSIFICATIONID, 
				LOCALGROWTHEXEMPTFLAG, 
				EXPORTCNTGROUPEXCLUSIONFLAG, 
				SORTORDER, 
				ACTIVEFLAG, 
				LIMITTOABSTTYPE, 
				JURISDICTIONID, 
				LASTUPDATED, 
				ABSTRACTCATEGORYCODE
			FROM [asr_staging].[s_tlkpabstractcode]
			WHERE LEN(ABSTRACTDESCRIPTION) > 256



--------------------------------------------------------------------------------

            END


	END
	

