





-- ==========================================================
-- Author:		David Guillen
-- Create date: 1/22/2016
-- Description:	DQM stored procedure for S_TBNSUBFILING table
-- ==========================================================


/*
DQM RULES FOR:
TABLE:  S_TBNSUBFILING

1.	    SUBFILINGRECORDINGNO – cannot be NULL

*/

CREATE PROCEDURE [dqm].[dqm_s_tbnsubfiling]
	

AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	  BEGIN
	

     --Begin DQM checks for the table for each row.

----------------------------------------------------------------------------------
	
	-- SUBFILINGRECORDINGNO – cannot be NULL DQM check and also check for empty string
	
	INSERT INTO [dqm].[s_tbnsubfiling_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, SUBNO, FILINGNO, SUBFILINGDESCRIPTION, SUBFILINGRECORDINGNO, SUBFILINGCITY, DEFAULTSECTION, DEFAULTTOWNSHIP, DEFAULTRANGE, DEFAULTQTR, DEFAULTQTRQTR, SUBFILINGDATERECORDED, DEFAULTLEA, DEFAULTTAXDISTRICT, MAPNO, ECONOMICAREACODE, ACCOUNTTYPE, LANDCERTIFICATIONCODE, FLAGTYPE, SUBFILINGSTATUS, DEFAULTAPPROACHTYPE, VALUEAREACODE, ZONINGCODE, BLOCKCOUNT, LOTCOUNT, TRACTCOUNT, SUBFILINGMHTITLEFLAG, SUBFILINGNOTESFLAG, SUBFILINGNEWCONSTFLAG, SUBFILINGPHOTOSFLAG, SUBFILINGSKETCHESFLAG, SUBFILINGTAXYEAR, SUBFILINGON0, SUBFILINGON1, SUBFILINGON2, ASSIGNEDTO, SUBFILINGOD0, SUBFILINGOD1, SUBFILINGOM0, SUBFILINGOM1, SUBFILINGOT0, SUBFILINGOT1, JURISDICTIONID, DEFAULTLEGAL, LASTUPDATED, PRIMARYUSECODE, APPRAISALTYPE)
	    SELECT 
				'SUBFILINGRECORDINGNO',
				'FIELD CANNOT BE NULL',
				'SUBFILINGRECORDINGNO CANNOT BE NULL',
				@lv_RUNTIME,
				SUBNO, 
				FILINGNO, 
				SUBFILINGDESCRIPTION, 
				SUBFILINGRECORDINGNO, 
				SUBFILINGCITY, 
				DEFAULTSECTION, 
				DEFAULTTOWNSHIP, 
				DEFAULTRANGE, 
				DEFAULTQTR, 
				DEFAULTQTRQTR, 
				SUBFILINGDATERECORDED, 
				DEFAULTLEA, 
				DEFAULTTAXDISTRICT, 
				MAPNO, 
				ECONOMICAREACODE, 
				ACCOUNTTYPE, 
				LANDCERTIFICATIONCODE, 
				FLAGTYPE, 
				SUBFILINGSTATUS, 
				DEFAULTAPPROACHTYPE, 
				VALUEAREACODE, 
				ZONINGCODE, 
				BLOCKCOUNT, 
				LOTCOUNT, 
				TRACTCOUNT, 
				SUBFILINGMHTITLEFLAG, 
				SUBFILINGNOTESFLAG, 
				SUBFILINGNEWCONSTFLAG, 
				SUBFILINGPHOTOSFLAG, 
				SUBFILINGSKETCHESFLAG, 
				SUBFILINGTAXYEAR, 
				SUBFILINGON0, 
				SUBFILINGON1, 
				SUBFILINGON2, 
				ASSIGNEDTO, 
				SUBFILINGOD0, 
				SUBFILINGOD1, 
				SUBFILINGOM0, 
				SUBFILINGOM1, 
				SUBFILINGOT0, 
				SUBFILINGOT1, 
				JURISDICTIONID, 
				DEFAULTLEGAL, 
				LASTUPDATED, 
				PRIMARYUSECODE, 
				APPRAISALTYPE
			FROM [asr_staging].[s_tbnsubfiling]
			WHERE SUBFILINGRECORDINGNO IS NULL
			or SUBFILINGRECORDINGNO = '';

--------------------------------------------------------------------------------

            END




		END
	













