CREATE PROCEDURE [dqm].[dqm_s_tlkptaxauthority]
	

AS
BEGIN

    DECLARE @lv_RUNTIME  DATETIME=GETDATE()

	  BEGIN
	

     --Begin DQM checks for the table.

----------------------------------------------------------------------------------
	-- AUTHORITYTYPE – must be 50 characters or less DQM check
	
	INSERT INTO [dbo].[s_tlkptaxauthority_err]
	(COLUMN_NAME, DQM_RULE, ERROR_DESCRIPTION, DQM_RUN_DATE, TAXAUTHORITY, STATEAUTHORITYCODE, AUTHORITYTYPE, AUTHORITYNAME, CREATIONDATE, CONTACTPERSON, CONTACTADDRESS1, CONTACTADDRESS2, CONTACTCITY, CONTACTSTATE, CONTACTZIPCODE, AFFILIATE, AUTHORITYSIZE, SORTORDER, ACTIVEFLAG, JURISDICTIONID, LASTUPDATED, CONTACTPHONE, AUTHORITYVALUETYPE, ISURBANRENEWALAUTHORIZERFLAG)
	    SELECT 
				'AUTHORITYTYPE',
				'FIELD MUST BE 50 CHARACTERS OR LESS',
				'AUTHORITYTYPE MUST BE 50 CHARACTERS OR LESS',
				@lv_RUNTIME,
				TAXAUTHORITY, 
				STATEAUTHORITYCODE, 
				AUTHORITYTYPE, 
				AUTHORITYNAME, 
				CREATIONDATE, 
				CONTACTPERSON, 
				CONTACTADDRESS1, 
				CONTACTADDRESS2, 
				CONTACTCITY, 
				CONTACTSTATE, 
				CONTACTZIPCODE, 
				AFFILIATE, 
				AUTHORITYSIZE, 
				SORTORDER, 
				ACTIVEFLAG, 
				JURISDICTIONID, 
				LASTUPDATED, 
				CONTACTPHONE, 
				AUTHORITYVALUETYPE, 
				ISURBANRENEWALAUTHORIZERFLAG
			FROM [dbo].[s_tlkptaxauthority]
			WHERE LEN(AUTHORITYTYPE) >= 50



--------------------------------------------------------------------------------

            END




		END
	











