CREATE TABLE [dbo].[EXPORT_TABLE_NOT_USED] (
    [PROPERTY_ACCOUNT_NO]    VARCHAR (100) NULL,
    [STATE_PARCEL_NO]        VARCHAR (100) NULL,
    [OWNER_NAME]             VARCHAR (100) NULL,
    [MAILING_STREET_ADDRESS] VARCHAR (100) NULL,
    [MAILING_CITY]           VARCHAR (100) NULL,
    [MAILING_ZIP_CODE]       VARCHAR (100) NULL
);

