CREATE TABLE [cboe].[appeal] (
    [TAX_YEAR]                       NUMERIC (4)      NULL,
    [APPEAL_NO]                      NUMERIC (15)     NULL,
    [APPEAL_TYPE]                    VARCHAR (30)     NULL,
    [APPEAL_METHOD]                  VARCHAR (30)     NULL,
    [ASSIGNED_TO]                    VARCHAR (20)     NULL,
    [INITIATED_BY]                   VARCHAR (30)     NULL,
    [AGENT_CODE]                     NUMERIC (15)     NULL,
    [AGENT_NAME]                     VARCHAR (150)    NULL,
    [AGENT_EMAILADDRESS]             VARCHAR (100)    NULL,
    [AGENT_PHONE]                    VARCHAR (25)     NULL,
    [AGENT_ADDRESS]                  VARCHAR (250)    NULL,
    [FILER_EMAIL]                    VARCHAR (100)    NULL,
    [FILER_PHONE]                    VARCHAR (18)     NULL,
    [FILER]                          VARCHAR (250)    NULL,
    [FILER_ADDRESS]                  VARCHAR (50)     NULL,
    [FILER_CITY]                     VARCHAR (50)     NULL,
    [FILER_STATECODE]                VARCHAR (2)      NULL,
    [FILER_ZIPCODE]                  VARCHAR (10)     NULL,
    [MAIL_TO]                        VARCHAR (30)     NULL,
    [DECISION_BY]                    VARCHAR (30)     NULL,
    [CASE_NO]                        VARCHAR (30)     NULL,
    [REREVIEW_STATUS]                VARCHAR (30)     NULL,
    [REREVIEW_INITIALS]              VARCHAR (30)     NULL,
    [REREVIEW_DECISION]              VARCHAR (30)     NULL,
    [APPEAL_REASON]                  VARCHAR (30)     NULL,
    [APPEAL_BASIS]                   VARCHAR (30)     NULL,
    [APPEAL_RECOMMENDATION]          VARCHAR (30)     NULL,
    [APPEAL_ADJUST_DENY_REASON_ID]   NUMERIC (15)     NULL,
    [APPEAL_END_VALUE]               NUMERIC (15, 2)  NULL,
    [DATE_OF_APPEAL]                 VARCHAR (22)     NULL,
    [DATE_RECEIVED]                  VARCHAR (22)     NULL,
    [TAX_PAYER_MEETING_REQUEST_FLAG] NUMERIC (1)      NULL,
    [TAX_PAYER_MEETING_DATE]         VARCHAR (22)     NULL,
    [TAX_PAYER_MEETING_TIME]         VARCHAR (100)    NULL,
    [BEGINNING_APPEAL_VALUE]         NUMERIC (15, 2)  NULL,
    [APPEAL_ON1]                     NUMERIC (20, 6)  NULL,
    [APPEAL_ON2]                     NUMERIC (20, 6)  NULL,
    [APPEAL_OD0]                     VARCHAR (22)     NULL,
    [APPEAL_OD1]                     VARCHAR (22)     NULL,
    [APPEAL_OM0]                     VARCHAR (50)     NULL,
    [APPEAL_OM1]                     VARCHAR (50)     NULL,
    [APPEAL_ON0]                     NUMERIC (20, 6)  NULL,
    [APPEAL_OT0]                     VARCHAR (50)     NULL,
    [APPEAL_OT1]                     VARCHAR (50)     NULL,
    [APPRAISAL_TYPE]                 VARCHAR (30)     NULL,
    [PRIMARY_ACCOUNT]                VARCHAR (30)     NULL,
    [JURISDICTION_ID]                NUMERIC (15)     NULL,
    [SCHEDULE_DATE_AS]               VARCHAR (22)     NULL,
    [SCHEDULE_START_TIME]            VARCHAR (50)     NULL,
    [SCHEDULE_END_TIME]              VARCHAR (50)     NULL,
    [SCHEDULE_COMMENT]               VARCHAR (500)    NULL,
    [SCHEDULE_BOARD_FILE_NO]         VARCHAR (30)     NULL,
    [SCHEDULE_APPRAISER_INITIALS]    VARCHAR (30)     NULL,
    [APPOINTMENT_COLOR]              VARCHAR (50)     NULL,
    [WRITE_DATE]                     VARCHAR (22)     NULL,
    [APPEAL_STATUS_ID]               NUMERIC (15)     NULL,
    [APPEAL_REASON_DESCRIPTION]      VARCHAR (1000)   NULL,
    [BOARD_NO]                       VARCHAR (10)     NULL,
    [APPEAL_DECISION]                VARCHAR (30)     NULL,
    [SEQ_ID]                         NUMERIC (15)     NULL,
    [create_datetime]                DATETIME         NULL,
    [create_user_id]                 NVARCHAR (128)   NULL,
    [rowhash]                        VARBINARY (8000) NULL,
    [update_datetime]                DATETIME         NULL,
    [update_user_id]                 NVARCHAR (128)   NULL
);

