


CREATE VIEW [asr_app_query].[v_ppnov]
AS
SELECT        rn.ACCOUNTNO, rn.TAXYEAR, rn.PARCELNO, rn.PROPADDRESS, rn.LEGALDESCRIPTION1, rn.LEGALDESCRIPTION2, rn.LEGALDESCRIPTION3, rn.NAME1, rn.NAME2, rn.PNAME1, rn.PNAME2, 
                         rn.OWNERADDRESS1, rn.OWNERADDRESS2, rn.OWNERCITY, rn.OWNERSTATE, rn.OWNERZIP, rn.PROPCLASS1, rn.PRIORVALUE1, rn.CURRENTVALUE1, rn.INCREASEDECREASE1, rn.PROPCLASS2, 
                         rn.PRIORVALUE2, rn.CURRENTVALUE2, rn.INCREASEDECREASE2, rn.PROPCLASS3, rn.PRIORVALUE3, rn.CURRENTVALUE3, rn.INCREASEDECREASE3, rn.PROPCLASS4, rn.PRIORVALUE4, rn.CURRENTVALUE4, 
                         rn.INCREASEDECREASE4, rn.PROPCLASS5, rn.PRIORVALUE5, rn.CURRENTVALUE5, rn.INCREASEDECREASE5, rn.PROPCLASS6, rn.PRIORVALUE6, rn.CURRENTVALUE6, rn.INCREASEDECREASE6, 
                         rn.TOTALPRIOR, rn.TOTALCURRENT, rn.TOTALINCREASEDECREASE, rn.VALUEYEAR, rn.PROPERTYTYPE, rn.PRIMARYBUILDING, rn.BUILDINGCOUNT, rn.SUBDIVISION, rn.NEIGHBORHOOD, rn.RESIDENTIALSF, 
                         rn.STYLE, rn.QUALITY, rn.YEARBUILT, rn.HEATTYPE, rn.BASEMENTSF, rn.FINISHEDBSMNTSF, rn.BASEMENTTYPE, rn.GARAGESF, rn.IMPSF, rn.COMMERCIALSF, rn.OUTBUILDINGSF, rn.LANDTYPE, rn.ACREAGE,
                          rn.LEA, rn.LANDATTRIBUTES, rn.APPRDATEYEAR, rn.REAPPRYEAR, rn.BEGPERYEAR, rn.ENDPERYEAR, rn.CBOEDEADLINE, rn.PRINTFLAG, rn.BULKNOVFLAG, rn.PRIVATEFLAG, rn.create_datetime, 
                         rn.create_user_id, rn.update_datetime, rn.update_user_id, rn.ASSESSOR, rn.SREXEMPTIONDEADLINE, rn.VETEXEMPTIONDEADLINE, rn.NODMONTH

FROM            asr_datastore.ppnov AS rn INNER JOIN
                         assessor_app.asr_app.account AS ac ON rn.ACCOUNTNO = ac.account_no



