
CREATE VIEW [rw_extract].[V_NODTABLE1]
AS
SELECT        [HEADER]
      ,[AGENT_FLAG]
      ,[REVIEWNUMBER]
      ,[TAXYEAR]
      ,[OWNERNAME1]
      ,[OWNERNAME2]
      ,[OWNERADDRESS1]
      ,[OWNERADDRESS2]
      ,[OWNERCITY]
      ,[OWNERSTATE]
      ,[OWNERZIP]
      ,[LOCATION]
      ,[SUBNAME]
      ,[VALUEDESCRIPTION1]
      ,[VALUEDESCRIPTION2]
      ,[VALUEDESCRIPTION3]
FROM            PRRW.dbo.NODTABLE1




