

CREATE VIEW [rw_extract].[V_OD_PROPERTYLOCATION]
AS
SELECT DISTINCT 
                      PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO AS ACCOUNT_NO, PRRW.ENCOMPASS.TBLACCT.ACCTTYPE AS ACCOUNT_TYPE_CODE, 
                      PRRW.ENCOMPASS.TBLACCT.PARCELNO AS STATE_PARCEL_NO, PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.STREETNO AS ADDRESS_NUMBER, 
                      PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.PREDIRECTION AS PRE_DIRECTION_CODE, 
                      PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.STREETNAME AS STREET_NAME, PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.STREETTYPE AS STREET_TYPE_CODE, 
                      PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.UNITNAME AS UNIT_NO, PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.PROPERTYZIPCODE AS LOCATION_ZIP_CODE, 
                      PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.PROPERTYCITY AS CITY_NAME, PRRW.ENCOMPASS.TBLACCTLEGAL.LEGAL AS LEGAL_DESCR, 
                      PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.SECTION, PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.TOWNSHIP, PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.RANGE, 
                      PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.QTR AS QUARTER, PRRW.ENCOMPASS.TBLACCTREAL.DEFAULTLEA AS LAND_ECONOMIC_AREA_CODE, 
                      CASE WHEN PRRW.ENCOMPASS.TBLACCTREAL.VACANTFLAG = 1 THEN 'Y' ELSE 'N' END AS VACANT_FLAG, 
                      PRRW.ENCOMPASS.TBLACCTREAL.LANDGROSSACRES AS TOTAL_NET_ACRES, PRRW.ENCOMPASS.TBLACCT.DEFAULTTAXDISTRICT AS TAX_DISTRICT_NO, 
                      PRRW.dbo.uv_Prop_NBHDs.NBHDCODE AS NEIGHBORHOOD_CODE, PRRW.dbo.uv_Prop_NBHDs.NBHDEXTENSION AS NEIGHBORHOOD_EXTENSION
FROM         PRRW.ENCOMPASS.TBLACCT INNER JOIN
                      PRRW.ENCOMPASS.TBLACCTREAL ON PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO = PRRW.ENCOMPASS.TBLACCTREAL.ACCOUNTNO INNER JOIN
                      PRRW.ENCOMPASS.TBLACCTLEGALLOCATION ON PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO = PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.ACCOUNTNO INNER JOIN
                      PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS ON PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO = PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.ACCOUNTNO INNER JOIN
                      PRRW.ENCOMPASS.TBLACCTLEGAL ON PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO = PRRW.ENCOMPASS.TBLACCTLEGAL.ACCOUNTNO INNER JOIN
                      PRRW.dbo.uv_Prop_NBHDs ON PRRW.ENCOMPASS.TBLACCT.ACCOUNTNO = PRRW.dbo.uv_Prop_NBHDs.accountno
WHERE     (PRRW.ENCOMPASS.TBLACCT.ACCTSTATUSCODE = 'A') AND (PRRW.ENCOMPASS.TBLACCT.VEREND = 99999999999) AND 
                      (PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS.VEREND = 99999999999) AND (PRRW.ENCOMPASS.TBLACCTLEGALLOCATION.VEREND = 99999999999) AND 
                      (PRRW.ENCOMPASS.TBLACCTLEGAL.VEREND = 99999999999) AND (PRRW.ENCOMPASS.TBLACCTREAL.VEREND = 99999999999)






