
CREATE VIEW [rw_extract].[V_TBLSALEACCT]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,RECEPTIONNO
      ,ACCOUNTNO
      ,CAST(INVENTORYEFFECTIVEDATE AS VARCHAR(22) ) INVENTORYEFFECTIVEDATE
      ,ACCTADJSALEPRICE
      ,GROUPPRIMARYACCTFLAG
      ,SALEACCTON0
      ,SALEACCTON1
      ,SALEACCTON2
      ,CAST(SALEACCTOD0 AS VARCHAR(22) ) SALEACCTOD0
      ,CAST(SALEACCTOD1 AS VARCHAR(22) ) SALEACCTOD1
      ,SALEACCTOM0
      ,SALEACCTOM1
      ,SALEACCTOT0
      ,SALEACCTOT1
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE 
      ,CAST(SALEACCTPENALTYDATE AS VARCHAR(22) ) SALEACCTPENALTYDATE
      ,SALEACCTPENALTYFLAG
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLSALEACCT T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;








