

CREATE VIEW [rw_extract].[V_TBLAPPEALACCTVALUE]
AS
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT AAV.VERSTART
      ,AAV.VEREND
      ,AAV.TAXYEAR
      ,AAV.APPEALNO
      ,AAV.ACCOUNTNO
      ,AAV.VALUEGROUPCODE
	  ,VG.VALUEGROUPDESCRIPTION
      ,AAV.ESTIMATEDVALUE
      ,AAV.INITIALREVIEWVALUE
      ,AAV.FINALREVIEWVALUE
      ,AAV.APPEALACCTVALUEON0
      ,AAV.APPEALACCTVALUEON1
      ,AAV.APPEALACCTVALUEON2
      ,AAV.APPEALACCTVALUEOD0
      ,AAV.APPEALACCTVALUEOD1
      ,AAV.APPEALACCTVALUEOM0
      ,AAV.APPEALACCTVALUEOM1
      ,AAV.APPEALACCTVALUEOT0
      ,AAV.APPEALACCTVALUEOT1
      ,AAV.JURISDICTIONID
      ,AAV.WRITEDATE
      ,AAV.SEQID
  FROM PRRW.ENCOMPASS.TBLAPPEALACCTVALUE AAV,
       PRRW.ENCOMPASS.TLKPVALUEGROUP VG
	   ,(select cast(parameter_value as numeric) verstart
                     from RW_EXTRACT.ETL_PARAMETER 
                     where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
              ,(select cast(parameter_value as numeric) verend
                     from RW_EXTRACT.ETL_PARAMETER 
                     where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where AAV.VERSTART <= p1.verstart
  and AAV.VEREND > p2.verend
  and  AAV.VALUEGROUPCODE = VG.VALUEGROUPCODE
  
  

