
CREATE VIEW [rw_extract].[V_TBLIMPSBLTAS]
AS
SELECT DETAILID
      ,T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,IMPNO
      ,BLTASCODE
      ,HVACPERCENT
      ,CLIMATE
      ,IMPEXTERIOR
      ,IMPINTERIOR
      ,BLTASSTORIES
      ,BLTASSTORYHEIGHT
      ,ROOFTYPE
      ,ROOFCOVER
      ,FLOORCOVER
      ,BLTASFOUNDATION
      ,ROOMCOUNT
      ,BEDROOMCOUNT
      ,BLTASTOTALUNITCOUNT
      ,IMPBLTASOTHER
      ,CLASSCODE
      ,DIAMETER
      ,CAPACITY
      ,BLTASHORSEPOWER
      ,BLTASHEIGHT
      ,BLTASYEARBUILT
      ,YEARREMODELED
      ,REMODELEDPERCENT
      ,EFFECTIVEAGE
      ,BLTASLENGTH
      ,BLTASWIDTH
      ,MHTAGLENGTH
      ,MHTAGWIDTH
      ,MHSKIRT
      ,MHSKIRTLINEARFEET
      ,MHWALLTYPE
      ,BLTASSF
      ,SPRINKLERSF
      ,BATHCOUNT
      ,PRIMARYBLTASORDERNO
      ,JURISDICTIONID
      ,HVACTYPE
      ,IMPSBLTASOT0
      ,IMPSBLTASOT1
      ,IMPSBLTASOM0
      ,IMPSBLTASOM1
      ,CAST(IMPSBLTASOD0 AS VARCHAR(22) ) IMPSBLTASOD0
      ,CAST(IMPSBLTASOD1 AS VARCHAR(22) ) IMPSBLTASOD1
      ,IMPSBLTASON0
      ,IMPSBLTASON1
      ,IMPSBLTASON2
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE 
      ,MHDEPRCODE
      ,MHMAKE
      ,MHMODELNAME
      ,SEQID
      ,APEXID
  FROM PRRW.ENCOMPASS.TBLIMPSBLTAS T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;







