
CREATE VIEW [rw_extract].[V_TBLIMPSOCC]
AS
SELECT DETAILID
      ,T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,IMPNO
      ,OCCCODE
      ,OCCPERCENT
      ,ABSTRACTCODE
      ,IMPABSTRACTVALUE
      ,CAST(ABSTRACTINDATE AS VARCHAR(22) ) ABSTRACTINDATE
      ,CAST(ABSTRACTOUTDATE AS VARCHAR(22) ) ABSTRACTOUTDATE 
      ,ABSTRACTADJCODE
      ,PRORATETYPE
      ,TAXDISTRICT
      ,JURISDICTIONID
      ,IMPSOCCOT0
      ,IMPSOCCOT1
      ,IMPSOCCOM0
      ,IMPSOCCOM1
      ,CAST(IMPSOCCOD0 AS VARCHAR(22) ) IMPSOCCOD0
      ,CAST(IMPSOCCOD1 AS VARCHAR(22) ) IMPSOCCOD1
      ,IMPSOCCON0
      ,IMPSOCCON1
      ,IMPSOCCON2
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,OCCCOMPLETEDPCT
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLIMPSOCC T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;








