

/****** Object:  View [ODS_EXTRACT_ASR].[V_TBLACCTPP]    Script Date: 10/30/2013 11:58:51 AM ******/


CREATE VIEW [rw_extract].[V_TBLACCTPP]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,PPCERTIFICATIONCODE
      ,CAST(PPCERTIFICATIONDATE AS VARCHAR(22) ) PPCERTIFICATIONDATE
      ,CAST(JURISDICTIONAUDITDATE AS VARCHAR(22) ) JURISDICTIONAUDITDATE
      ,CAST(NOVSENTDATE AS VARCHAR(22) ) NOVSENTDATE
      ,ASSOCIATEDREALSF
      ,PPAUDITEDBY
      ,CAST(PPDECLARATIONSENTDATE AS VARCHAR(22) ) PPDECLARATIONSENTDATE
      ,CAST(PPDECLARATIONRETURNDATE AS VARCHAR(22) ) PPDECLARATIONRETURNDATE
      ,ASSOCIATEDREALUNITCOUNT
      ,LATEDECLARATIONFLAG 
      ,CAST(PRECOLLECTDATE AS VARCHAR(22) ) PRECOLLECTDATE
      ,LETTERSENTFLAG
      ,PPAPPRAISER
      ,CAST(PPAPPRASALDATE AS VARCHAR(22) ) PPAPPRASALDATE
      ,CROPTYPE
      ,ACRESUSED
      ,FARMSERVICEAGENCYFLAG
      ,FARMSERVICEAGENCYNO
      ,NOCHANGEFLAG
      ,CAST(AUDITDATE AS VARCHAR(22) ) AUDITDATE
      ,NODECLARATIONFLAG
      ,BESTINFOAVAILABLEFLAG
      ,PPCITYCODE
      ,ATTACHMENTCOUNT
      ,SPECIALDISTRICT1
      ,SPECIALDISTRICT2
      ,AREACODEID
      ,DESKAUDITBY
      ,PPUNITTYPE
      ,APPRAISEDVALUEPERUNIT
      ,UNITNUMBER
      ,SMALLACCTCERTIFICATIONFLAG
      ,STATESALESTAXID
      ,FEDERALID
      ,ACCTPPON0
      ,ACCTPPON1
      ,ACCTPPON2
      ,ELECTRONICFILEFLAG
      ,CAST(ACCTPPOD0 AS VARCHAR(22) ) ACCTPPOD0
      ,CAST(ACCTPPOD1 AS VARCHAR(22) ) ACCTPPOD1
      ,ACCTPPOM0
      ,ACCTPPOM1
      ,ACCTPPOT0
      ,ACCTPPOT1
      ,BUSINESSCODE
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,SEQID
      ,ONLINEFILINGOPTOUTFLAG
  FROM PRRW.ENCOMPASS.TBLACCTPP T1
    ,(select cast(parameter_value as numeric) verstart
        from ASSESSOR_EXTRACT.RW_EXTRACT.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from ASSESSOR_EXTRACT.RW_EXTRACT.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;









