


/****** Object:  View [rw_extract].[V_TBLAPPEALACCT]    Script Date: 10/30/2013 11:58:51 AM ******/


CREATE VIEW [rw_extract].[V_TBLAPPEALACCT]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,T1.TAXYEAR
      ,T1.APPEALNO
      ,T1.ACCOUNTNO
      ,T1.APPEALADJUSTDENYREASONID
      ,T1.APPEALCOMMENT
      ,AAV.FINALREVIEWVALUE APPEALACCOUNTENDVALUE
	  ,AAV.VALUEGROUPDESCRIPTION
      ,T1.APPEALACCTON0
      ,T1.APPEALACCTON1
      ,T1.APPEALACCTON2
      ,CAST(T1.APPEALACCTOD0 AS VARCHAR(22) ) APPEALACCTOD0
      ,CAST(T1.APPEALACCTOD1 AS VARCHAR(22) ) APPEALACCTOD1
      ,T1.APPEALACCTOM0
      ,T1.APPEALACCTOM1
      ,T1.APPEALACCTOT0
      ,T1.APPEALACCTOT1
      ,T1.JURISDICTIONID
      ,CAST(T1.WRITEDATE AS VARCHAR(22) )  WRITEDATE
      ,T1.BEGINNINGACCOUNTVALUE
      ,T1.APPEALDECISION
      ,T1.APPEALACCTREASONDESC
      ,T1.ADDBOARDAPPEALENDVALUE
      ,T1.SEQID
from PRRW.ENCOMPASS.TBLAPPEALACCT T1
    LEFT OUTER JOIN [rw_extract].[V_TBLAPPEALACCTVALUE] AAV 
		ON  T1.ACCOUNTNO = AAV.ACCOUNTNO 
		AND T1.APPEALNO = AAV.APPEALNO 
		AND T1.TAXYEAR = AAV.TAXYEAR
     --JOIN PRRW.ENCOMPASS.TBLAPPEALACCTVALUE AAV ON AAV.APPEALNO = T1.APPEALNO AND AAV.ACCOUNTNO = T1.ACCOUNTNO
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where t1.verend = 99999999999
  --and T1.VERSTART <= p1.verstart
  --and T1.VEREND > p2.verend;
  



