
CREATE VIEW [rw_extract].[V_TBLACCTLEGALLOCATION]
AS
SELECT        VERSTART, VEREND, ACCOUNTNO, DETAILID, QTRQTR, QTR, SECTION, TOWNSHIP, RANGE, GOVERNMENTLOT, GOVERNMENTTRACT, LEGALCOMMENT, ACCTLEGALLOCATIONON0, ACCTLEGALLOCATIONON1, 
                         ACCTLEGALLOCATIONON2, ACCTLEGALLOCATIONOD0, ACCTLEGALLOCATIONOD1, ACCTLEGALLOCATIONOM0, ACCTLEGALLOCATIONOM1, ACCTLEGALLOCATIONOT0, ACCTLEGALLOCATIONOT1, 
                         JURISDICTIONID, WRITEDATE, SEQID
FROM            PRRW.ENCOMPASS.TBLACCTLEGALLOCATION
WHERE        (VERSTART < CONVERT(VARCHAR, GETDATE(), 112) + '999') AND (VEREND >= CONVERT(VARCHAR, GETDATE(), 112) + '999')





