







CREATE VIEW [rw_extract].[V_TBNSUBFILING]
AS
SELECT SUBNO
      ,FILINGNO
      ,SUBFILINGDESCRIPTION
      ,SUBFILINGRECORDINGNO
      ,SUBFILINGCITY
      ,DEFAULTSECTION
      ,DEFAULTTOWNSHIP
      ,DEFAULTRANGE
      ,DEFAULTQTR
      ,DEFAULTQTRQTR
      ,CAST(SUBFILINGDATERECORDED AS VARCHAR(22) ) SUBFILINGDATERECORDED
      ,DEFAULTLEA
      ,DEFAULTTAXDISTRICT
      ,MAPNO
      ,ECONOMICAREACODE
      ,ACCOUNTTYPE
      ,LANDCERTIFICATIONCODE
      ,FLAGTYPE
      ,SUBFILINGSTATUS
      ,DEFAULTAPPROACHTYPE
      ,VALUEAREACODE
      ,ZONINGCODE
      ,BLOCKCOUNT
      ,LOTCOUNT
      ,TRACTCOUNT
      ,SUBFILINGMHTITLEFLAG
      ,SUBFILINGNOTESFLAG
      ,SUBFILINGNEWCONSTFLAG
      ,SUBFILINGPHOTOSFLAG
      ,SUBFILINGSKETCHESFLAG
      ,SUBFILINGTAXYEAR
      ,SUBFILINGON0
      ,SUBFILINGON1
      ,SUBFILINGON2
      ,ASSIGNEDTO
      ,CAST(SUBFILINGOD0 AS VARCHAR(22) ) SUBFILINGOD0
      ,CAST(SUBFILINGOD1 AS VARCHAR(22) ) SUBFILINGOD1
      ,SUBFILINGOM0
      ,SUBFILINGOM1
      ,SUBFILINGOT0
      ,SUBFILINGOT1
      ,JURISDICTIONID
      ,CAST(DEFAULTLEGAL AS VARCHAR(4000) ) DEFAULTLEGAL
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,PRIMARYUSECODE
      ,APPRAISALTYPE
  FROM PRRW.ENCOMPASS.TBNSUBFILING;






