
CREATE VIEW [rw_extract].[V_TBLLANDABSTRACT_OLD]
AS
SELECT ACCOUNTNO
      ,T1.VERSTART
      ,T1.VEREND
      ,LANDTYPE
      ,ABSTRACTCODE
      ,LANDACRES
      ,LANDSF
      ,LANDFF
      ,LANDUNITCOUNT
      ,LANDVALUEPER
      ,LANDVALUE
      ,LANDOVERRIDEFLAG
      ,LANDOVERRIDETOTAL
      ,LANDACTUALTOTAL
      ,LANDCLASS
      ,LANDSUBCLASS
      ,LANDVALUEBY
      ,LANDVALUEMEASURE
      ,CAST(ABSTRACTINDATE AS VARCHAR(22) ) ABSTRACTINDATE
      ,CAST(ABSTRACTOUTDATE AS VARCHAR(22) ) ABSTRACTOUTDATE 
      ,PRORATETYPE
      ,LANDACTIVEFLAG
      ,DETAILID
      ,ABSTRACTADJCODE
      ,LANDVALUEPERADJFACTOR
      ,ATTRIBUTEADJFLAG
      ,LANDADJSIZE
      ,LANDOVERRIDEADJSIZE
      ,LANDABSTRACTON0
      ,LANDABSTRACTON1
      ,LANDABSTRACTON2
      ,LANDOVERRIDEVALUEPER
      ,TAXDISTRICT
      ,CAST(LANDABSTRACTOD0 AS VARCHAR(22) ) LANDABSTRACTOD0
      ,CAST(LANDABSTRACTOD1 AS VARCHAR(22) ) LANDABSTRACTOD1
      ,LANDABSTRACTOM0
      ,LANDABSTRACTOM1
      ,LANDABSTRACTOT0
      ,LANDABSTRACTOT1
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,MSALANDVALUE
      ,MSALANDVALUEPER
      ,LEA
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLLANDABSTRACT T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;








