


/****** Object:  View [ODS_EXTRACT_ASR].[V_TBLACCTPROPERTYADDRESS]    Script Date: 10/30/2013 11:58:51 AM ******/


CREATE VIEW [rw_extract].[V_TBLACCTPROPERTYADDRESS]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,T1.ACCOUNTNO
      ,T1.BUILDINGID
      ,T1.PREDIRECTION
      ,STREETNO
      ,UNITNAME
      ,POSTDIRECTION
      ,STREETTYPE
      ,STREETNAME
      ,PROPERTYZIPCODE
      ,PROPERTYCITY
      ,ORDERNO
      ,ACCTPROPERTYADDRESSON0
      ,ACCTPROPERTYADDRESSON1
      ,ACCTPROPERTYADDRESSON2
      ,T1.BUSINESSNAME
      ,CAST(ACCTPROPERTYADDRESSOD0 AS VARCHAR(22) ) ACCTPROPERTYADDRESSOD0
      ,CAST(ACCTPROPERTYADDRESSOD1 AS VARCHAR(22) ) ACCTPROPERTYADDRESSOD1
      ,ACCTPROPERTYADDRESSOM0
      ,ACCTPROPERTYADDRESSOM1
      ,ACCTPROPERTYADDRESSOT0
      ,ACCTPROPERTYADDRESSOT1
      ,T1.JURISDICTIONID
      ,PROPERTYADDRESSCODE
      ,CAST(T1.WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,LOCATIONID
      ,T1.SEQID
  FROM PRRW.ENCOMPASS.TBLACCTPROPERTYADDRESS T1
        , PRRW.ENCOMPASS.TBLACCT A
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend
  and A.accountno = T1.accountno
  and A.VERSTART <= p1.verstart
  and A.VEREND > p2.verend;











