

CREATE VIEW [rw_extract].[V_TBNSALEINVENTORY]
AS
SELECT RECEPTIONNO
      ,ACCOUNTNO
      ,PARCELNO
      ,CAST(INVENTORYEFFECTIVEDATE AS VARCHAR(22) ) INVENTORYEFFECTIVEDATE
      ,CAST(SALEDATE AS VARCHAR(22) ) SALEDATE
      ,SALEPRICE
      ,ADJSALEPRICE
      ,SALEVALUEPER
      ,ACCTTYPE
      ,ECONOMICAREACODE
      ,LEA
      ,SUBDIVISION
      ,VALUEAREACODE
      ,PROPERTYTYPE
      ,IMPCONDITIONTYPE
      ,IMPQUALITY
      ,IMPABSTRACTCODE
      ,BLTASDESCRIPTION
      ,BLTASYEARBUILT
      ,PHYSICALAGE
      ,ADJUSTEDYEARBUILT
      ,EFFECTIVEAGE
      ,IMPEXTERIOR
      ,CLASSCODE
      ,IMPCOUNT
      ,BLTASTOTALUNITCOUNT
      ,ROOMCOUNT
      ,BEDROOMCOUNT
      ,BATHCOUNT
      ,FIXTURECOUNT
      ,TOTALIMPSF
      ,RESIDENTIALSF
      ,COMMERCIALSF
      ,CONDOIMPSF
      ,OUTBUILDINGSF
      ,IMPBLTASOTHER
      ,LANDNETSF
      ,MULTIPLEUSEFLAG
      ,LANDTYPE
      ,LANDABSTRACTCODE
      ,LANDCERTIFICATIONCODE
      ,LANDGROSSACRECOUNT
      ,LANDGROSSSF
      ,LANDGROSSFF
      ,LANDGROSSUNITCOUNT
      ,ZONINGCODE
      ,PLATTEDFLAG
      ,UNITNAME
      ,ACCTADJSALEVALUEPER
     ,TOTALLANDVALUETIMEOFSALE
      ,TOTALACCTVALUETIMEOFSALE
      ,PRIORYEARTAXROLLACTUALAMT
      ,PRIORYEARTAXROLLASSESSED
      ,LANDNETACRECOUNT
      ,HVACTYPE
      ,IMPUNITTYPE
      ,IMPINTERIOR
      ,ROOFCOVER
      ,ROOFTYPE
      ,INVENTORYOVERRIDEFLAG
      ,ZONEDAREA
      ,NBHDCODE1
      ,NBHDCODE2
      ,NBHDCODE3
      ,NBHDCODE4
      ,NBHDEXTENSION1
      ,NBHDEXTENSION2
      ,NBHDEXTENSION3
      ,NBHDEXTENSION4
      ,OCCCODE1
      ,OCCCODE2
      ,OCCCODE3
      ,ACCTADJSALEPRICE
      ,TIMEADJSALEPRICE
      ,DEEDCODE
      ,VALID1FLAG
      ,VALID2FLAG
      ,EXCLUDECODE1
      ,EXCLUDECODE2
      ,IMPROVEDFLAG
      ,CONFIRMEDFLAG
      ,BUSINESSNAME
      ,STREETNO
      ,PREDIRECTION
      ,STREETNAME
      ,STREETTYPE
      ,POSTDIRECTION
      ,PROPERTYCITY
      ,PROPERTYZIPCODE
      ,OUTBUILDINGCOUNT
      ,LANDEXCESSSF
      ,APPROACHTYPE
      ,FLOORCOVER
      ,CONDOIMPPERCENT
      ,FINALSF
      ,FINALSFVALUEPER
      ,ZONEDAREAVALUEPER
      ,GROUPINVENTORYFLAG
      ,GRANTORNAME1
      ,GRANTORNAME2
      ,GRANTORADDRESS1
      ,GRANTORADDRESS2
      ,GRANTORCITY
      ,GRANTORSTATECODE
      ,GRANTORZIPCODE
      ,SUBDIVISIONNAME
      ,LOT
      ,BLOCK
      ,FILINGNO
      ,TRACT
      ,LEGALDESCRIPTION
      ,GRANTEENAME1
      ,GRANTEENAME2
      ,GRANTEEADDRESS1
      ,GRANTEEADDRESS2
      ,GRANTEECITY
      ,GRANTEESTATECODE
      ,GRANTEEZIPCODE
      ,SALEINVENTORYON0
      ,SALEINVENTORYON1
      ,SALEINVENTORYON2
      ,OCCCODEDESCRIPTION1
      ,OCCCODEDESCRIPTION2
      ,OCCCODEDESCRIPTION3
      ,CAST(SALEINVENTORYOD0 AS VARCHAR(22) ) SALEINVENTORYOD0
      ,CAST(SALEINVENTORYOD1 AS VARCHAR(22) ) SALEINVENTORYOD1
      ,SALEINVENTORYOM0
      ,SALEINVENTORYOM1
      ,SALEINVENTORYOT0
      ,SALEINVENTORYOT1
      ,LANDNETFF
      ,JURISDICTIONID
      ,OUTOFAREASALEJURISDICTION
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,GRANTEEPROVINCE
      ,GRANTEECOUNTRY
      ,GRANTEEPOSTALCODE
      ,OCCCOMPLETEDPCT
      ,PRIMARYUSECODE
      ,GRANTORPROVINCE
      ,GRANTORCOUNTRY
      ,GRANTORPOSTALCODE
      ,LANDNETUNITCOUNT
      ,TOTALFINISHEDSF
      ,TOTALUNFINISHEDSF
      ,BLTASCODE
      ,SALERATIO
  FROM PRRW.ENCOMPASS.TBNSALEINVENTORY;









