

/****** Object:  View [ODS_EXTRACT_ASR].[V_TBLACCTNEWCONSTRUCTION]    Script Date: 10/30/2013 11:58:51 AM ******/


CREATE VIEW [rw_extract].[V_TBLACCTNEWCONSTRUCTION]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,DETAILID
      ,NCTOTALACTUALVALUE
      ,T1.TAXYEAR
      ,ABSTRACTCODE
      ,ABSTRACTADJCODE
      ,TAXDISTRICT
      ,ACCTNEWCONSTRUCTIONON0
      ,ACCTNEWCONSTRUCTIONON1
      ,ACCTNEWCONSTRUCTIONON2
      ,CAST(ACCTNEWCONSTRUCTIONOD0  AS VARCHAR(22) ) ACCTNEWCONSTRUCTIONOD0 
      ,CAST(ACCTNEWCONSTRUCTIONOD1  AS VARCHAR(22) ) ACCTNEWCONSTRUCTIONOD1
      ,ACCTNEWCONSTRUCTIONOM0
      ,ACCTNEWCONSTRUCTIONOM1
      ,ACCTNEWCONSTRUCTIONOT0
      ,ACCTNEWCONSTRUCTIONOT1
      ,LANDCLASS
      ,LANDSUBCLASS
      ,JURISDICTIONID
      ,CAST(WRITEDATE  AS VARCHAR(22) ) WRITEDATE 
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLACCTNEWCONSTRUCTION T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
    ,(SELECT  cast(parameter_value AS numeric(11,0)) taxyear
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASSESSMENT_TAX_YEAR') TY      
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend
  and T1.taxyear = TY.taxyear;









