



CREATE VIEW [rw_extract].[V_TBNSALEINVENTORYDETAIL]
AS
SELECT RECEPTIONNO
      ,ACCOUNTNO
      ,DETAILTYPE
      ,INVENTORYDETAILTYPE
      ,INVENTORYDETAILDESCRIPTION
      ,INVENTORYUNITCOUNT
      ,SALEINVENTORYDETAILON0
      ,SALEINVENTORYDETAILON1
      ,SALEINVENTORYDETAILON2
      ,CAST(SALEINVENTORYDETAILOD0 AS VARCHAR(22) ) SALEINVENTORYDETAILOD0
      ,CAST(SALEINVENTORYDETAILOD1 AS VARCHAR(22) ) SALEINVENTORYDETAILOD1
      ,SALEINVENTORYDETAILOM0
      ,SALEINVENTORYDETAILOM1
      ,SALEINVENTORYDETAILOT0
      ,SALEINVENTORYDETAILOT1
      ,YEARBUILT
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,INVENTORYDETAILID
  FROM PRRW.ENCOMPASS.TBNSALEINVENTORYDETAIL;








