
CREATE VIEW [rw_extract].[V_TBLIMPS]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,IMPNO
      ,IMPDESCRIPTION
      ,COSTVALUEBY
      ,MARKETVALUEBY
      ,INCOMEVALUEBY
      ,LANDATTRIBUTEDPCT
      ,IMPCOMPLETEDPCT
      ,IMPQUALITY
      ,IMPUNITTYPE
      ,IMPDESIGNADJPCT
      ,IMPEXTERIORADJPCT
      ,IMPPHYSICALDEPRPCT
      ,FUNCTIONALOBSOLESCEPCT
      ,ECONOMICOBSOLESCEPCT
      ,IMPOTHERADJPCT
      ,MHTITLENO
      ,MHSERIALNO
      ,MHTOTALLENGTH
      ,MHDECALNO
      ,MHTAGNO
      ,APPRAISER
      ,CAST(APPRAISALDATE AS VARCHAR(22) ) APPRAISALDATE
      ,OWNEROCCUPIEDFLAG
      ,COSTMETHOD
      ,MARKETMETHOD
      ,INCOMEMETHOD
      ,IMPCONDITIONTYPE
      ,CONDOLANDPERCENT
      ,IMPSF
      ,CONDOIMPPERCENT
      ,IMPPERIMETER
      ,IMPINTERIORADJPCT
      ,CONDOIMPSF
      ,IMPAMATEURADJPCT
      ,IMPNETSF
      ,PROPERTYTYPE
      ,APPROACHTYPE
      ,JURISDICTIONID
      ,IMPSOT0
      ,IMPSOT1
      ,IMPSOM0
      ,IMPSOM1
      ,CAST(IMPSOD0 AS VARCHAR(22) ) IMPSOD0
      ,CAST(IMPSOD1 AS VARCHAR(22) ) IMPSOD1
      ,IMPSON0
      ,IMPSON1
      ,IMPSON2
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE 
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLIMPS T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;








