



CREATE VIEW [rw_extract].[V_TBLLANDATTRIBUTE]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,DETAILID
      ,ATTRIBUTETYPE
      ,ATTRIBUTESUBTYPE
      ,ATTRIBUTEADJUSTMENT
      ,FILTERTYPE
      ,LANDATTRIBUTEOT0
      ,LANDATTRIBUTEOT1
      ,LANDATTRIBUTEON0
      ,LANDATTRIBUTEON1
      ,LANDATTRIBUTEON2
      ,CAST(LANDATTRIBUTEOD0 AS VARCHAR(22) ) LANDATTRIBUTEOD0
      ,CAST(LANDATTRIBUTEOD1 AS VARCHAR(22) ) LANDATTRIBUTEOD1
      ,LANDATTRIBUTEOM0
      ,LANDATTRIBUTEOM1
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLLANDATTRIBUTE T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;











