
CREATE VIEW [rw_extract].[V_TBNSUBDIVISION]
AS
SELECT SUBNO
      ,SUBNAME
      --,CAST(SUBDATEALTERD AS VARCHAR(22) ) SUBDATEALTERD
      ,SUBON2
      ,SUBOT0
      ,SUBOT1
      ,CAST(SUBOD0 AS VARCHAR(22) ) SUBOD0
      ,CAST(SUBOD1 AS VARCHAR(22) ) SUBOD1
      ,SUBOM0
      ,SUBOM1
      ,SUBON0
      ,SUBON1
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
  FROM PRRW.ENCOMPASS.TBNSUBDIVISION;






