



CREATE VIEW [rw_extract].[V_TBLACCTREAL]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,IMPONLYFLAG
      ,TIFFLAG
      ,VACANTFLAG
      ,LANDWIDTH
      ,LANDDEPTH
      ,LANDEASEMENTSF
      ,LANDEXCESSSF
      ,TRAFFICCOUNT
      ,PARKINGSPACES
      ,ZONINGCODE
      ,FLOODFRINGE
      ,FLOODWAY
      ,TAPFEE
      ,PLATTEDFLAG
      ,LANDCERTIFICATIONCODE
      ,LANDAPPRAISER
      ,CAST(LANDAPPRAISALDATE AS VARCHAR(22) ) LANDAPPRAISALDATE
      ,LANDOVERRIDESIZEADJ
      ,LANDSIZEADJ
      ,LANDGROSSSF
      ,LANDGROSSACRES
      ,LANDGROSSFF
      ,LANDGROSSUNITCOUNT
      ,ACCTREALON0
      ,ACCTREALON1
      ,ACCTREALON2
      ,CAST(ACCTREALOD0 AS VARCHAR(22) ) ACCTREALOD0
      ,CAST(ACCTREALOD1 AS VARCHAR(22) ) ACCTREALOD1
      ,ACCTREALOM0
      ,ACCTREALOM1
      ,ACCTREALOT0
      ,ACCTREALOT1
      ,JURISDICTIONID
      ,DEFAULTLEA
      ,TOTALACCTIMPINTERESTPCT
      ,TOTALACCTLANDINTERESTPCT
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLACCTREAL T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;








