

CREATE VIEW [rw_extract].[V_TBLACCTPPDETAIL]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,DETAILID
      ,PPRECORDNO
      ,ABSTRACTCODE
      ,ABSTRACTADJCODE
      ,TAXDISTRICT
      ,PPOGTYPE
      ,PPOGDESCRIPTIONTYPEID
      ,ACQUISITIONYEAR
      ,PPAGE
      ,PPQUANTITY
      ,TYPEFACTOR
      ,ORIGINALCOST
      , null as PPMETHODCODE --removed in rw v5131
      ,PPLIFEEXPECTANCY
      ,PPCONDITIONCODE
      ,PPGOODPERCENT
      ,PERCENTADDEDDEPRECIATION
      ,ROLLBACKFACTOR
      ,PPABSTRACTVALUE
      ,BESTINFOAVAILABLEFLAG
      ,OMITTEDFLAG
      ,DEPRECIATIONVALUE
      --,ECONOMICOBSOLESCENCEPERCENT
      --,ECONOMICOBSOLESCENCEVALUE
      --,FUNCTIONALOBSOLESCENCEPCT
      --,FUNCTIONALOBSOLESCENCEVALUE
      --,OTHEROBSOLESCENCEPERCENT
      --,OTHEROBSOLESCENCEVALUE
      ,REPORTEDACQUIREDYEAR
      ,REPORTEDACQUIREDCOST
      ,PPREPORTEDRECORDNO
      ,PPMAKE
      ,PPMODEL
      ,PPLEASETERM
      ,PPMONTHLYRENT
      ,PPLESSORCODE
      --,ACCTPPDETAILON0
      --,ACCTPPDETAILON1
      --,ACCTPPDETAILON2
      --,CAST(ACCTPPDETAILOD0 AS VARCHAR(22) ) ACCTPPDETAILOD0
      --,CAST(ACCTPPDETAILOD1 AS VARCHAR(22) ) ACCTPPDETAILOD1
      --,ACCTPPDETAILOM0
      --,ACCTPPDETAILOM1
      --,ACCTPPDETAILOT0
      --,ACCTPPDETAILOT1
      ,PPDETAILDESCRIPTION
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,APPRAISALTYPE
      ,SEQID
  FROM PRRW.ENCOMPASS.TBLACCTPPDETAIL T1
    ,(select cast(parameter_value as numeric) verstart
        from RW_EXTRACT.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from RW_EXTRACT.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend








