

CREATE VIEW [rw_extract].[V_TBLACCTOWNERADDRESS]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,T1.ACCOUNTNO
      ,T1.PERSONCODE
      ,T1.ADDRESSCODE
      ,PRIMARYOWNERFLAG
      ,ACCTOWNERADDRESSON0
      ,ACCTOWNERADDRESSON1
      ,ACCTOWNERADDRESSON2
      ,CAST(ACCTOWNERADDRESSOD0 AS VARCHAR(22) ) ACCTOWNERADDRESSOD0
      ,CAST(ACCTOWNERADDRESSOD1 AS VARCHAR(22) ) ACCTOWNERADDRESSOD1
      ,ACCTOWNERADDRESSOM0
      ,ACCTOWNERADDRESSOM1
      ,ACCTOWNERADDRESSOT0
      ,ACCTOWNERADDRESSOT1
      ,T1.JURISDICTIONID
      ,T1.OWNERPERCENT
      ,CAST(T1.WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,T1.SEQID
      ,OWNERSHIPTYPE
  FROM PRRW.ENCOMPASS.TBLACCTOWNERADDRESS T1, 
       PRRW.ENCOMPASS.TBLACCT A 
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend
  and A.accountno = T1.accountno
  and A.VERSTART <= p1.verstart
  and A.VEREND > p2.verend; 








