
CREATE VIEW [rw_extract].[V_TBLSALE]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,RECEPTIONNO
      ,BOOK
      ,PAGE
      ,GRANTOR
      ,GRANTEE
      ,CAST(DOCUMENTDATE AS VARCHAR(22) ) DOCUMENTDATE
      ,CAST(SALEDATE AS VARCHAR(22) ) SALEDATE
      ,DOCUMENTFEE
      ,DEEDCODE
      ,PENALTYFLAG
      ,CAST(PENALTYDATE AS VARCHAR(22) ) PENALTYDATE
      ,SALEPRICE
      ,PPADJAMOUNT
      ,GOODWILLADJAMOUNT
      ,OTHERADJAMOUNT
      ,TIMEADJ
      ,DOWNPAYMENTAMOUNT
      ,DOWNPAYMENTPCT
      ,NOTEAMOUNT
      ,INTERESTRATEPCT
      ,LOANTERM
      ,POINTSPAID
      ,POINTSPAIDBY
      ,LOANINSTITUTION
      ,MKTRATEPCT
      ,PAYMENTAMOUNT
      ,RECOURSEFLAG
      ,TENANT
      ,VALID1FLAG
      ,VALID2FLAG
      ,CONFIRMEDFLAG
      ,EXCLUDECODE1
      ,EXCLUDECODE2
      ,IMPROVEDFLAG
      ,CONFIRMBY
      ,CONFIRMMETHOD
      ,CAST(CONFIRMDATE AS VARCHAR(22) ) CONFIRMDATE
      ,COMMENTS
      ,NONSALEFLAG
      ,SALEON0
      ,SALEON1
      ,SALEON2
      ,CAST(SALEOD0 AS VARCHAR(22) ) SALEOD0
      ,CAST(SALEOD1 AS VARCHAR(22) ) SALEOD1
      ,SALEOM0
      ,SALEOM1
      ,SALEOT0
      ,SALEOT1
      ,JURISDICTIONID
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,BALLOONPAYMENTYEAR
      ,TRANSFERDECLARATIONFLAG
      ,CAST(TRANSFERDECLARATIONDATE AS VARCHAR(22) ) TRANSFERDECLARATIONDATE
      ,CAST(QUESTIONNAIREMAILDATE AS VARCHAR(22) ) QUESTIONNAIREMAILDATE
      ,CAST(QUESTIONNAIRERETURNDATE AS VARCHAR(22) ) QUESTIONNAIRERETURNDATE
      ,SEQID
        FROM PRRW.ENCOMPASS.TBLSALE T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;











