CREATE VIEW [rw_extract].[V_TBLACCT]
AS
SELECT T1.VERSTART
      ,T1.VEREND
      ,ACCOUNTNO
      ,PARCELNO
      ,LOCALNO
      ,MAPNO
      ,ACCTSTATUSCODE
      ,ACCTTYPE
      ,ASSIGNEDTO
      ,VALUEAREACODE
      ,ASSOCIATEDACCT
      ,APPRAISALTYPE
      ,ECONOMICAREACODE
      --,CAST(ACCTDATEALTERD AS VARCHAR(22) ) ACCTDATEALTERD
      ,DEFAULTAPPROACHTYPE
      ,DEFAULTTAXDISTRICT
      ,BUSINESSLICENSE
      ,MAPGROUP
      ,CONTROLMAP
      ,PROPERTYIDENTIFIER
      ,SPECIALINTERESTNUMBER
      ,ACCTON0
      ,ACCTON1
      ,ACCTON2
      ,PRIMARYUSECODE
      ,WARD
      ,CAST(ACCTOD0 AS VARCHAR(22) ) ACCTOD0
      ,CAST(ACCTOD1 AS VARCHAR(22) ) ACCTOD1
      ,ACCTOM0
      ,ACCTOM1
      ,STRIPPEDACCOUNTNO
      ,JURISDICTIONID
      ,ACCTOT0
      ,ACCTOT1
      ,CAST(WRITEDATE AS VARCHAR(22) ) WRITEDATE
      ,CENSUSTRACT
      ,CENSUSBLOCK
      ,MOBILEHOMESPACE
      ,EFILEFLAG
      ,BUSINESSNAME
      ,COSTHYBRIDPERCENT
      ,MARKETHYBRIDPERCENT
      ,INCOMEHYBRIDPERCENT
      ,RECONCILEDHYBRIDPERCENT
      ,PARCELSEQUENCE
      ,PROPERTYCLASSID
      ,SEQID
      ,CAST(DETAILEDREVIEWDATE  AS VARCHAR(22) ) DETAILEDREVIEWDATE
  FROM PRRW.ENCOMPASS.TBLACCT T1
    ,(select cast(parameter_value as numeric) verstart
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_START_DATE' ) p1
    ,(select cast(parameter_value as numeric) verend
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASR_EXTRACT_VERSION_END_DATE' ) p2
where T1.VERSTART <= p1.verstart
  and T1.VEREND > p2.verend;  











