

CREATE VIEW [rw_extract].[V_TLKPABSTRACTCODE]
AS   
SELECT ABSTRACTCODE
      ,ABSTRACTDESCRIPTION
      ,EQUIVALENCEABSTRACTCODE
      ,ROLLABSTRACTVALUEFLAG
      ,VALUEGROUPCODE
      ,ACTUALPRECISION
      ,ACTUALMINIMUMVALUE
      ,ASSESSEDPRECISION
      ,ASSESSEDMINIMUMVALUE
      ,ACTUALROUNDTYPE
      ,ASSESSEDROUNDTYPE
      ,USEVALUEFLAG
      ,ADJACTUALPRECISION
      ,ADJACTUALMINIMUMVALUE
      ,ADJACTUALROUNDTYPE
      ,ADJASSESSEDPRECISION
      ,ADJASSESSEDMINIMUMVALUE
      ,ADJASSESSEDROUNDTYPE
      ,ADJALTACTUALPRECISION
      ,ADJALTACTUALMINVALUE
      ,ADJALTACTUALROUNDTYPE
      ,ADJALTASSESSEDPRECISION
      ,ADJALTASSESSEDMINVALUE
      ,ADJALTASSESSEDDROUNDTYPE
      ,ALTASSESSEDPRECISION
      ,ALTASSESSEDMINIMUMVALUE
      ,ALTASSESSEDROUNDTYPE
      ,SHOWADMINFLAG
      ,CLASSIFICATIONID
      ,LOCALGROWTHEXEMPTFLAG
      ,EXPORTCNTGROUPEXCLUSIONFLAG
      ,SORTORDER
      ,ACTIVEFLAG
      ,LIMITTOABSTTYPE
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,ABSTRACTCATEGORYCODE 
FROM PRRW.ENCOMPASS.TLKPABSTRACTCODE;








