

CREATE VIEW [rw_extract].[V_TLKPTAXFUND]
AS
SELECT FUNDCODE
      ,FUNDDESCRIPTION
      ,SORTORDER
      ,ACTIVEFLAG
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
FROM PRRW.ENCOMPASS.TLKPTAXFUND;




