
CREATE VIEW [rw_extract].[V_TLKPIMPSCOMCLASSTYPE]
AS
SELECT CLASSCODE
      ,CLASSDESCRIPTION
      ,SORTORDER
      ,ACTIVEFLAG
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
  FROM PRRW.ENCOMPASS.TLKPIMPSCOMCLASSTYPE;





