

CREATE VIEW [rw_extract].[V_TLKPLANDATTRIBUTETYPE]
AS
SELECT ATTRIBUTETYPE
      ,ATTRIBUTESUBTYPE
      ,ATTRIBUTEADJUSTMENT
      ,FILTERTYPE
      ,ACTIVEFLAG
      ,USEINANALYSISFLAG
      ,JURISDICTIONID
      ,SORTORDER
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,EXECUTIONORDER
      ,NULL ADJUSTMENTCALCULATIONTYPE -- ADD NULL for RW 5.15
FROM PRRW.ENCOMPASS.TLKPLANDATTRIBUTETYPE ;

