


CREATE VIEW [rw_extract].[V_TLKPABSTRACTCODEVALUE]
AS
SELECT ABSTRACTCODE
      ,T1.TAXYEAR
      ,ASSESSMENTRATIO
      ,ALTERNATEASSESSMENTRATIO
      ,ROLLVALUEGROUPFLAG
      ,SORTORDER
      ,ACTIVEFLAG
      ,CAPFLAG
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
FROM PRRW.ENCOMPASS.TLKPABSTRACTCODEVALUE  T1
    ,(SELECT  cast(parameter_value AS numeric(4,0)) taxyear 
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASSESSMENT_TAX_YEAR' ) P1
WHERE T1.TAXYEAR = p1.taxyear ;








