
/****** Object:  View [ODS_EXTRACT_ASR].[V_TLKPPPCONDITION]    Script Date: 10/30/2013 11:58:51 AM ******/





CREATE VIEW [rw_extract].[V_TLKPPPCONDITION]
AS
SELECT PPCONDITIONCODE
      ,PPCONDITIONDESCRIPTION
      ,ACTIVEFLAG
      ,SORTORDER
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED 
FROM PRRW.ENCOMPASS.TLKPPPCONDITION ;








