

CREATE VIEW [rw_extract].[V_TLKPTAXDISTRICT]
AS
SELECT TAXDISTRICT
      ,TAXDISTRICTNAME
      ,TAXAREA
      ,CAST(CREATIONDATE AS VARCHAR(22) ) CREATIONDATE
      ,SORTORDER
      ,ACTIVEFLAG
      ,JURISDICTIONID
      ,TAXDISTRICTCATEGORY
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,TAXDISTRICTTYPE
      ,TAXDISTRICTID
      ,ASSOCIATEDURBANRENEWALPLAN
      ,REPORTINGTAXDISTRICT 
FROM PRRW.ENCOMPASS.TLKPTAXDISTRICT;






