

CREATE VIEW [rw_extract].[V_TLKPVALUEGROUP]
AS
SELECT [VALUEGROUPCODE],
       [VALUEGROUPDESCRIPTION],
       [VALUECODE],
       [SORTORDER],
       [ACTIVEFLAG],
       [JURISDICTIONID],
       CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED,
       [SUPPLEMENTALBILLTYPEID]
  FROM PRRW.ENCOMPASS.TLKPVALUEGROUP;






