CREATE VIEW [rw_extract].[V_TLKPDEEDTYPE]
AS
SELECT DEEDCODE
      ,DEEDDESCRIPTION
      ,SORTORDER
      ,ACTIVEFLAG
      ,EFFECTEXEMPTIONSFLAG
      ,EFFECTCAPFLAG
      ,INCLUDEINSALESRATIOSFLAG
      ,JURISDICTIONID
      ,NONSALEFLAG
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED  
FROM PRRW.ENCOMPASS.TLKPDEEDTYPE ;








