
/****** Object:  View [ODS_EXTRACT_ASR].[V_TLKPPPOGDESCRIPTIONTYPE]    Script Date: 10/30/2013 11:58:51 AM ******/



CREATE VIEW [rw_extract].[V_TLKPPPOGDESCRIPTIONTYPE]
AS
SELECT PPOGDESCRIPTIONTYPEID
      ,PPOGDESCRIPTIONTYPE
      ,DEFAULTABSTRACTCODE
      ,DEFAULTPPTYPE
      ,SORTORDER
      ,APPRAISALTYPE
      ,PPOGDETAILTYPE
      ,ACCTTYPE
      ,ACTIVEFLAG
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
from PRRW.ENCOMPASS.TLKPPPOGDESCRIPTIONTYPE T1;








