
CREATE VIEW [rw_extract].[V_TLKPTAXAUTHORITYDETAIL]
AS
SELECT TAXAUTHORITY
      ,T1.TAXYEAR
      ,NETASSESSED
      ,GROSSASSESSED
      ,TIFDISTRICTINCREMENT
      ,NEWCONSTRUCTION
      ,PRODUCINGMINEINCREMENT
      ,ANNEXINCLUSIONS
      ,PREVIOUSEXEMPTFEDERAL
      ,NEWPRIMARYOIL
      ,TAXOMITTEDPROPERTY
      ,TAXESABATEDREFUNDED
      ,REALACTUALVALUE
      ,REALNEWCONSTACTUALVALUE
      ,NEWANNEXACTUALVALUE
      ,PRODUCINGMINEACTUALVALUE
      ,PREVIOUSEXEMPTACTUALVALUE
      ,NEWWELLPRODUCINGACTUALVALUE
      ,REALOMITTEDACTUALVALUE
      ,REALDESTROYEDACTUALVALUE
      ,DISCONNECTEXCLACTUALVALUE
      ,PREVIOUSTAXACTUALVALUE
      ,GROSSACTUALVALUE
      ,ACTIVEFLAG
      ,SORTORDER
      ,JURISDICTIONID
      ,MAXASSESSEDMILLLEVY
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
FROM PRRW.ENCOMPASS.TLKPTAXAUTHORITYDETAIL  T1
    ,(SELECT  cast(parameter_value AS numeric(4,0)) taxyear 
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASSESSMENT_TAX_YEAR' ) P1
WHERE T1.TAXYEAR = p1.taxyear;






