
CREATE VIEW [rw_extract].[V_TMAPTAXAUTHORITYDETAILFUND]
AS
SELECT TAXAUTHORITY
      ,T1.TAXYEAR
      ,FUNDCODE
      ,PARENTFUNDCODE
      ,ASSESSEDMILLLEVY
      ,ALTERNATEMILLLEVY
      ,REALFLAG
      ,PPFLAG
      ,MAXLEVYINCLUDEFLAG
      ,SORTORDER
      ,JURISDICTIONID
      ,CAST(LASTUPDATED AS VARCHAR(22) ) LASTUPDATED
      ,LEVYTYPEID
      ,TAXDISTRICTID
      ,EXCLUDEREDUCEDRATEFLAG
      ,INCLUDEONTAXBILLFLAG
      ,PERMANENTRATE
      ,BILLINGRATE
      ,URDOTADJUSTMENTRATE
      ,BUDGETEDTAXVALUE
      ,BUDGETEDTAXRATE
      ,TRUNCATIONLOSSVALUE
      ,FUNDCATEGORYTYPEID
  FROM PRRW.ENCOMPASS.TMAPTAXAUTHORITYDETAILFUND T1
   ,(SELECT  cast(parameter_value AS numeric(4,0)) taxyear 
        from rw_extract.ETL_PARAMETER 
       where PARAMETER_NAME = 'ASSESSMENT_TAX_YEAR' ) P1
WHERE T1.TAXYEAR = p1.taxyear ;








