



CREATE VIEW [rw_extract].[V_TSGVACCTABSTVALUE_Old2]
AS
SELECT        VERSTART, VEREND, ACCOUNTNO, ABSTRACTCODE, T1.TAXYEAR, ACTUALVALUE, RAWASSESSEDVALUE, NEWCONSTVALUECHANGE, 
              NEWCONSTVALUECHANGEASSESSED, JURISDICTIONID, CAST(WRITEDATE AS VARCHAR(22)) AS WRITEDATE, SEQID, 
                       T1.TAXDISTRICT,  MILL.MILLLEVY AS MILLLEVY
FROM            PRRW.ENCOMPASS.TSGVACCTABSTVALUE AS T1 INNER JOIN
                (SELECT        DA.TAXDISTRICT, AF.TAXYEAR, SUM(AF.ASSESSEDMILLLEVY) AS MILLLEVY
                 FROM          PRRW.ENCOMPASS.TMAPTAXDISTRICTAUTHORITY AS DA INNER JOIN
                               PRRW.ENCOMPASS.TMAPTAXAUTHORITYDETAILFUND AS AF ON DA.TAXAUTHORITY = AF.TAXAUTHORITY 
                                                   AND DA.TAXYEAR = AF.TAXYEAR
                 WHERE DA.TAXDISTRICT <> '9999'
                 GROUP BY DA.TAXDISTRICT, AF.TAXYEAR) AS MILL ON T1.TAXDISTRICT = MILL.TAXDISTRICT 
                            AND T1.TAXYEAR = MILL.TAXYEAR








