



CREATE VIEW [rw_extract].[V_TSGNVALUE]
AS
SELECT   ACCOUNTNO
              ,TAXYEAR
              ,VALUEGROUPCODE
              ,TAXDISTRICT
              ,PARCELNO
              ,TAXDOLLARS
              ,ALTERNATETAXDOLLARS
              ,ADJUSTEDTAXDOLLARS
              ,ADJALTERNATETAXDOLLARS
              ,TOTALTAXDOLLARS
              ,ADJTOTALTAXDOLLARS
              ,ACTUALVALUE
              ,ADJACTUALVALUE
              ,ALTERNATEADJACTUALVALUE
              ,ADJALTERNATEADJACTUALVALUE
              ,ASSESSEDVALUE
              ,ALTERNATEASSESSEDVALUE
              ,ADJASSESSEDVALUE
              ,ADJALTERNATEASSESSEDVALUE
              ,MILLLEVY
              ,ALTERNATEMILLLEVY
              ,AVERAGEASSESSMENTRATIO
              ,AVERAGEALTASSESSMENTRATIO
              ,ACTUALPENALTYVALUE
              ,ALTERNATEACTUALPENALTYVALUE
              ,ASSESSEDPENALTYVALUE
              ,ALTERNATEASSDPENALTYVALUE
              ,PENALTYTAXDOLLARS
              ,ALTERNATEPENALTYTAXDOLLARS
              ,RAWASSESSEDVALUE
              ,RAWTAXDOLLARS
              ,TOTALPENALTYTAXDOLLARS
              ,IMPCURRENTUSE
              ,LANDMKTUSE
              ,JURISDICTIONID
              ,LASTUPDATED
              ,FINALADJASSESSEDVALUE
              ,FINALADJALTASSESSEDVALUE
              ,FINALADJASSDPENALTYVALUE
              ,FINALADJALTASSDPENALTYVALUE
              ,CCIAPPLICATIONID
              ,CAPOVERMARKETVALUE
FROM PRRW.ENCOMPASS.TSGNVALUE;





