





CREATE VIEW [rw_extract].[V_TSGVACCTABSTVALUE_NONPP_FRZ_Old_032618]
AS
SELECT     T1.VERSTART, T1.VEREND, T1.ACCOUNTNO, T1.ABSTRACTCODE, T1.TAXDISTRICT, T1.TAXYEAR, T1.ACTUALVALUE, T1.RAWASSESSEDVALUE, T1.NEWCONSTVALUECHANGE, T1.NEWCONSTVALUECHANGEASSESSED, T1.JURISDICTIONID, 
                  CAST(T1.WRITEDATE AS VARCHAR(22)) AS WRITEDATE, T1.SEQID, MILL.MILLLEVY
FROM        PRRW.ENCOMPASS.TSGVACCTABSTVALUE AS T1 INNER JOIN
                      (SELECT     DA.TAXDISTRICT, AF.TAXYEAR, SUM(AF.ASSESSEDMILLLEVY) AS MILLLEVY
                       FROM        PRRW.ENCOMPASS.TMAPTAXDISTRICTAUTHORITY AS DA INNER JOIN
                                         PRRW.ENCOMPASS.TMAPTAXAUTHORITYDETAILFUND AS AF ON DA.TAXAUTHORITY = AF.TAXAUTHORITY AND DA.TAXYEAR = AF.TAXYEAR
                       WHERE     (DA.TAXDISTRICT <> '9999')
                       GROUP BY DA.TAXDISTRICT, AF.TAXYEAR) AS MILL ON T1.TAXDISTRICT = MILL.TAXDISTRICT AND T1.TAXYEAR = MILL.TAXYEAR INNER JOIN
                      (SELECT     CAST(PARAMETER_VALUE AS NUMERIC(11, 0)) AS freeze_verstart
                       FROM        rw_extract.etl_parameter
                       WHERE     (PARAMETER_NAME = 'ASR_VALUE_FREEZE_VERSION_START_DATE')) AS P1 ON T1.VERSTART <= P1.freeze_verstart INNER JOIN
                      (SELECT     CAST(PARAMETER_VALUE AS NUMERIC(11, 0)) AS freeze_verend
                       FROM        rw_extract.etl_parameter AS etl_parameter_2
                       WHERE     (PARAMETER_NAME = 'ASR_VALUE_FREEZE_VERSION_END_DATE')) AS P2 ON T1.VEREND > P2.freeze_verend INNER JOIN
                      (SELECT     CAST(PARAMETER_VALUE AS NUMERIC(4, 0)) AS freeze_taxyear
                       FROM        rw_extract.etl_parameter AS etl_parameter_1
                       WHERE     (PARAMETER_NAME = 'ASR_VALUE_FREEZE_TAX_YEAR')) AS P3 ON T1.TAXYEAR = P3.freeze_taxyear
WHERE     (T1.ACCOUNTNO NOT LIKE 'P%')



