CREATE TABLE [dbo].[clin_search] (
    [account_no]                                      VARCHAR (30)    NOT NULL,
    [account_type]                                    VARCHAR (30)    NOT NULL,
    [state_parcel_no]                                 VARCHAR (30)    NULL,
    [legal_description]                               VARCHAR (MAX)   NULL,
    [township]                                        VARCHAR (15)    NULL,
    [section]                                         VARCHAR (15)    NULL,
    [range]                                           VARCHAR (15)    NULL,
    [person_code]                                     CHAR (18)       NOT NULL,
    [owner_name]                                      VARCHAR (256)   NOT NULL,
    [address_line_1]                                  VARCHAR (80)    NULL,
    [address_line_2]                                  VARCHAR (80)    NULL,
    [owner_address_city_name]                         VARCHAR (80)    NULL,
    [owner_address_zip_code]                          VARCHAR (30)    NULL,
    [ownership_percent]                               NUMERIC (9, 8)  NULL,
    [improvement_no]                                  NUMERIC (5)     NULL,
    [completed_percent]                               NUMERIC (7, 4)  NULL,
    [condition_type]                                  VARCHAR (50)    NULL,
    [improvement_net_sf]                              NUMERIC (15)    NULL,
    [improvement_sf]                                  NUMERIC (15)    NULL,
    [improvement_quality]                             VARCHAR (50)    NULL,
    [improvement_unit_type]                           VARCHAR (30)    NULL,
    [property_type]                                   VARCHAR (50)    NULL,
    [finished_basement_sf_by_improvement_no]          NUMERIC (38, 4) NULL,
    [unfinished_basement_sf_by_improvement_no]        NUMERIC (38, 4) NULL,
    [walkout_basement_flag]                           NUMERIC (38, 4) NULL,
    [no_of_fireplace_by_improvement_no]               NUMERIC (38, 4) NULL,
    [garage_sf_by_improvement_no]                     NUMERIC (38, 4) NULL,
    [porch_sf_by_improvement_no]                      NUMERIC (38, 4) NULL,
    [bathroom_count]                                  NUMERIC (7, 2)  NULL,
    [bedroom_count]                                   NUMERIC (7, 2)  NULL,
    [built_as_code]                                   VARCHAR (50)    NULL,
    [built_as_code_description]                       VARCHAR (100)   NULL,
    [built_as_sf]                                     NUMERIC (15)    NULL,
    [built_year]                                      VARCHAR (4)     NULL,
    [exterior_construction_type]                      VARCHAR (50)    NULL,
    [floor_material_type]                             VARCHAR (50)    NULL,
    [heat_type]                                       VARCHAR (50)    NULL,
    [interior_finish_type]                            VARCHAR (50)    NULL,
    [no_of_story]                                     NUMERIC (5, 2)  NULL,
    [roof_construction_type]                          VARCHAR (50)    NULL,
    [roof_material_type]                              VARCHAR (50)    NULL,
    [occupancy_detail_id]                             NUMERIC (15)    NULL,
    [improvement_occupancy_abstract_code]             VARCHAR (50)    NULL,
    [improvement_occupancy_abstract_code_description] VARCHAR (100)   NULL,
    [occupancy_code]                                  VARCHAR (50)    NULL,
    [occupancy_code_description]                      VARCHAR (100)   NULL,
    [occupancy_percent]                               NUMERIC (7, 4)  NULL,
    [sub_filing_recording_no]                         VARCHAR (30)    NULL,
    [subdivision_no]                                  VARCHAR (30)    NULL,
    [subdivision_name]                                VARCHAR (256)   NULL,
    [filing_no]                                       VARCHAR (30)    NULL,
    [filing_description]                              VARCHAR (80)    NULL,
    [lot_no]                                          VARCHAR (30)    NULL,
    [block_no]                                        VARCHAR (30)    NULL,
    [tract_no]                                        VARCHAR (30)    NULL,
    [tax_district_no]                                 VARCHAR (30)    NOT NULL,
    [total_actual_value]                              NUMERIC (38, 2) NULL,
    [total_assessed_value]                            NUMERIC (38, 2) NULL,
    [total_net_acres]                                 NUMERIC (38, 4) NULL,
    [land_abstract_detail_id]                         NUMERIC (15)    NULL,
    [land_abstract_abstract_code]                     VARCHAR (50)    NULL,
    [land_abstract_abstract_code_description]         VARCHAR (100)   NULL,
    [land_acres]                                      NUMERIC (20, 6) NULL,
    [land_sf]                                         NUMERIC (20, 6) NULL,
    [detail_id]                                       NUMERIC (15)    NULL,
    [attribute_type]                                  VARCHAR (30)    NULL,
    [attribute_subtype]                               VARCHAR (50)    NULL,
    [account_property_address_order_no]               INT             NULL,
    [primary_address_flag]                            BIT             NULL,
    [property_address]                                VARCHAR (125)   NULL,
    [property_address_street_name]                    VARCHAR (80)    NULL,
    [property_address_city_name]                      VARCHAR (50)    NULL,
    [property_address_zip_code]                       VARCHAR (10)    NULL
);


GO
CREATE NONCLUSTERED INDEX [dbo.clin_search_ix_test]
    ON [dbo].[clin_search]([account_type] ASC, [improvement_quality] ASC, [built_as_code_description] ASC, [improvement_occupancy_abstract_code_description] ASC, [subdivision_name] ASC, [tax_district_no] ASC, [land_abstract_abstract_code] ASC, [attribute_subtype] ASC, [property_address_street_name] ASC, [property_address_city_name] ASC, [property_address_zip_code] ASC, [improvement_sf] ASC, [total_actual_value] ASC, [land_acres] ASC)
    INCLUDE([account_no], [state_parcel_no], [legal_description], [township], [section], [range], [person_code], [owner_name], [address_line_1], [address_line_2], [owner_address_city_name], [owner_address_zip_code], [ownership_percent], [improvement_no], [completed_percent], [condition_type], [improvement_net_sf], [improvement_unit_type], [property_type], [bathroom_count], [bedroom_count], [built_as_code], [built_as_sf], [built_year], [exterior_construction_type], [floor_material_type], [heat_type], [interior_finish_type], [no_of_story], [roof_construction_type], [roof_material_type], [occupancy_detail_id], [improvement_occupancy_abstract_code], [occupancy_percent], [sub_filing_recording_no], [subdivision_no], [filing_no], [filing_description], [lot_no], [block_no], [tract_no], [total_assessed_value], [total_net_acres], [land_abstract_detail_id], [land_abstract_abstract_code_description], [land_sf], [detail_id], [attribute_type], [account_property_address_order_no], [primary_address_flag], [property_address]);

