

CREATE VIEW [dqm].[q_tbnsaleinventory]
WITH SCHEMABINDING
AS
SELECT        RECEPTIONNO, ACCOUNTNO, PARCELNO, INVENTORYEFFECTIVEDATE, SALEDATE, SALEPRICE, ADJSALEPRICE, SALEVALUEPER, ACCTTYPE, ECONOMICAREACODE, LEA, SUBDIVISION, VALUEAREACODE, 
                         PROPERTYTYPE, IMPCONDITIONTYPE, IMPQUALITY, IMPABSTRACTCODE, BLTASDESCRIPTION, BLTASYEARBUILT, PHYSICALAGE, ADJUSTEDYEARBUILT, EFFECTIVEAGE, IMPEXTERIOR, CLASSCODE, 
                         IMPCOUNT, BLTASTOTALUNITCOUNT, ROOMCOUNT, BEDROOMCOUNT, BATHCOUNT, FIXTURECOUNT, TOTALIMPSF, RESIDENTIALSF, COMMERCIALSF, CONDOIMPSF, OUTBUILDINGSF, IMPBLTASOTHER, 
                         LANDNETSF, MULTIPLEUSEFLAG, LANDABSTRACTCODE, LANDTYPE, LANDCERTIFICATIONCODE, LANDGROSSACRECOUNT, LANDGROSSSF, LANDGROSSFF, LANDGROSSUNITCOUNT, ZONINGCODE, 
                         PLATTEDFLAG, UNITNAME, ACCTADJSALEVALUEPER, TOTALLANDVALUETIMEOFSALE, TOTALACCTVALUETIMEOFSALE, PRIORYEARTAXROLLACTUALAMT, PRIORYEARTAXROLLASSESSED, 
                         LANDNETACRECOUNT, HVACTYPE, IMPUNITTYPE, IMPINTERIOR, ROOFCOVER, ROOFTYPE, INVENTORYOVERRIDEFLAG, ZONEDAREA, NBHDCODE1, NBHDCODE2, NBHDCODE3, NBHDCODE4, 
                         NBHDEXTENSION1, NBHDEXTENSION2, NBHDEXTENSION3, NBHDEXTENSION4, OCCCODE1, OCCCODE2, OCCCODE3, ACCTADJSALEPRICE, TIMEADJSALEPRICE, DEEDCODE, VALID1FLAG, VALID2FLAG, 
                         EXCLUDECODE1, EXCLUDECODE2, IMPROVEDFLAG, CONFIRMEDFLAG, BUSINESSNAME, STREETNO, PREDIRECTION, STREETNAME, STREETTYPE, POSTDIRECTION, PROPERTYCITY, PROPERTYZIPCODE, 
                         OUTBUILDINGCOUNT, LANDEXCESSSF, APPROACHTYPE, FLOORCOVER, CONDOIMPPERCENT, FINALSF, FINALSFVALUEPER, ZONEDAREAVALUEPER, GROUPINVENTORYFLAG, GRANTORNAME1, 
                         GRANTORNAME2, GRANTORADDRESS1, GRANTORADDRESS2, GRANTORCITY, GRANTORSTATECODE, GRANTORZIPCODE, SUBDIVISIONNAME, LOT, BLOCK, FILINGNO, TRACT, LEGALDESCRIPTION, 
                         GRANTEENAME1, GRANTEENAME2, GRANTEEADDRESS1, GRANTEEADDRESS2, GRANTEECITY, GRANTEESTATECODE, GRANTEEZIPCODE, SALEINVENTORYON0, SALEINVENTORYON1, SALEINVENTORYON2, 
                         OCCCODEDESCRIPTION1, OCCCODEDESCRIPTION2, OCCCODEDESCRIPTION3, SALEINVENTORYOD0, SALEINVENTORYOD1, SALEINVENTORYOM0, SALEINVENTORYOM1, SALEINVENTORYOT0, 
                         SALEINVENTORYOT1, LANDNETFF, JURISDICTIONID, OUTOFAREASALEJURISDICTION, LASTUPDATED, GRANTEEPROVINCE, GRANTEECOUNTRY, GRANTEEPOSTALCODE, OCCCOMPLETEDPCT, 
                         PRIMARYUSECODE, GRANTORPROVINCE, GRANTORCOUNTRY, GRANTORPOSTALCODE, LANDNETUNITCOUNT, TOTALFINISHEDSF, BLTASCODE, TOTALUNFINISHEDSF, SALERATIO
FROM            asr_staging.s_tbnsaleinventory si
WHERE NOT EXISTS
				(SELECT 1 FROM dqm.s_tbnsaleinventory_err sie
				WHERE si.RECEPTIONNO = sie.RECEPTIONNO);


