





CREATE view [dqm].[q_tblacctpropertyaddress] as 
SELECT -- all columns
s.VERSTART, s.VEREND, s.ACCOUNTNO, s.BUILDINGID, s.PREDIRECTION, s.STREETNO, s.UNITNAME, s.POSTDIRECTION, s.STREETTYPE, s.STREETNAME, 
s.PROPERTYZIPCODE, s.PROPERTYCITY, s.ORDERNO, s.ACCTPROPERTYADDRESSON0, s.ACCTPROPERTYADDRESSON1, s.ACCTPROPERTYADDRESSON2, 
s.BUSINESSNAME, s.ACCTPROPERTYADDRESSOD0, s.ACCTPROPERTYADDRESSOD1, s.ACCTPROPERTYADDRESSOM0, s.ACCTPROPERTYADDRESSOM1, 
s.ACCTPROPERTYADDRESSOT0, s.ACCTPROPERTYADDRESSOT1, s.JURISDICTIONID, s.PROPERTYADDRESSCODE, s.WRITEDATE, s.LOCATIONID, s.SEQID, s.ETL_RUN_TIME
FROM [asr_staging].[s_tblacctpropertyaddress] s
LEFT OUTER JOIN [dqm].[S_TBLACCTPROPERTYADDRESS_ERR] e
ON s.ACCOUNTNO = e.ACCOUNTNO
WHERE e.ACCOUNTNO IS NULL;









