


CREATE view [dqm].[q_tblsale] as 
select
VERSTART, VEREND, cast(RECEPTIONNO as varchar(20)) AS RECEPTIONNO, BOOK, PAGE, GRANTOR, GRANTEE, DOCUMENTDATE
, SALEDATE, DOCUMENTFEE, DEEDCODE, PENALTYFLAG, PENALTYDATE, SALEPRICE, PPADJAMOUNT, GOODWILLADJAMOUNT, OTHERADJAMOUNT
, TIMEADJ, DOWNPAYMENTAMOUNT, DOWNPAYMENTPCT, NOTEAMOUNT, INTERESTRATEPCT, LOANTERM, POINTSPAID, POINTSPAIDBY, LOANINSTITUTION
, MKTRATEPCT, PAYMENTAMOUNT, RECOURSEFLAG, TENANT, VALID1FLAG, VALID2FLAG, CONFIRMEDFLAG, EXCLUDECODE1, EXCLUDECODE2
, IMPROVEDFLAG, CONFIRMBY, CONFIRMMETHOD, CONFIRMDATE, COMMENTS, NONSALEFLAG, SALEON0, SALEON1, SALEON2, SALEOD0, SALEOD1
, SALEOM0, SALEOM1, SALEOT0, SALEOT1, JURISDICTIONID, WRITEDATE, BALLOONPAYMENTYEAR, TRANSFERDECLARATIONFLAG, TRANSFERDECLARATIONDATE, QUESTIONNAIREMAILDATE, QUESTIONNAIRERETURNDATE, SEQID
from [asr_staging].[s_tblsale] s
where not exists 
(SELECT 1 FROM [dqm].[S_TBLSALE_ERR] se
WHERE s.RECEPTIONNO = se.RECEPTIONNO);


