
CREATE VIEW [dqm].[q_tbnsaleinventorydetail2]
WITH SCHEMABINDING
AS
SELECT        RECEPTIONNO, ACCOUNTNO, DETAILTYPE, INVENTORYDETAILTYPE, INVENTORYDETAILDESCRIPTION, INVENTORYUNITCOUNT, SALEINVENTORYDETAILON0, SALEINVENTORYDETAILON1, 
                         SALEINVENTORYDETAILON2, SALEINVENTORYDETAILOD0, SALEINVENTORYDETAILOD1, SALEINVENTORYDETAILOM0, SALEINVENTORYDETAILOM1, SALEINVENTORYDETAILOT0, SALEINVENTORYDETAILOT1, 
                         YEARBUILT, JURISDICTIONID, LASTUPDATED, INVENTORYDETAILID
FROM            asr_staging.s_tbnsaleinventorydetail AS sid
WHERE        (NOT EXISTS
                             (SELECT        1 AS Expr1
                               FROM            dqm.s_tbnsaleinventorydetail_err AS side
                               WHERE        (sid.RECEPTIONNO = RECEPTIONNO)))

