

CREATE view [dqm].[q_tlkpabstractcode]
WITH SCHEMABINDING 
AS 
select -- all columns
ABSTRACTCODE, ABSTRACTDESCRIPTION, EQUIVALENCEABSTRACTCODE, ROLLABSTRACTVALUEFLAG, VALUEGROUPCODE, ACTUALPRECISION, ACTUALMINIMUMVALUE, ASSESSEDPRECISION, ASSESSEDMINIMUMVALUE, ACTUALROUNDTYPE, ASSESSEDROUNDTYPE, USEVALUEFLAG, ADJACTUALPRECISION, ADJACTUALMINIMUMVALUE, ADJACTUALROUNDTYPE, ADJASSESSEDPRECISION, ADJASSESSEDMINIMUMVALUE, ADJASSESSEDROUNDTYPE, ADJALTACTUALPRECISION, ADJALTACTUALMINVALUE, ADJALTACTUALROUNDTYPE, ADJALTASSESSEDPRECISION, ADJALTASSESSEDMINVALUE, ADJALTASSESSEDDROUNDTYPE, ALTASSESSEDPRECISION, ALTASSESSEDMINIMUMVALUE, ALTASSESSEDROUNDTYPE, SHOWADMINFLAG, CLASSIFICATIONID, LOCALGROWTHEXEMPTFLAG, EXPORTCNTGROUPEXCLUSIONFLAG, SORTORDER, ACTIVEFLAG, LIMITTOABSTTYPE, JURISDICTIONID, LASTUPDATED, ABSTRACTCATEGORYCODE
from [asr_staging].[s_tlkpabstractcode]
where ABSTRACTCODE not in (select ABSTRACTCODE from [dqm].[s_tlkpabstractcode_err]);


