

CREATE VIEW [asr_staging_query].[v_tsgvacctabstvalue_npp_reg]
AS
SELECT

  INGRP2.ABSTCODE ABSTCODE,
  --identity account_valuation_eid,
  W_PUBLISHED_ACCOUNT.ACCOUNT_NO ACCOUNT_NO,
  INGRP2.NEWGROWTHACTVAL NEWGROWTHACTVAL,
  INGRP2.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  INGRP2.NET_ACRES NET_ACRES,
  INGRP2.NEW_GROWTH_FLAG NEW_GROWTH_FLAG
FROM
   ( SELECT
  INGRP1.ACCOUNTNO ACCOUNTNO,
  INGRP1.ABSTCODE ABSTCODE,
  INGRP1.NEWGROWTHACTVAL NEWGROWTHACTVAL,
  INGRP1.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  INGRP1.NET_ACRES NET_ACRES,
  INGRP1.NEW_GROWTH_FLAG NEW_GROWTH_FLAG
FROM
   ( SELECT
  AGGREGATOR.ACCOUNTNO ACCOUNTNO,
  AGGREGATOR.ABSTRACTCODE ABSTCODE,
  AGGREGATOR.NEWGROWTHACTUAL NEWGROWTHACTVAL,
  AGGREGATOR.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  AGGREGATOR.NETACRES NET_ACRES,
  'N' NEW_GROWTH_FLAG
FROM
  (SELECT
  AGG_INPUT.ACCOUNTNO$1 ACCOUNTNO,
  AGG_INPUT.ABSTRACTCODE$1 ABSTRACTCODE,
  SUM(AGG_INPUT.ACTUALVALUE_1) NEWGROWTHACTUAL,
  SUM(AGG_INPUT.RAWASSESSEDVALUE_1) NEWGROWTHASSESSVAL,
  SUM(AGG_INPUT.LANDACRES) NETACRES
FROM
  (SELECT
  S_TSGVACCTABSTVALUE_NPP_REG.ACCOUNTNO ACCOUNTNO$1,
  S_TSGVACCTABSTVALUE_NPP_REG.ABSTRACTCODE ABSTRACTCODE$1,
  S_TSGVACCTABSTVALUE_NPP_REG.ACTUALVALUE ACTUALVALUE_1,
  S_TSGVACCTABSTVALUE_NPP_REG.RAWASSESSEDVALUE RAWASSESSEDVALUE_1,
  LANDABST.LANDACRES LANDACRES
FROM
    ASR_STAGING.S_TSGVACCTABSTVALUE_NPP_REG  S_TSGVACCTABSTVALUE_NPP_REG   
 LEFT OUTER JOIN  
 ( SELECT
  AGGREGATOR_0.ACCOUNTNO$2 ACCOUNTNO,
  isnull(AGGREGATOR_0.LANDACRES$1 ,0) LANDACRES,
  AGGREGATOR_0.ABSTRACTCODE$2 ABSTRACTCODE
FROM
  (SELECT
  S_TBLLANDABSTRACT.ACCOUNTNO ACCOUNTNO$2,
  S_TBLLANDABSTRACT.ABSTRACTCODE ABSTRACTCODE$2,
  SUM(S_TBLLANDABSTRACT.LANDACRES) LANDACRES$1
FROM
  ASR_STAGING.S_TBLLANDABSTRACT  S_TBLLANDABSTRACT
GROUP BY
S_TBLLANDABSTRACT.ACCOUNTNO , S_TBLLANDABSTRACT.ABSTRACTCODE,S_TBLLANDABSTRACT.ACCOUNTNO ) AGGREGATOR_0  ) LANDABST ON ( (( S_TSGVACCTABSTVALUE_NPP_REG.ACCOUNTNO = LANDABST.ACCOUNTNO )) AND (( S_TSGVACCTABSTVALUE_NPP_REG.ABSTRACTCODE = LANDABST.ABSTRACTCODE )) )) AGG_INPUT 
GROUP BY
AGG_INPUT.ACCOUNTNO$1 , AGG_INPUT.ABSTRACTCODE$1) AGGREGATOR  ) INGRP1   
 JOIN   VALUATION_CLASS_CODE  VALUATION_CLASS_CODE ON ( ( INGRP1.ABSTCODE = VALUATION_CLASS_CODE.VALUATION_CLASS_CODE ) ) ) INGRP2   
 JOIN   W_PUBLISHED_ACCOUNT  W_PUBLISHED_ACCOUNT ON ( ( INGRP2.ACCOUNTNO = W_PUBLISHED_ACCOUNT.ACCOUNT_NO ) );


