


CREATE VIEW [asr_staging_query].[v_tsgvacctabstvalue_pp_reg]
AS
SELECT
  INGRP2.ABSTCODE ABSTCODE,
  --IDENTITY ACCOUNT_VALUATION_EID,
  W_PUBLISHED_ACCOUNT.ACCOUNT_NO ACCOUNT_NO,
  INGRP2.NEWGROWTHACTVAL NEWGROWTHACTVAL,
  INGRP2.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  INGRP2.NET_ACRES NET_ACRES,
  INGRP2.NEW_GROWTH_FLAG NEW_GROWTH_FLAG
FROM
   ( SELECT
  INGRP1.ACCOUNTNO ACCOUNTNO,
  INGRP1.ABSTCODE ABSTCODE,
  INGRP1.NEWGROWTHACTVAL NEWGROWTHACTVAL,
  INGRP1.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  INGRP1.NET_ACRES NET_ACRES,
  INGRP1.NEW_GROWTH_FLAG NEW_GROWTH_FLAG
FROM
   ( SELECT
  AGGREGATOR.ACCOUNTNO ACCOUNTNO,
  AGGREGATOR.ABSTRACTCODE ABSTCODE,
  AGGREGATOR.NEWGROWTHACTUAL NEWGROWTHACTVAL,
  AGGREGATOR.NEWGROWTHASSESSVAL NEWGROWTHASSESSVAL,
  AGGREGATOR.NETACRES NET_ACRES,
  'N' NEW_GROWTH_FLAG
FROM
  (SELECT
  AGG_INPUT.ACCOUNTNO$1 ACCOUNTNO,
  AGG_INPUT.ABSTRACTCODE$1 ABSTRACTCODE,
  SUM(AGG_INPUT.ACTUALVALUE_1) NEWGROWTHACTUAL,
  SUM(AGG_INPUT.RAWASSESSEDVALUE_1) NEWGROWTHASSESSVAL,
  SUM(AGG_INPUT.LANDACRES) NETACRES
FROM
  (SELECT
  S_TSGVACCTABSTVALUE_PP_REG.ACCOUNTNO ACCOUNTNO$1,
  S_TSGVACCTABSTVALUE_PP_REG.ABSTRACTCODE ABSTRACTCODE$1,
  S_TSGVACCTABSTVALUE_PP_REG.ACTUALVALUE ACTUALVALUE_1,
  S_TSGVACCTABSTVALUE_PP_REG.RAWASSESSEDVALUE RAWASSESSEDVALUE_1,
  LANDABST.LANDACRES LANDACRES
FROM
    ASR_STAGING.S_TSGVACCTABSTVALUE_PP_REG  S_TSGVACCTABSTVALUE_PP_REG   
 LEFT OUTER JOIN  ( SELECT
  S_TBLLANDABSTRACT.ACCOUNTNO ACCOUNTNO,
  ISNULL(S_TBLLANDABSTRACT.LANDACRES ,0) LANDACRES,
  S_TBLLANDABSTRACT.ABSTRACTCODE ABSTRACTCODE
FROM
  ASR_STAGING.S_TBLLANDABSTRACT  S_TBLLANDABSTRACT ) LANDABST ON ( (( S_TSGVACCTABSTVALUE_PP_REG.ACCOUNTNO = LANDABST.ACCOUNTNO )) AND (( S_TSGVACCTABSTVALUE_PP_REG.ABSTRACTCODE = LANDABST.ABSTRACTCODE )) )) AGG_INPUT 
GROUP BY
AGG_INPUT.ACCOUNTNO$1 , AGG_INPUT.ABSTRACTCODE$1 ) AGGREGATOR  ) INGRP1   
 JOIN   VALUATION_CLASS_CODE  VALUATION_CLASS_CODE ON ( ( INGRP1.ABSTCODE = VALUATION_CLASS_CODE.VALUATION_CLASS_CODE ) ) ) INGRP2   
 JOIN   W_PUBLISHED_ACCOUNT  W_PUBLISHED_ACCOUNT ON ( ( INGRP2.ACCOUNTNO = W_PUBLISHED_ACCOUNT.ACCOUNT_NO ) );



